### ISSUE TITLE
HTML5 support

### ISSUE THREAD

**Issue by tonioo** [tonioo/modoboa#184]
**Originally created by Antoine Nguyen on 2011-10-03T14:04:53Z**

Convert existing templates to HTML5. 

+Note+: Given my current knowledge of HTML5, I don't know if other parts (maybe javascript?) are impacted.

**Comment by eberkund** [comment]
I could help with this if you are interested

**Comment by tonioo** [comment]
Help is always appreciated !

**Comment by eberkund** [comment]
What needs to be done for this? Is it as simple as replacing the files in the modoboa/templates/ directory?

Also feature-wise, what is the goal? Other than to simply update the markup.

**Comment by tonioo** [comment]
This is a pretty old ticket. When I created it, I just wanted to update the markup and maybe make use of the new history API (in place of the current anchor based navigation).

Now, I'd say modo should be rewritten in client/server way : an REST API on the backend and a JS frontend (angular or something like that).

What do you think ?

**Comment by patrickbenkoetter** [comment]
* Antoine Nguyen <reply@reply.github.com>:
> This is a pretty old ticket. When I created it, I just wanted to update the markup and maybe make use of the new history API (in place of the current anchor based navigation).
> 
> Now, I'd say modo should be rewritten in client/server way : an REST API on the backend and a JS frontend (angular or something like that).
> 
> What do you think ?

+1

Rendering in client
Logic in server


-- 
[*] sys4 AG
 
https://sys4.de, +49 (89) 30 90 46 64
Franziskanerstraße 15, 81669 München
 
Sitz der Gesellschaft: München, Amtsgericht München: HRB 199263
Vorstand: Patrick Ben Koetter, Marc Schiffbauer
Aufsichtsratsvorsitzender: Florian Kirstein

**Comment by eberkund** [comment]
Sounds good, I don't mind doing that although I don't know much Python. I guess since it needs a new backend API this would come when there is a major revision and the front end needs to be rewritten?

**Comment by tonioo** [comment]
Yes, you're totally right :)

**Comment by tonioo** [comment]
I close this issue for now. I'll create new ones when needed.
