### ISSUE TITLE
Splitdomains

### ISSUE THREAD

**Issue by patrickbenkoetter** [tonioo/modoboa#490]
We should find a way to allow 'split-domains', that is: some mails go to the local mailstore and some are rerouted to a relaydomain. Activating a 'splitdomain' should be an upgrade path from e.g. a local domain that doesn't require someone to delete or modify the existing domain.

Maybe running a local- and a relaydomain in parallel already does what we want. Check and see if this needs better visibility (tag) etc.

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-admin-relaydomains#3
