### ISSUE TITLE
Dashboard for administrators

### ISSUE THREAD

**Issue by tonioo** [tonioo/modoboa#517]
Modoboa lacks a nice dashboard to provide administrators a quick overview of platform's health and activity.

Does anyone know a library to implement this quickly?

**Comment by eberkund** [comment]
What kind of information are you looking to display?

**Comment by tonioo** [comment]
Graphics, statistics about domains/mailboxes, server health, latest quarantined messages, etc.

**Comment by tonioo** [comment]
A simple dashboard has been added but it is not customizable atm.
