### ISSUE TITLE
Optional Description for Aliases

### ISSUE THREAD

**Issue by patsoffice** [tonioo/modoboa#522]
A common thing that I do is use opaque aliases (part of the md5sum of the date when I created the alias for example) so that I can have a single, throw-away address per company. It would be nice to have that be settable and something I can query in Modoboa. I am already storing it locally in my DB and have written scripts to query it. But it would be better for users to be able to do all of this via the UI.

+1 for aliases that have an expiration date. Email addresses for rebates or dealing with a buyer/seller online. When the expiration date comes around, you simply drop the alias.

Thanks, Pat

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-admin#3
