### ISSUE TITLE
Add support for the Roundcube password plugin

### ISSUE THREAD

**Issue by SomeGeek** [tonioo/modoboa#523]
We should create a simple driver for the Roundcube password changing plugin: https://github.com/roundcube/roundcubemail/tree/master/plugins/password

Using the API of Modoboa. Roundcube is a very popular webmail client. Doing this has the advantage of not having to have the database world-accessible.

**Comment by jonathan00** [comment]
FYI,
vboxadm also implemented an HTTP API on the server side and an roundcube plugin on client side to let users change their passwords (and some other things). Maybe that helps you ;-)

Server side:
https://github.com/dominikschulz/VBoxAdm/blob/master/lib/VBoxAdm/Controller/API.ipm

Client side:
https://github.com/dominikschulz/roundcube-plugin-vboxadm/blob/master/roundcube/plugins/vboxadm/vboxadm.php

**Comment by tonioo** [comment]
So, the API part is done. Now, we need a roundcube plugin.
