### ISSUE TITLE
Add Auto-Submitted, In-Reply-To, References, Precedence headers in autoreply messages

### ISSUE THREAD

**Issue by themr0c** [tonioo/modoboa#544]
According to https://tools.ietf.org/html/rfc3834#section-3.1 some fields are mandatory in autoreply messages:

The In-Reply-To and References fields SHOULD be provided in the header of a response message if there was a Message-ID field in the subject message.

The Auto-Submitted field, with a value of "auto-replied", SHOULD be included in the message header of any automatic response.

The Subject field SHOULD contain a brief indication that the message is an automatic response, followed by contents of the Subject field (or a portion thereof) from the subject message.  The prefix "Auto:" MAY be used as such an indication. If used, this prefix SHOULD be followed by an ASCII SPACE character (0x20).

A response MAY include a Precedence field. The field-body of the Precedence field MAY consist of the text "junk", "list", "bulk", or other text deemed appropriate by  the responder.

[NB: for Precedence: auto_reply is also an option]

Actual message is like : 

```
Return-Path: <uuu@uuu.uuu>
Delivered-To: ttt@ttt.ttt
Received: [...]
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject: I'm off
From: Uuu Uuu <uuu@uuu.uuu>
To: ttt@ttt.ttt
Message-ID: <NNN@vvv.vvv.vvv>
User-Agent: Modoboa
Date: Thu, 10 Apr 2014 09:06:09 +0200

I'm currently off. I'll answer as soon as I come back.

Best regards,
```

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-postfix-autoreply#3
