### ISSUE TITLE
Documentation : Virtual Machine update?

### ISSUE THREAD

**Issue by almereyda** [tonioo/modoboa#560]
I have tried to use your virtual machine. After converting it to qemu2 I would have loaded it with `libvirt`.

Unfortunately it doesn't embody the virtio kernel modules, nor were I able to hack them in via a virtual serial console. So network access never really worked.

After 6 hrs of trying around, a quick test with a fresh CentOS Minimal image showed my network was working as expected.

Those links sent me in the right direction:

* https://wiki.debian.org/DebianKVMGuests (didn't work?!)
* http://debianforum.de/forum/viewtopic.php?f=32&t=130248

In the end I've learned a lot about `libvirt` and its design.

**Comment by eberkund** [comment]
It worked for me, although I think it is a much older version than the online demo they have up

**Comment by tonioo** [comment]
Yes, the VM is really outdated. I wonder if I should continue to distribute it or not...

**Comment by eberkund** [comment]
Well with the online demo available it seems rather redundant IMO. I was just using it because earlier this week when I tried, the online demo was down.
