### ISSUE TITLE
Docs: write about db role creation for mailboxes owner

### ISSUE THREAD

**Issue by rominf** [tonioo/modoboa#564]
When I launched `manage.py handle_mailbox_operations` from `vmail` (mailboxes owner) I got error:
```
OperationalError: FATAL:  role "vmail" does not exist
```

I fixed it by creating `vmail` user and granting all permissions to database `modoboa` (I don't know how much permission should I give).

**Comment by tonioo** [comment]
@rominf I still don't understand why you needed to create this role. Any command executed through manage.py uses the credentials configured in the settings.py file. What is/was the name of the user you configured ?

**Comment by rominf** [comment]
Thank you for answer, @tonioo. That was 2 years ago, I don't remember the details. I think this issue is irrelevant.

**Comment by tonioo** [comment]
Sorry for the delay and thanks for your answer ;)
