### ISSUE TITLE
Webmail: Bug: Error: ["Mailbox doesn't exist: virtual"]

### ISSUE THREAD

**Issue by piwats** [tonioo/modoboa#581]
Hello Antoine,

I recently discovered dovecots' virtual mailboxes (http://wiki2.dovecot.org/Plugins/Virtual).

The config is pretty simple:
from 10-mail.conf:

namespace {
  prefix = virtual/
  separator = /
  location = virtual:~/dbox/virtual
}

After having them enabled and configured, Modoboa webmailer refuses to work as desired with this error, no erros in the log:

"Error: ["Mailbox doesn't exist: virtual"]"

If I disable the aforementioned namespace, the webmailer is working properly again.

This is definitely not a blocker or high priority. Yet there might be some use cases and users who depend on this.

-Paul

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-webmail#7
