### ISSUE TITLE
amavis tables not created

### ISSUE THREAD

**Issue by zodman** [tonioo/modoboa#583]
Hi i create a fabric install script for modoboa.

https://bitbucket.org/zodman/vagrant_modoboa/src/d8a4fbe65e0296f0a5493763a3aefd45b710a4ec/fabfile.py?at=master

Here the code

when it finished the database amavis no had tables. ( missing the tables for modoboa.extensions.amavis)

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-amavis#10
