### ISSUE TITLE
Mail activity

### ISSUE THREAD

**Issue by aanriot** [tonioo/modoboa#602]
Hello,

As done in MailCleaner, it could be useful to have a page displaying the mail activity:

- Arrival date / status ;
- Envelope sender ;
- Recipients ;
- Status (spam / virus / bad header mail) ;
- Deliver status / date.

with a few filters:

- The liste of the configured domains
- A type field (e.g. to look for logs of a specific mailbox)
- Date

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-amavis#9
