### ISSUE TITLE
Can't log in as normal user

### ISSUE THREAD

**Issue by piwats** [tonioo/modoboa#606]
This is the error I get when I try to login as a normal user in modoboa:
admin login is fine, normal user is obviously not:

Environment:

Request Method: GET
Request URL: https://mysite.com/modoboa/

Django Version: 1.5.10
Python Version: 2.7.7
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'south',
 'reversion',
 'modoboa',
 'modoboa.core',
 'modoboa.lib',
 'modoboa.extensions.admin',
 'modoboa.extensions.postfix_relay_domains',
 'modoboa.extensions.limits',
 'modoboa.extensions.postfix_autoreply',
 'modoboa.extensions.webmail',
 'modoboa.extensions.stats',
 'modoboa.extensions.sievefilters',
 'modoboa.extensions.amavis')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.transaction.TransactionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'modoboa.lib.middleware.AjaxLoginRedirect',
 'modoboa.lib.middleware.CommonExceptionCatcher',
 'modoboa.lib.middleware.ExtControlMiddleware',
 'modoboa.lib.middleware.RequestCatcherMiddleware')

Traceback:
File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py" in get_response
  113.                         response = callback(request, *callback_args, **callback_kwargs)
File "/usr/lib64/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  25.                 return view_func(request, *args, **kwargs)
File "/usr/lib64/python2.7/site-packages/modoboa/lib/webutils.py" in topredirection
  159.             path = infos["url"] if infos["url"] else infos["name"]

Exception Type: TypeError at /
Exception Value: 'NoneType' object has no attribute '__getitem__'

----

Also I find this lines in the log:

Internal Server Error: /modoboa/quarantine/process/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/modoboa/extensions/amavis/views.py", line 268, in process
    return delete(request, ids)
  File "/usr/lib64/python2.7/site-packages/modoboa/extensions/amavis/lib.py", line 30, in wrapped_f
    return f(request, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/modoboa/extensions/amavis/views.py", line 163, in delete
    r, i = mid.split()
ValueError: too many values to unpack

What is going on?

-Paul

**Comment by machinefixer** [comment]
I got same problem, and I didn't see any error alert in my modoboa log. 
Here's my package version list:
* Ubuntu 14.04
* Nginx/1.4.6(Ubuntu)
* Postfix/2.11.0
* Dovecot/2.2.9
* Modoboa/1.2.0
* Gunicorn/19.1.1

Any idea?

**Comment by tonioo** [comment]
Try with DEBUG = True (settings.py) and please use a tool like firebug to catch AJAX errors.

**Comment by machinefixer** [comment]
I just fix my problem. I forgot that I create a test user 'abc' on my Ubuntu before I install modoboa, and later I create a test normal user with same user name 'abc@mydomain' in Modoboa, so it seems the Modoboa user name conflict with the system user. 
After I delete my system test user, I am able to login into Modoboa as 'abc@mydomain'.
