### ISSUE TITLE
Proposal: Provide our own Postfix/Dovecot packages

### ISSUE THREAD

**Issue by SomeGeek** [tonioo/modoboa#619]
Most of the default versions in the repository's are outdated, especially when it comes down to new (security) features. Providing our own packages, we can be sure about the version-compatibility.

**Comment by Kegeruneku** [comment]
I agree with piwats. Modoboa manages a mail service, using databases to provide independence. It is not its job to provide packages for a MTA/... Let's stay on the right side of the fence.

Also, by experience, distros do quite a good job at maintaining security patches and providing new versions. The overhead and complexity of building packages for different OSes, arches (yep, Postfix is C code, not platform independent at all) can easily reach exponential complexity. Trust me, if your EL6 postfix package is too old for you, use EL7. If you think it has security issues, I certainly think RedHat has already made patches.

Please keep up the good job a maintaining a good and efficient mail service management platform, leave the packaging burden to those who have enough time and resources to do so :)

**Comment by carragom** [comment]
I have to agree with @piwats and @Kegeruneku. Let the packaging of related software to the distros.

**Version Compatibility**
This can be easily solved by stating in the release notes that Modoboa version X requires Postfix version Y, Dovecot version Z and so on.

**Security**
Most distros keep their packages pretty secure and I would rather trust packages from my distro of choice than someone else.

That said, I do think that creating a package of **Modoboa** itself that **integrates** with specific distros would be a great idea and would increase Modoboa user base a lot. As long as we keep the manual installation method as a first class citizen with the excellent documentation it has enjoyed so far.

**Comment by tonioo** [comment]
Looks like we're done with this proposal :)
