### ISSUE TITLE
DomainKeys Support

### ISSUE THREAD

**Issue by SomeGeek** [tonioo/modoboa#625]
Add support for DomainKeys.

http://en.wikipedia.org/wiki/DomainKeys

**Comment by Kegeruneku** [comment]
This is a good idea, also AFAIK amavisd-new already supports DKIM. cf. http://www.ijs.si/software/amavisd/amavisd-new-docs.html#dkim

**Comment by tonioo** [comment]
Indeed, something is already on the list ;)

https://github.com/modoboa/modoboa-amavis/issues/8

**Comment by tonioo** [comment]
Since Domain Keys is considered as a deprecated technology, I don't see any interest about working on it. DKIM is the way to go now.
