### ISSUE TITLE
Webmail Error: "Modoboa: command UID => got more than 10000 bytes"

### ISSUE THREAD

**Issue by piwats** [tonioo/modoboa#635]
Hello,

suddenly, when trying to access the INBOX in the Webamiler under 1.1.7 I am getting this error:

```Modoboa: command UID => got more than 10000 bytes```

No emails are being shown in the list apart from this error.

Also I get nor errors in my log when this happens...

-Paul

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-webmail#4

**Comment by vingeni** [comment]
With the master HEAD version of webmail, I am able to read an inbox with more than 18000 emails.
Could you tell me how many mails do you need to reproduce the bug ?

**Comment by piwats** [comment]
Wow, 18000 emails in the inbox - how to reproduce that? :-)

I do not know how, but it seems, that I have no troubles with the webmail since 1.3.

Still, the error is common with django/python.

-Paul
