### ISSUE TITLE
Permissions and relay domains

### ISSUE THREAD

**Issue by aanriot** [tonioo/modoboa#642]
Hello,

As a reminder, it would be nice to be able to apply permissions to relay domains.

For example, it could be possible to allow a reseller account to check the quarantine of its owned domains.

Thanks.

**Comment by andrewyager** [comment]
This is a feature we would love to see too. We have a number of resellers who would like to log in to see the quarantine items that just belong to them.

**Comment by tonioo** [comment]
I understand it but I have limited time to work on Modoboa since it is just a free software. Do not hesitate to contribute (code, money, time, whatever) if you'd like it to evolve faster ;-)

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-admin-relaydomains#2
