### ISSUE TITLE
Horde integration with modoboa db

### ISSUE THREAD

**Issue by piwats** [tonioo/modoboa#663]
Hello,

I stumbled upon Horde webmail. I know that modoboa has its own webmailer, which unfortunately has (hopefully temporary) its limitations due to python (#635). However, a webmailer is still needed.

Having now played with horde I came across some interesting options:

It is able to authenticate and manage users with not only some horde standard queries but also with custom ones. (Apart from authentication via imap and other options)

These are the points, which horde allows custom queries to, and some other settings, too:

* Authenticate the user
* Add user
* Get a user's password
* Update user
* Reset a user's password
* Remove user
* List users
* Check if an account exists

* The password hashing algorithm to use
* Prepend the password algorithm to the password value?

"\L" will be replaced by the user's login
"\P" will be replaced by the user's password
"\O" will be replaced by the old user's login (required for update)
Eg: "SELECT * FROM users WHERE uid = \L AND passwd = \P AND billing = 'paid'"

Would it be possible to get horde working together with modoboa via the db?

Thanks you a lot and happy holidays :)

**Comment by tonioo** [comment]
@piwats Modoboa now provides a basic API (for example, it is possible to update user passwords)

Is that what you were talking about ?

**Comment by tonioo** [comment]
@piwats The API has been completed and now allows operations on accounts. Since I don't know Horde, I'm not going to develop such a connector but maybe Horde's team would be interested to do it. I suggest you move the issue to Horde's repository :)
