### ISSUE TITLE
Webmail: Authentication Failed

### ISSUE THREAD

**Issue by machinefixer** [tonioo/modoboa#678]
![screen shot 2015-01-29 at 17 16 13](https://cloud.githubusercontent.com/assets/5358642/5955168/f76695bc-a7da-11e4-89a6-01449bd1a410.png)

I've debugged this error for a while, it happens all the time once I try to use webmail interface, something like 'Password mismatch' or 'auth: Debug: client passdb out: FAIL' in my log file. But after I refreshed my webmail page by a couple of times the authentication come back to normal, and Modoboa works fine. It might be tiny configuration mistake, but pretty annoying. Maybe somewhere in Dovecot has a configuration item like 'xxx_timeout'?

**Comment by tonioo** [comment]
Maybe an issue with your dovecot configuration?

**Comment by machinefixer** [comment]
Thanks for replying! I've check all my dovecot configuration, since the problem happens occasionally, it can be some kind of "Timeout", I changed my local VPS to another which provide more stable web connection, then everything works fine after re-deploy modoboa.

**Comment by tonioo** [comment]
Great. So I close this issue.

**Comment by moufmouf** [comment]
Hey Tonioo,

Sorry to bump this issue up but we are facing exactly the same problem.

The webmail fails completely randomly (maybe one in 5 requests...)

Also, when it fails, I can see this in the logs:

```
Jun 19 03:15:15 modoboa dovecot: imap-login: Disconnected (auth failed, 1 attempts in 2 secs): user=<admin@mailtest.thecodingmachine.com>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, secured, session=<JuUhM9wY+gB/AAAB>
```

I'm using the latest version of modoboa (1.3.3) that I tried to migrate from the virtual image provided.
I'm pretty sure this must be a configuration issue, but I have no clue on how to pinpoint it. Also, I tried to enable SASL on postfix, I don't know if this can be related. My /etc/dovecot/conf.d/10-master.conf file looks like this:

```
service auth {
  unix_listener auth-userdb {
    #mode = 0666
    #user = 
    #group = 
  }

  # Postfix smtp-auth
  unix_listener /var/spool/postfix/private/auth {
    mode = 0666
    user = postfix
    group = postfix
  }

  # Auth process is run as this user.
  user = $default_internal_user
}
```

Any clue how I could try to pinpoint the problem?

**Comment by tonioo** [comment]
Hi,
the demo VM is pretty outdated now and I've not enough time to work on it. I suggest you install install a fresh server using newer versions.
Don't hesitate to contact me in private in you need help/more information.

**Comment by orangejuicy** [comment]
Hello. I have this issue after fresh install on ubuntu 14.04 with modoboa-installer. Modoboa version is 1.4.5. 

```
Apr  2 22:22:17 mail dovecot: imap-login: Disconnected (auth failed, 1 attempts in 2 secs): user=<admin>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, secured, session=<wjxXQIYvMgB/AAAB>
```

What can I do to fix this?
