### ISSUE TITLE
postfixadmin migration script don´t create amavis records

### ISSUE THREAD

**Issue by controlcde** [tonioo/modoboa#681]
I´ve configured modoboa before I fire up the postfixadmin migration script but after a sucessful import the needed records in the amavis database are missing.

**Comment by tonioo** [comment]
Now that I look at the code, amavis records should be created when you run the migration script unless the amavis extension is not enabled.

Are you sure the extension was enabled when you ran the script ?

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-pfxadmin-migrate#1
