### ISSUE TITLE
Relay domains user alias support

### ISSUE THREAD

**Issue by phelset** [tonioo/modoboa#683]
Relay domains should be supported as alias

user@relay-domain.com -> user@other-relay-domain.com
otheruser@relay-domain.com -> otheruser@hosted-domain.com

**Comment by tonioo** [comment]
I think you are looking for relay domain aliases, which are already supported. Look at the relaydomain creation form, you can specify aliases...

Am I right ?

**Comment by phelset** [comment]
Relay domain aliases works perfect.
But, I would like to add alias from one relay domain to another relay domain.
user@relaydomain.com -> user@other-relaydomain.com

If you try to add an alias with @relaydomain.com, the form validation fails with "Domain does not exist".

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-admin-relaydomains#1
