### ISSUE TITLE
Webmail login display problem on smartphones

### ISSUE THREAD

**Issue by emestels** [tonioo/modoboa#690]
Hi,

The login page is really not well displayed - it seems that there is a scaling problem.

I'm not an html pro but it seems this line is missing in the code :
```<meta name="viewport" content="width=device-width" /> ```
 
![screenshot_2015-02-11-13-54-22](https://cloud.githubusercontent.com/assets/8982895/6147315/5b9cf63c-b1f6-11e4-917b-9533db35c8cd.png)

**Comment by tonioo** [comment]
You're right, the viewport is not properly configured.
