### ISSUE TITLE
Impossible to send a mail from webmail with smartphone

### ISSUE THREAD

**Issue by emestels** [tonioo/modoboa#691]
Hi,

There is a problem in the menu visualization on smartphones - impossible to "click" the WRITE/ECRIRE button to compose a new message!
![screenshot_2015-02-10-11-31-30](https://cloud.githubusercontent.com/assets/8982895/6147356/caccc2da-b1f6-11e4-97a6-12d458a72c05.png)

**Comment by emestels** [comment]
Do you need more info on this?

**Comment by tonioo** [comment]
No that's enough, thank you.

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-webmail#6
