### ISSUE TITLE
Selection of multiple message to delete/mark as read/unread

### ISSUE THREAD

**Issue by emestels** [tonioo/modoboa#692]
Hi,

In the inbox, in order to select multiple mail messages to apply an action (delete - mark as read - mark as unread) we need to use keyboard ctrl + click
==> it not possible with a touch screen device!
Simple click/touch of the check box should activate the select
![webmail - mozilla firefox_2015-02-11_14-09-08](https://cloud.githubusercontent.com/assets/8982895/6147483/56842eac-b1f8-11e4-9199-a152f7d25dcc.png)

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-webmail#5
