### ISSUE TITLE
Domain removal fails when manual learning is enabled

### ISSUE THREAD

**Issue by piwats** [tonioo/modoboa#693]
Hi,

I tried to add xx.domain.tld in the domain list as a domain in modoboa-1.2.0. It seems that this is not possible any more.

domain.tld seems to be not problematic.

Is it possible to revert to a previous state, when it was possible to do so?

-Paul

**Comment by tonioo** [comment]
Hi,

could you give more information? I don't reproduce your issue on the demo site.

**Comment by piwats** [comment]
I have a domain.tld in my domains list.

When I try to add a subdomain like the one described, xx.domain.tld, modoboa refuses to create it, stating that the name of the domain is invalid.

If I try to add a domain, which parent domain is not on the list already, then xy.domain2.tld will be created. Here domain2.tld was not in the list of created domains before xy.domain2.tld was created.


That is, when domain.tld is already added to modoboa, it is not possible to add subdomains of this domain.

**Comment by tonioo** [comment]
Could you try on the official demo please ? (http://modoboa.sys4.de)

I've just created a sub domain... What is the role of the connected user?

**Comment by piwats** [comment]
Hmm, it seems that my installation of modoboa has some troubles:

```
2015/02/17 15:34:34 [error] 8740#0: *5876 open() "/var/www/admin/sitestatic/bootstrap-select/dist/js/bootstrap-select.js.map" failed (2: No such file or directory), client: XX.XX.XX.XX, server: server.tld, request: "GET /modoboa/sitestatic/bootstrap-select/dist/js/bootstrap-select.js.map HTTP/1.1", host: "server.tld"
```

If I add a completely new domain, be it "test.com" to my modoboa instance, and later add another subdomain "test.test.com", then it works - with no problems at all.

It seems that domains added by previous modoboa installations, <1.2.0, are affected so it is not possible to add domains in the scheme which leads to this problem.

**Comment by piwats** [comment]
Furthermore, when trying to delete the domain to which it is not possible to add subdomains I get this 500 Internal Server error:

```
AttributeError at /admin/domains/8/delete/
'QuerySet' object has no attribute 'full_address'

Request Method: POST
Request URL: https://server.tld/modoboa/admin/domains/8/delete/
Django Version: 1.6.10
Python Executable: /usr/bin/uwsgi
Python Version: 2.7.9
Python Path: ['.', '', '/usr/lib64/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/usr/lib64/python2.7/site-packages']
Server time: Di, 17 Feb 2015 16:17:13 +0100
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'south',
 'reversion',
 'modoboa',
 'modoboa.core',
 'modoboa.lib',
 'modoboa.extensions.admin',
 'modoboa.extensions.postfix_relay_domains',
 'modoboa.extensions.limits',
 'modoboa.extensions.postfix_autoreply',
 'modoboa.extensions.webmail',
 'modoboa.extensions.stats',
 'modoboa.extensions.sievefilters',
 'modoboa.extensions.radicale',
 'modoboa.extensions.amavis')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'modoboa.lib.middleware.AjaxLoginRedirect',
 'modoboa.lib.middleware.CommonExceptionCatcher',
 'modoboa.lib.middleware.ExtControlMiddleware',
 'modoboa.lib.middleware.RequestCatcherMiddleware')

Traceback:
File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py" in get_response
  112.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/lib64/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  22.                 return view_func(request, *args, **kwargs)
File "/usr/lib64/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  22.                 return view_func(request, *args, **kwargs)
File "/usr/lib64/python2.7/site-packages/modoboa/extensions/admin/views/domain.py" in deldomain
  136.     dom.delete(request.user, keepdir)
File "/usr/lib64/python2.7/site-packages/modoboa/extensions/admin/models/domain.py" in delete
  124.             events.raiseEvent("MailboxAliasDeleted", self.alias_set.all())
File "/usr/lib64/python2.7/site-packages/modoboa/lib/events.py" in raiseEvent
  145.         callback(*args, **kwargs)
File "/usr/lib64/python2.7/site-packages/modoboa/lib/events.py" in wrapped_f
  98.             return f(*args, **kwargs)
File "/usr/lib64/python2.7/site-packages/modoboa/extensions/amavis/general_callbacks.py" in on_mailboxalias_deleted
  109.     if Users.objects.filter(email=alias.full_address).exists():

Exception Type: AttributeError at /admin/domains/8/delete/
Exception Value: 'QuerySet' object has no attribute 'full_address'
Request information:
GET: No GET data

POST: No POST data

FILES: No FILES data
```

**Comment by piwats** [comment]
The role of the connected user is always the same - super admin

**Comment by tonioo** [comment]
Hi,
I've pushed a fix that should allow you to delete the domain. Can you please try it?

**Comment by piwats** [comment]
Hello,
the fix allowed to remove the domain which prior to this couldn't be removed.

If I recreate the removed domain again and try to add a subdomain to it, modoboa fails with the same error, that the domain name is invalid.

**Comment by piwats** [comment]
I just noticed, that I am now able to create a test.domain.tld subdomain, but not a z.domain.tld.

Is it possible that one character subdomains are not allowed for creation in modoboa?

**Comment by tonioo** [comment]
It would be easier with the full backtrace or a screenshot.

**Comment by piwats** [comment]
You get the same error on the official modoboa demo:

1.) create a domain "a.test.com" (it is not important to have a "test.com" domain prior to this)
2.) In the form-box where you enter the name you get a "Enter a valid domain name"-error.

I get following Errors in Chrome developer-tools:

```
form_errors: {name: ["Enter a valid domain name"]}
name: ["Enter a valid domain name"]
0: "Enter a valid domain name"
stepid: 1

```

and 

```
Request URL:https://modoboaserver.tld/modoboa/admin/domains/new/
Request Method:POST
Status Code:400 BAD REQUEST
Response Headers
content-language:en
content-type:application/json
date:Wed, 18 Feb 2015 16:53:04 GMT
server:nginx
status:400 BAD REQUEST
vary:Accept-Language, Cookie
version:HTTP/1.1
x-frame-options:SAMEORIGIN
```

**Comment by piwats** [comment]
Can you split this bug into two, one which affect the amavis extension, and another which affects the subdomain/domain creation?

**Comment by tonioo** [comment]
Sure. I'll create a new issue.
