### ISSUE TITLE
Create new account

### ISSUE THREAD

**Issue by kobra34** [tonioo/modoboa#696]
Hi
How can I open a new account with add-ons compatible with modoboa .
After asking the user to open some questions users would get their own email.
thanks and respect

**Comment by tonioo** [comment]
Are you talking about an API to create accounts into Modoba?

**Comment by kobra34** [comment]
Yes, or pluging

**Comment by hadifarnoud** [comment]
as far as I know, the account creation API is not ready yet.

**Comment by tonioo** [comment]
see #832
