### ISSUE TITLE
Identities import of aliases never sets recipient

### ISSUE THREAD

**Issue by patsoffice** [tonioo/modoboa#698]
If I have a list of aliases to import, the first import will be created, but the internal recipient is never set and the import never continues even if "Continue on error" is checked.

Say my import list is:

alias;981abf1683c8a8c43671669e44a430c6@domain.com;True;dest@domain.com
alias;16438f737fa04f9dab0d176d8cec3c24@domain.com;True;dest@domain.com
alias;5416ecf971ea97a0b1d57d4e774374b7@domain.com;True;dest@domain.com

and dest@domain.com is the username of a Simple User.

The alias 981abf1683c8a8c43671669e44a430c6@domain.com will be created and enabled. But the recipient will never be set. The two following aliases will never be imported.

I have duplicated the issue on 1.2 and 1.2.1.

**Comment by patsoffice** [comment]
I made the change I described in https://github.com/tonioo/modoboa/issues/522 to the DB schema, so that could be messing with the import. I am going to re-kickstart the host and build without that schema change and will report back.

**Comment by tonioo** [comment]
I don't think so. I'm able to reproduce this issue.

**Comment by tonioo** [comment]
Seems to work now :)

**Comment by patsoffice** [comment]
Thanks, installed this weekend. Works great!
