### ISSUE TITLE
Problems with distribution lists after CSV import

### ISSUE THREAD

**Issue by bennidi** [tonioo/modoboa#700]
I tried the csv import for identities and used it to create accounts. Then I decided to replace some of the accounts with distribution lists. I deleted the accounts in the admin interface and used the csv to import them as distribution lists.

The import always created them as aliases instead of distribution list. The same happens when I try to add a distribution list via admin interface. It is now not possible anymore to create distribution lists at all. It seems that the csv import broke the whole thing.

The option to delete accounts was turned off but since I never logged in they were never created and the directory where accounts are stored does not show them.

All of that happened with 1.2.0. I upgraded to 1.2.1 using pip but the problem persists.

**Comment by tonioo** [comment]
Have you tried to manually remove remaining accounts? (since the option was turned off)

**Comment by bennidi** [comment]
Yes, there are no unused/old accounts left. Neither in the database nor on the file system.

**Comment by tonioo** [comment]
Can you provide the CSV file you used ?

**Comment by bennidi** [comment]
No, I can't. I used different files with incorrect formats because I did
not understand the explanations. That's why I added a PR to include
examples :) I know that I had variations where I added a semicolon at the
end which caused the parser to hang.

Now the entire functionality of distribution lists and forwards seems to be
broken.

2015-03-18 13:07 GMT+01:00 Antoine Nguyen <notifications@github.com>:

**Comment by vingeni** [comment]
i think that a distribution list with a single recipient is treated as an alias. If you have more than two recipient, then it is considered as a distribution list.

**Comment by tonioo** [comment]
That's true. @bennidi Have you checked if there are more than one recipient inside the created distribution lists ?

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-admin#23
