### ISSUE TITLE
LDAP Backend: add support for ldap groups 'groupOfNames'

### ISSUE THREAD

**Issue by kokel** [tonioo/modoboa#704]
Hello,

please add support for [groupOfNames](https://tools.ietf.org/html/rfc4519#page-22) ldap groups into the LDAP Backend. A 'groupOfNames' object stores the full User-DN in the attribute 'member'.

Currently there is only support for 'posixGroup' ldap groups.

Thanks in advance!

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-admin#8

**Comment by tonioo** [comment]
@kokel Hi,

it looks like we can't use more than one group type at the same time (or in the same configuration). Do you confirm ?
