### ISSUE TITLE
I installed this, but I can't see any webmail

### ISSUE THREAD

**Issue by buffonomics** [tonioo/modoboa#708]
All I see is the Domain and accounts, Webmail, calendar and the other are not showing up.
Is there some extra step that needs to be done that wasn't included in the docs for enabling these things?

**Comment by tonioo** [comment]
Which version have you installed ?

**Comment by buffonomics** [comment]
1.2.1. the currently stable one.  I see it now though, Had to rerun modoboa-admin.py with --extensions all, though I had some issues with placement of the parameters initially, hence me ignoring the extensions flag.

I wasn't able to see anywhere to enable those extensions after the deploy.
