### ISSUE TITLE
add support for smtpd_sender_login_maps

### ISSUE THREAD

**Issue by kokel** [tonioo/modoboa#709]
Hello,

please enhance modoboa in order that postfix can query modoboa sql database for [smtpd_sender_login_maps](http://www.postfix.org/postconf.5.html#smtpd_sender_login_maps).

This is very security related and will give modoboa admins the possibility to restrict users relaying emails with any "from" address.

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-admin#7
