### ISSUE TITLE
Pip install for 1.2.1 keeps using drupal 1.6

### ISSUE THREAD

**Issue by buffonomics** [tonioo/modoboa#710]
Docs say Modoboa 1.2.1 (current version) needs drupal 1.7+, but the pip install always insists on and downloads drupal 1.6. This leads to inconsistencies in the current installation experience, and sometime outright errors.

My python version is 2.7.6.

**Comment by tonioo** [comment]
Drupal ? :)

The documentation you're watching (with /en/latest/ inside the address) in the one built from the master branch which requires Django 1.7.

If you want to read the documentation of the 1.2.x branch (which requires Django 1.6):
http://modoboa.readthedocs.org/en/1.2.0/

**Comment by buffonomics** [comment]
Sorry I meant django 1.7 :)
It's been a coffeeless morning.

**Comment by buffonomics** [comment]
It might also be best to specify which versions of postfix and dovecot too, because I do not see any
/etc/postfix/sql-aliases.cf or /etc/postfix/sql-mailboxes-self-aliases.cf or any of that.
