### ISSUE TITLE
SQL prepare failed: near "(": Error with generated sql-aliases.cf file

### ISSUE THREAD

**Issue by buffonomics** [tonioo/modoboa#711]
When I try to use webmail I get the error:
Error: command: LOGIN => socket error: EOF

Looking at my logs, I see this continously:
Apr 13 17:42:28 mail postfix/pickup[2261]: ECB5F2166E: uid=0 from=<root>
Apr 13 17:42:28 mail postfix/cleanup[2619]: fatal: dict_sqlite_lookup: /servers/mail/mapfiles/sql-aliases.cf: SQL prepare failed: near "(": syntax error?
Apr 13 17:42:29 mail postfix/pickup[2261]: warning: maildrop/85FD22146D: error writing ECB5F2166E: queue file write error
Apr 13 17:42:29 mail postfix/master[2256]: warning: process /usr/lib/postfix/cleanup pid 2619 exit status 1
Apr 13 17:42:29 mail postfix/master[2256]: warning: /usr/lib/postfix/cleanup: bad command startup -- throttling

I've never been quite able to get this to work. Any tips?

**Comment by buffonomics** [comment]
This is the query given to the query field in that generated file by modoboa-django.py postfix_maps ...
Nothing changed. Spaced out for more legibility.
`
(
	SELECT (mb.address || '@' || dom.name) 
	FROM admin_mailbox mb 
		INNER JOIN admin_domain dom ON mb.domain_id=dom.id 
	WHERE mb.id IN (
		SELECT al_mb.mailbox_id 
		FROM admin_alias_mboxes al_mb 
			INNER JOIN admin_alias al ON al_mb.alias_id=al.id 
			INNER JOIN admin_domain dom ON al.domain_id=dom.id 
		WHERE dom.name='%d' 
			AND dom.enabled=1 
			AND al.address='%u' 
			AND al.enabled=1
		)
)

UNION (
	SELECT (al.address || '@' || dom.name) 
	FROM admin_alias al INNER JOIN admin_domain dom ON al.domain_id=dom.id 
	WHERE al.id IN (
		SELECT al_al.to_alias_id 
		FROM admin_alias_aliases al_al 
			INNER JOIN admin_alias al ON al_al.from_alias_id=al.id 
			INNER JOIN admin_domain dom ON al.domain_id=dom.id 
		WHERE dom.name='%d' AND dom.enabled=1 AND al.address='%u' AND al.enabled=1
	)
) 

UNION (
	SELECT al.extmboxes 
	FROM admin_alias al 
		INNER JOIN admin_domain dom ON al.domain_id=dom.id 
	WHERE dom.name='%d' AND dom.enabled=1 AND al.address='%u' AND al.enabled=1 AND al.extmboxes<>''
)
`

**Comment by buffonomics** [comment]
While we're at it, would it be a terrible thing to just use that VM provided for 1.2.1 as a production mail server?

**Comment by vingeni** [comment]
Hello,

try this request, without the start/end parenthesis :

query = SELECT (mb.address || '@' || dom.name) FROM admin_mailbox mb 
INNER JOIN admin_domain dom ON mb.domain_id=dom.id WHERE mb.id IN 
(SELECT al_mb.mailbox_id FROM admin_alias_mboxes al_mb INNER JOIN 
admin_alias al ON al_mb.alias_id=al.id INNER JOIN admin_domain dom ON 
al.domain_id=dom.id WHERE dom.name='%d' AND dom.enabled=1 AND 
al.address='%u' AND al.enabled=1) UNION SELECT (al.address || '@' || 
dom.name) FROM admin_alias al INNER JOIN admin_domain dom ON 
al.domain_id=dom.id WHERE al.id IN (SELECT al_al.to_alias_id FROM 
admin_alias_aliases al_al INNER JOIN admin_alias al ON 
al_al.from_alias_id=al.id INNER JOIN admin_domain dom ON 
al.domain_id=dom.id WHERE dom.name='%d' AND dom.enabled=1 AND 
al.address='%u' AND al.enabled=1) UNION SELECT al.extmboxes FROM 
admin_alias al INNER JOIN admin_domain dom ON al.domain_id=dom.id WHERE 
dom.name='%d' AND dom.enabled=1 AND al.address='%u' AND al.enabled=1 AND 
al.extmboxes<>'';

--
vincent.

**Comment by tonioo** [comment]
@buffonomics Hi, have you tried the proposed solution ?

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-admin#24

**Comment by bernd-wechner** [comment]
Hmmm, am getting this on webmail too, but see no clue in logs and wondering where "modoboa/modoboa-admin#24" is?
