### ISSUE TITLE
Internal error when I click on domain with domain admin user account

### ISSUE THREAD

**Issue by harobed** [tonioo/modoboa#715]
Hi,

I've this bug :

* I use modoboa v1.2.1
* I'm logged with domain admin user (not super admin user)
* I'm on this page http://modoboa.bearstech.dev/admin/domains/#list/
* I click on domain in the list
* In firebug, I've this error :

```
GET http://modoboa.bearstech.dev/admin/domains/14/edit/ error 500
```

To fix it : 

```
$ git diff
diff --git a/modoboa/lib/formutils.py b/modoboa/lib/formutils.py
index 4b1922b..3097209 100644
--- a/modoboa/lib/formutils.py
+++ b/modoboa/lib/formutils.py
@@ -211,6 +211,9 @@ class TabForms(object):
     template_name = "common/tabforms.html"

     def __init__(self, request, instances=None, classes=None):
+        if instances is not None:
+            self.instances = instances
+
         self.request = request
         to_remove = []
         for fd in self.forms:
@@ -221,7 +224,6 @@ class TabForms(object):
             if request.method == "POST":
                 args.append(request.POST)
             if instances is not None:
-                self.instances = instances
                 if hasattr(self, "check_%s" % fd["id"]):
                     if not getattr(self, "check_%s" % fd["id"])(instances[fd["id"]]):
                         to_remove += [fd]
```

Next after this fix, I've "Update" button in modal window in below screenshot. If I click on update, I've this error :

```
POST http://modoboa.bearstech.dev/admin/domains/108/edit 500
```

![capture d ecran 2015-04-27 a 19 22 02](https://cloud.githubusercontent.com/assets/230143/7353322/e8eb4bc2-ed12-11e4-90ff-cf7d05670b3c.png)

What is the good behaviour ? I should see the same dialog box that super admin ? like in screenshot below ?

![capture d ecran 2015-04-27 a 19 26 28](https://cloud.githubusercontent.com/assets/230143/7353396/73ef57b8-ed13-11e4-95be-ec61c34b5b5d.png)

**Comment by harobed** [comment]
The problem is that my domain admin user (not super admin) haven't "admin.change_domain" permission.

It's here : https://github.com/tonioo/modoboa/blob/1.2.x/modoboa/extensions/admin/forms/domain.py#L274

I think that domain admin user must have "admin.change_domain" permission on its domain, isn't it ?

**Comment by tonioo** [comment]
Hi,
a domain administrator is not supposed to change the properties of the domain he manages unless the amavis extension is enabled. Are you using it ? If you don't, you should not see the "Domains" menu entry at all.

Otherwise, it looks like you find an issue when a domain adminstrator tries to save a domain. I'm looking into it.

**Comment by tonioo** [comment]
Sorry, my previous post was wrong about visibility. A domain administrator IS supposed to list and see the domain(s) he manages.

**Comment by tonioo** [comment]
Here is a quick fix. Could you please test it ?

**Comment by harobed** [comment]
Fixed, thanks

**Comment by w4ugit** [comment]
I have the same problem. how can i solve it?
