### ISSUE TITLE
python manage.py bower install => Unknown command: 'bower'

### ISSUE THREAD

**Issue by harobed** [tonioo/modoboa#716]
I've installed 

```
~/vtenv/bin/pip install -r dev-requirements.txt
```

and I've : 

```
~/vtenv/bin/python manage.py bower install
Unknown command: 'bower'
Type 'manage.py help' for usage.
```

any explanation ?

**Comment by tonioo** [comment]
Is bower installed on your server ? (Not only django-bower)

**Comment by harobed** [comment]
Yes : 

```
$ bower --version
1.4.1
$ python manage.py bower install
Unknown command: 'bower'
Type 'manage.py help' for usage.
```

**Comment by tonioo** [comment]
Did you deploy your modoboa instance using the --devel option ? If you didn't, you need to manually add "djangobower" to the INSTALLED_APPS variable.

**Comment by harobed** [comment]
> Did you deploy your modoboa instance using the --devel option ? If you didn't, you need to manually add "djangobower" to the INSTALLED_APPS variable.

Yes is that.

Sorry it's here in the documentation https://modoboa.readthedocs.org/en/latest/extending/getting_started.html#deploy-an-instance-for-development

What do you think about append FAQ in « Deploy an instance for development » ?
I can append an item FAQ « bower command is missing in manage.py »

**Comment by tonioo** [comment]
That's a good idea.

**Comment by harobed** [comment]
> Did you deploy your modoboa instance using the --devel option ? If you didn't, you need to manually add "djangobower" to the INSTALLED_APPS variable.

--devel option didn't append djangobower in INSTALLED_APPS in settings.py

**Comment by harobed** [comment]
"djangobower" missing in https://github.com/tonioo/modoboa/blob/master/modoboa/core/commands/templates/settings.py.tpl
