### ISSUE TITLE
Remove "Webmail" extension dependency on "Sieve filters" extension

### ISSUE THREAD

**Issue by harobed** [tonioo/modoboa#719]
Currently "extensions/sievefilters/" depend on "extensions/webmail/".

Webmail extension need to be enabled to use "Sieve filters" extension.

Proposal : remove this dependency

**Comment by tonioo** [comment]
I agree. From my point of view, this change should be integrated with versions >= 1.3.0 so the right location for this issue should be https://github.com/modoboa/modoboa-sievefilters.

What do you think ?

**Comment by harobed** [comment]
@themr0c I didn't see this issue in >= 1.3, do you have did a fix ?

**Comment by tonioo** [comment]
@harobed I think you commented the wrong issue, right ?

**Comment by harobed** [comment]
No I didn't see https://github.com/modoboa/modoboa-sievefilters/blob/master/requirements.txt#L1

webmail have been automaticaly installed.

**Comment by harobed** [comment]
I've moved this issue to modoboa-sievefilters repository.
