### ISSUE TITLE
1.3.0: --dburl default:...

### ISSUE THREAD

**Issue by piwats** [tonioo/modoboa#723]
Hello,

I'm trying to automate the redeployment of modoba.

When using the new modoboa-admin.py parameters, especially the new

--dburl default:postgres://USER:PASS@HOST:PORT/DB

and

--dburl amavis:postgres://USER:PASS@HOST:PORT/DB

That should be right, shouldn't it?

When running the modoba-admin.py deploy dir and the parameters above, I get:

"You must define a 'default' database" Error.

What's up?

**Comment by tonioo** [comment]
The --dburl option must appear only once but it accepts multiple arguments :

```--dburl defaut:<...> amavis:<...>```

Am I clear ?

**Comment by piwats** [comment]
Thank you +1:

Could you place a note to the docs, because it was not clear?

**Comment by tonioo** [comment]
I will.
