### ISSUE TITLE
modoboa-admin.py postfix_maps command in 1.3.1 

### ISSUE THREAD

**Issue by wsl** [tonioo/modoboa#725]
Hi,

In my experience the right command for generating postfix_maps in 1.3.1 is:

   modoboa-admin.py postfix_maps --dbtype mysql maps --extensions modoboa-admin modoboa-postfix-autoreply modoboa-admin-relaydomains

Instead of

   modoboa-admin.py postfix_maps --dbtype <mysql|postgres|sqlite> --extensions all <directory>
as mentioned in the docs.

If I put the directory as last argument I get:
   modoboa-admin.py: error: too few arguments

If I leave out the extensions parameter the command succeeds but does not generate files.

So either the docs should be changed (http://modoboa.readthedocs.org/en/latest/integration/imap_and_smtp.html#postfix) or the command should be interpreted otherwise.

Regards, Wessel

**Comment by tonioo** [comment]
Hi,
have you tried like this :
```
$ modoboa-admin.py postfix_maps --extensions all --dbtype mysql maps
```
?
