### ISSUE TITLE
Server auto connect to 94.23.45.181

### ISSUE THREAD

**Issue by mvb9** [tonioo/modoboa#732]
When I finished install Modoboa, I detect sever still connect to 94.23.45.181. I block connection , service not running. What's this problem ?

**Comment by tonioo** [comment]
Modoboa provides a simple service to check if new versions are available. To check it, a public API is available on the IP address you mention.

**Comment by vingeni** [comment]
Also, I guess this feature can be disabled on the admin account :
-> Modoboa -> Parameters -> General -> Check new versions -> no
