### ISSUE TITLE
No alias recipient with address extension possible

### ISSUE THREAD

**Issue by controlcde** [tonioo/modoboa#745]
It is not possible to add to an alias a recipient with address extension like foo+bar@foo.bar. The error message says "Local recipient foo+bar@foo.bar not found".

**Comment by tonioo** [comment]
What version of Modoboa are you using ?

**Comment by controlcde** [comment]
1.2.0

**Comment by tonioo** [comment]
Ok, this problem has already been fixed. You can :
* Use the 1.2.x branch
* Upgrade to 1.3.3

The first option is quicker to setup.

**Comment by controlcde** [comment]
Well, how could I upgrade to 1.2.x branch if I installed modoboa via pip?

**Comment by tonioo** [comment]
I think I'll release a minor version (1.2.2), it will be easier.

**Comment by controlcde** [comment]
:) thanks @tonioo

**Comment by tonioo** [comment]
The release is available:

pip install modoboa==1.2.2
