### ISSUE TITLE
Upgrade fail 

### ISSUE THREAD

**Issue by rmalenko** [tonioo/modoboa#748]
Hello,

Gould you help me, please?
Currently is installed Modoboa 1.2.1
I have ran pip install modoboa==1.3.3 and then I run

`modoboa-admin.py deploy /var/www/mail --collectstatic --domain mail.domain.com --lang en --timezone Europe/Kiev --extensions all --dburl default:mysql://mail:pass@127.0.0.1:3306/mail` 

and I got this message

`Error: pip is required to install extensions`

Tell me what extensions should I install, please?

**Comment by tonioo** [comment]
You need to install pip. For example on a Debian system:
```$ apt-get install python-pip```

**Comment by rmalenko** [comment]
Thank you. I have already installed python-pip (Ubuntu 14 LTS) and even reinstalled.

**Comment by rmalenko** [comment]
The issue still remains. Could you help me, please?

**Comment by tonioo** [comment]
Sorry, I thought it was OK.

Try to remove the --extensions all option. Then, manually install the extension(s) you want to use. For example:
```
$ pip install modoboa-admin
```
