### ISSUE TITLE
Installation on Heroku?

### ISSUE THREAD

**Issue by OKNoah** [tonioo/modoboa#751]
I haven't seen Heroku mentioned in the docs or in the issues. Would running on Heroku work, and would it require any special build packs?

**Comment by tonioo** [comment]
Modoboa would certainly run on Heroku but what about postfix/dovecot and co. ?

**Comment by OKNoah** [comment]
@tonioo Yeah, I think that's where a build pack would come in.

**Comment by tonioo** [comment]
That would be a nice stuff to have but I have no time to work on this...
