### ISSUE TITLE
Update 1.2.1 -> 1.3.3 issue: Aliases are not shown anymore

### ISSUE THREAD

**Issue by phaf** [tonioo/modoboa#752]
Hi all,

after upgrading from 1.2.1 to 1.3.3 everything works fine except all aliases and distribution lists which already existed before upgrade are not listed anymore and can not be found via search. 
Newly created aliases are listed and working as expected. 

I am using PostgreSQL and checked the SQL queries created by modoboa, this query seems to be executed to get the list of aliases

```
SELECT "admin_alias"."id", "admin_alias"."dates_id", "admin_alias"."address", "admin_alias"."domain_id", "admin_alias"."extmboxes", "admin_alias"."enabled", "admin_objectdates"."id", "admin_objectdates"."creation", "admin_objectdates"."last_modification", "admin_domain"."id", "admin_domain"."dates_id", "admin_domain"."name", "admin_domain"."quota", "admin_domain"."enabled", "admin_domain"."type", T4."id", T4."creation", T4."last_modification"
 FROM "admin_alias" 
INNER JOIN "admin_objectdates" ON ( "admin_alias"."dates_id" = "admin_objectdates"."id" )
INNER JOIN "admin_domain" ON ( "admin_alias"."domain_id" = "admin_domain"."id" ) 
INNER JOIN "admin_objectdates" T4 ON ( "admin_domain"."dates_id" = T4."id" ) 
WHERE "admin_alias"."id" IN (SELECT U0."object_id" FROM "core_objectaccess" U0 
WHERE (U0."user_id" = 1 AND U0."content_type_id" = 42)) ORDER BY "admin_domain"."name" ASC, "admin_alias"."address" ASC
```
It looks like all old aliases are not present in table core_objectaccess. Is it safe to add the missing entries to core_objectaccess? Should this table populated automatically during the upgrade process?

Thanks for watching on this issue! If there is anything I can do to help, please let me know.

**Comment by tonioo** [comment]
Hi, the problem comes from a migration that is not applied.

To fix this, try to run the following python code :
```python
import django
from django.contrib.contenttypes.models import ContentType

django.setup()

for ct in ContentType.objects.filter(app_label="modoboa_admin"):
    try:
        old_ct = ContentType.objects.get(app_label="admin", model=ct.model)
    except ContentType.DoesNotExist:
        continue
    old_ct.app_label = "modoboa_admin"
    ct.delete()
    old_ct.save()
```
If you paste it into a file, use the following command to execute it:
```
$ PYTHONPATH=<path to modoboa instance> DJANGO_SETTINGS_MODULE=myinstance.settings python my_file.py
```

**Comment by phaf** [comment]
Hi tonioo,

thanks for providing your fix. I tried it, but the aliases are still missing in table core_objectaccess

**Comment by tonioo** [comment]
Which content type corresponds to id 42 ?

**Comment by phaf** [comment]
Hi tonioo,

very good hint: After the installation I was sure that id 42 was alias - but I looks like the the entry has gone after I deleted an alias that was created after installing 1.3.3. There is another entry for alias in django_contentype

    14 | alias              | modoboa_admin              | alias


It also now impossible to create new aliases because the insert statements tries to reference id 42 which is gone, so I am wondering why this id is still used

**Comment by tonioo** [comment]
Have you tried to restart apache/uwsgi/gunicorn/whatever ?

**Comment by phaf** [comment]
After restarting I was able to create a new alias and your patch has added the missing entries in core_objectaccess - therefore everything is fine more me right now. Do I have made a mistake during the upgrade process? I executed setup.py migrate before I used 1.3.3 the first time.

**Comment by tonioo** [comment]
No, this is an issue with the migration procedure. I don't know why  but Django fakes all migrations of the core application, whereas it should just fake the first one.

**Comment by piwats** [comment]
I came to notice the absence of displaying the aliases after the upgrade to 1.3, too.

Any news on this?

**Comment by tonioo** [comment]
Have you tried to run the code upper ?

**Comment by piwats** [comment]
Yes, that did the trick, thank you.
