### ISSUE TITLE
error 500 on importing a csv file with accounts & aliases

### ISSUE THREAD

**Issue by wessel-techtribe-nl** [tonioo/modoboa#754]
I'm importing a csv file with 70 acounts & about 170 aliases/dists/forwards in 6 domains. At some point in aliases/dists part the import call gives a 500 error. If I split the file in parts the same records succeed sometimes but then records later on fail. 

Stacktrace:
Request Method: POST
Request URL: https://10.111.112.78/admin/identities/import/

Django Version: 1.7.8
Python Version: 2.7.6
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'reversion',
 'modoboa',
 'modoboa.core',
 'modoboa.lib',
 'modoboa_admin',
 'modoboa_radicale',
 'modoboa_postfix_autoreply',
 'modoboa_webmail',
 'modoboa_stats',
 'modoboa_sievefilters',
 'modoboa_amavis',
 'modoboa_admin_relaydomains',
 'modoboa_admin_limits')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'modoboa.lib.middleware.AjaxLoginRedirect',
 'modoboa.lib.middleware.CommonExceptionCatcher',
 'modoboa.lib.middleware.RequestCatcherMiddleware')

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/modoboa_admin/views/import_.py" in import_identities
  153.         return importdata(request, ImportIdentitiesForm)
File "/usr/local/lib/python2.7/dist-packages/reversion/revisions.py" in do_revision_context
  297.                 return func(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/modoboa_admin/views/import_.py" in importdata
  125.                         fct(request.user, row, form.cleaned_data)
File "/usr/local/lib/python2.7/dist-packages/modoboa_admin/views/import_.py" in import_alias
  78.     _import_alias(user, row, expected_elements=4)
File "/usr/local/lib/python2.7/dist-packages/modoboa_admin/views/import_.py" in _import_alias
  74.     alias.from_csv(user, row, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/modoboa_admin/models/alias.py" in from_csv
  223.         self.post_create(user)
File "/usr/local/lib/python2.7/dist-packages/modoboa_admin/models/alias.py" in post_create
  99.         super(Alias, self).post_create(creator)
File "/usr/local/lib/python2.7/dist-packages/modoboa_admin/models/base.py" in post_create
  66.         events.raiseEvent("%sCreated" % self.objectname, creator, self)
File "/usr/local/lib/python2.7/dist-packages/modoboa/lib/events.py" in raiseEvent
  90.         callback(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/modoboa_amavis/general_callbacks.py" in on_mailboxalias_created
  97.             policy_name=alias.mboxes.all()[0].full_address
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in __getitem__
  177.         return list(qs)[0]

Exception Type: IndexError at /admin/identities/import/
Exception Value: list index out of range

I could fix it with the following diff:

diff /usr/local/lib/python2.7/dist-packages/modoboa_amavis/general_callbacks.py /tmp/general_callbacks.py
101,102d100
<     except IndexError:
<         return

in the method on_mailboxalias_created:

     @events.observe("MailboxAliasCreated")
     def on_mailboxalias_created(user, alias):
       """Create amavis record for the new alias.

      FIXME: how to deal with distibution lists ?
      """
      if not manual_learning_enabled(user) or alias.type != "alias":
          return
      try:
          policy = Policy.objects.get(
              policy_name=alias.mboxes.all()[0].full_address
          )
        except Policy.DoesNotExist:
          return
        except IndexError:
          return 
        else:
          email = alias.full_address
          Users.objects.create(
              email=email, policy=policy, fullname=email, priority=7
          )

But I'm not sure if my fix messes up the amavis stuff

I can provide the csv but I will have to anomize it then in someway

**Comment by tonioo** [comment]
Hi,
you fix is incorrect since you're creating a new policy. When a mailbox alias is created, Modoboa creates amavis records in order that only one policy exists for all addresses, the mailbox's one.

Have you been able to identify the alias which fails. What kind of alias is it ?

**Comment by wessel-techtribe-nl** [comment]
I have an obfuscated csv file (all names replaced with other names and domains replace with domain1..9) (see below)

If I import this file records till line 120 succeed. barabara@domain4.com on line 121 is the first one not created it seems.

But if I then import again with only this record in the file it succeeds.


account;gilberte@domain1.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;gilberte;True;SimpleUsers;gilberte@domain1.com;0
account;camila@domain1.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;camila;True;SimpleUsers;camila@domain1.com;0
account;merissa@domain4.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;merissa;True;SimpleUsers;merissa@domain4.com;0
account;karry@domain1.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;karry;True;SimpleUsers;karry@domain1.com;0
account;dorethea@domain8.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;dorethea;True;SimpleUsers;dorethea@domain8.com;0
account;gilma@domain5.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;gilma;True;SimpleUsers;gilma@domain5.com;0
account;cayla@domain1.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;cayla;True;SimpleUsers;cayla@domain1.com;0
account;amira@domain1.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;amira;True;SimpleUsers;amira@domain1.com;0
account;annelle@domain4.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;annelle;True;SimpleUsers;annelle@domain4.com;0
account;divina@domain4.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;divina;True;SimpleUsers;divina@domain4.com;0
account;jong@domain8.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;jong;True;SimpleUsers;jong@domain8.com;0
account;cyrstal@domain1.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;cyrstal;True;SimpleUsers;cyrstal@domain1.com;0
account;lauran@domain1.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;lauran;True;SimpleUsers;lauran@domain1.com;0
account;lorrine@domain1.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;lorrine;True;SimpleUsers;lorrine@domain1.com;0
account;margy@domain5.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;margy;True;SimpleUsers;margy@domain5.com;0
account;dakota@domain5.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;dakota;True;SimpleUsers;dakota@domain5.com;0
account;russell@domain4.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;russell;True;SimpleUsers;russell@domain4.com;0
account;chassidy@domain1.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;chassidy;True;SimpleUsers;chassidy@domain1.com;0
account;marketta@domain4.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;marketta;True;SimpleUsers;marketta@domain4.com;0
account;isadora@domain3.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;isadora;True;SimpleUsers;isadora@domain3.com;0
account;carlena@domain1.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;carlena;True;SimpleUsers;carlena@domain1.com;0
account;keira@domain3.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;keira;True;SimpleUsers;keira@domain3.com;0
account;keira@domain7.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;keira;True;SimpleUsers;keira@domain7.com;0
account;oscar@domain4.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;oscar;True;SimpleUsers;oscar@domain4.com;0
account;lavone@domain1.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;lavone;True;SimpleUsers;lavone@domain1.com;0
account;maurita@domain4.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;maurita;True;SimpleUsers;maurita@domain4.com;0
account;jessia@domain1.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;jessia;True;SimpleUsers;jessia@domain1.com;0
account;mistie@domain3.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;mistie;True;SimpleUsers;mistie@domain3.com;0
account;deloras@domain3.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;deloras;True;SimpleUsers;deloras@domain3.com;0
account;corrin@domain3.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;corrin;True;SimpleUsers;corrin@domain3.com;0
account;fermina@domain3.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;fermina;True;SimpleUsers;fermina@domain3.com;0
account;kallie@domain4.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;kallie;True;SimpleUsers;kallie@domain4.com;0
account;deetta@domain1.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;deetta;True;SimpleUsers;deetta@domain1.com;0
account;lashandra@domain7.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;lashandra;True;SimpleUsers;lashandra@domain7.com;0
account;krishna@domain1.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;krishna;True;SimpleUsers;krishna@domain1.com;0
account;peter@domain8.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;peter;True;SimpleUsers;peter@domain8.com;0
account;lourie@domain2.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;lourie;True;SimpleUsers;lourie@domain2.com;0
account;madalene@domain1.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;madalene;True;SimpleUsers;madalene@domain1.com;0
account;cassey@domain6.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;cassey;True;SimpleUsers;cassey@domain6.com;0
account;cassey@domain1.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;cassey;True;SimpleUsers;cassey@domain1.com;0
account;keira@domain6.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;keira;True;SimpleUsers;keira@domain6.com;0
account;alaine@domain5.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;alaine;True;SimpleUsers;alaine@domain5.com;0
account;georgianne@domain3.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;georgianne;True;SimpleUsers;georgianne@domain3.com;0
account;malena@domain2.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;malena;True;SimpleUsers;malena@domain2.com;0
account;lester@domain3.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;lester;True;SimpleUsers;lester@domain3.com;0
account;pamila@domain1.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;pamila;True;SimpleUsers;pamila@domain1.com;0
account;jaquelyn@domain8.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;jaquelyn;True;SimpleUsers;jaquelyn@domain8.com;0
account;etsuko@domain2.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;etsuko;True;SimpleUsers;etsuko@domain2.com;0
account;elizabet@domain7.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;elizabet;True;SimpleUsers;elizabet@domain7.com;0
account;britteny@domain5.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;britteny;True;SimpleUsers;britteny@domain5.com;0
account;lamonica@domain5.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;lamonica;True;SimpleUsers;lamonica@domain5.com;0
account;micha@domain4.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;micha;True;SimpleUsers;micha@domain4.com;0
account;marketta@domain2.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;marketta;True;SimpleUsers;marketta@domain2.com;0
account;eura@domain8.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;eura;True;SimpleUsers;eura@domain8.com;0
account;jinny@domain8.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;jinny;True;SimpleUsers;jinny@domain8.com;0
account;rolande@domain1.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;rolande;True;SimpleUsers;rolande@domain1.com;0
account;lenita@domain1.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;lenita;True;SimpleUsers;lenita@domain1.com;0
account;shantae@domain6.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;shantae;True;SimpleUsers;shantae@domain6.com;0
account;audrie@domain6.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;audrie;True;SimpleUsers;audrie@domain6.com;0
account;ellis@domain3.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;ellis;True;SimpleUsers;ellis@domain3.com;0
account;september@domain1.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;september;True;SimpleUsers;september@domain1.com;0
account;regine@domain5.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;regine;True;SimpleUsers;regine@domain5.com;0
account;eladia@domain1.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;eladia;True;SimpleUsers;eladia@domain1.com;0
account;enda@domain5.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;enda;True;SimpleUsers;enda@domain5.com;0
account;lacresha@domain3.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;lacresha;True;SimpleUsers;lacresha@domain3.com;0
account;ashlea@domain6.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;ashlea;True;SimpleUsers;ashlea@domain6.com;0
account;lewis@domain5.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;lewis;True;SimpleUsers;lewis@domain5.com;0
account;charlsie@domain5.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;charlsie;True;SimpleUsers;charlsie@domain5.com;0
account;lashay@domain5.com;!TKVKthisisadummypasswordnotuseddH4uChxgN;;lashay;True;SimpleUsers;lashay@domain5.com;0
alias;karry@domain3.com;True;karry@domain1.com
alias;dakota@domain4.com;True;dakota@domain5.com
alias;agueda@domain4.com;True;russell@domain4.com
alias;marcelene@domain4.com;True;russell@domain4.com
forward;lorilee@domain4.com;True;lorilee@admin.techtribe.nl
alias;christia@domain4.com;True;chassidy@domain1.com
alias;marshall@domain4.com;True;marketta@domain4.com
alias;maryln@domain4.com;True;marketta@domain4.com
alias;isadora@domain4.com;True;isadora@domain3.com
alias;isadora@domain1.com;True;isadora@domain3.com
alias;keira@domain4.com;True;keira@domain3.com
alias;rosenda@domain7.com;True;keira@domain7.com
alias;maxima@domain4.com;True;maurita@domain4.com
alias;deloras@domain4.com;True;deloras@domain3.com
alias;deloras@domain5.com;True;deloras@domain3.com
alias;deloras@domain1.com;True;deloras@domain3.com
alias;deloras@domain7.com;True;deloras@domain3.com
alias;corrin@domain4.com;True;corrin@domain3.com
alias;corrin@domain5.com;True;corrin@domain3.com
alias;corrin@domain1.com;True;corrin@domain3.com
alias;fermina@domain4.com;True;fermina@domain3.com
alias;fidelia@domain4.com;True;fermina@domain3.com
alias;evita@domain4.com;True;fermina@domain3.com
alias;faviola@domain4.com;True;fermina@domain3.com
alias;fermina@domain5.com;True;fermina@domain3.com
alias;faviola@domain3.com;True;fermina@domain3.com
alias;faviola@domain1.com;True;fermina@domain3.com
alias;fermina@domain1.com;True;fermina@domain3.com
alias;fermina@domain7.com;True;fermina@domain3.com
alias;faviola@domain7.com;True;fermina@domain3.com
alias;printmaster@domain4.com;True;russell@domain4.com
alias;postmaster@domain4.com;True;russell@domain4.com
alias;denyse@domain4.com;True;russell@domain4.com
alias;denyse@domain3.com;True;russell@domain4.com
alias;postmaster@domain3.com;True;russell@domain4.com
alias;denyse@domain1.com;True;russell@domain4.com
alias;postmaster@domain1.com;True;russell@domain4.com
alias;denyse@domain5.com;True;russell@domain4.com
alias;postmaster@domain5.com;True;russell@domain4.com
alias;postmaster@domain7.com;True;russell@domain4.com
alias;denyse@domain7.com;True;russell@domain4.com
alias;denyse@domain8.com;True;russell@domain4.com
alias;postmaster@domain8.com;True;russell@domain4.com
alias;denyse@domain2.com;True;russell@domain4.com
alias;postmaster@domain2.com;True;russell@domain4.com
alias;postmaster@domain6.com;True;russell@domain4.com
alias;denyse@domain6.com;True;russell@domain4.com
dlist;sharika@domain4.com;True;deloras@domain4.com;keira@domain3.com;micha@domain4.com;dakota@domain5.com
dlist;dion@domain4.com;True;fermina@domain4.com;keira@domain3.com
dlist;all@domain4.com;True;russell@domain4.com;divina@domain4.com;annelle@domain4.com;oscar@domain4.com;merissa@domain4.com;marketta@domain4.com;maurita@domain4.com;micha@domain4.com
alias;olevia@domain4.com;True;all@domain4.com
dlist;barabara@domain4.com;True;russell@domain4.com;keira@domain3.com;lauran@domain1.com;marketta@domain4.com;neely@domain9.com
alias;barabara@domain3.com;True;barabara@domain4.com
alias;ai@domain4.com;True;russell@domain4.com
alias;abuse@domain4.com;True;russell@domain4.com
alias;codi@domain4.com;True;russell@domain4.com
dlist;ellena@domain4.com;True;keira@domain3.com;marketta@domain4.com
alias;lashawna@domain4.com;True;keira@domain3.com
dlist;all@domain5.com;True;dakota@domain5.com;corrin@domain5.com;gilma@domain5.com;margy@domain5.com;alaine@domain5.com;lamonica@domain5.com;britteny@domain5.com;regine@domain5.com;enda@domain5.com;lewis@domain5.com;lashay@domain5.com
alias;rheba@domain4.com;True;all@domain5.com
dlist;dion@domain5.com;True;corrin@domain5.com;dakota@domain5.com;deloras@domain5.com;fermina@domain5.com
dlist;caroll@domain5.com;True;dakota@domain5.com;corrin@domain5.com
dlist;carylon@domain4.com;True;russell@domain4.com;dakota@domain5.com
alias;carylon@domain5.com;True;carylon@domain4.com
alias;carylon@domain2.com;True;carylon@domain4.com
dlist;rima@domain4.com;True;cindie@domain9.com;calista@domain9.com;mahalia@domain9.com;bula@domain9.com;neely@domain9.com;myesha@domain9.com;robena@domain9.com;concha@domain9.com;julietta@domain9.com;karole@domain9.com;eulah@domain9.com;lesha@domain9.com;ozell@domain9.com
alias;naida@domain4.com;True;rima@domain4.com
dlist;rosenda@domain5.com;True;lashawna@domain4.com;dakota@domain5.com;micha@domain4.com
alias;sharika@domain3.com;True;keira@domain3.com
dlist;sharika@domain5.com;True;keira@domain3.com;dakota@domain5.com;micha@domain4.com
alias;rosenda@domain3.com;True;keira@domain3.com
dlist;sharika@domain1.com;True;keira@domain3.com;jessia@domain1.com;jama@gmail.com
dlist;rosenda@domain1.com;True;keira@domain3.com;jessia@domain1.com
dlist;colby@domain3.com;True;corrin@domain3.com;gema@deduction.nl;fermina@domain3.com;keira@domain3.com
dlist;collene@domain4.com;True;karry@domain1.com;gema@deduction.nl;keira@domain3.com
alias;colby@domain1.com;True;collene@domain4.com
dlist;burma@domain4.com;True;russell@domain4.com;marketta@domain4.com;maurita@domain4.com;oscar@domain4.com;mistie@domain3.com
dlist;dion@domain1.com;True;karry@domain1.com;jessia@domain1.com;rolande@domain1.com;lorrine@domain1.com
dlist;colby@domain4.com;True;gema@deduction.nl;keira@domain3.com
alias;colby@domain5.com;True;colby@domain4.com
alias;colby@domain8.com;True;colby@domain4.com
dlist;colby@domain7.com;True;fermina@domain4.com;gema@deduction.nl;keira@domain3.com
alias;russell@domain5.com;True;russell@domain4.com
alias;russell@domain3.com;True;russell@domain4.com
alias;samuel@domain4.com;True;russell@domain4.com
alias;russell@domain1.com;True;russell@domain4.com
alias;jeremy@domain4.com;True;russell@domain4.com
alias;blake@domain4.com;True;russell@domain4.com
dlist;dia@domain7.com;True;lashandra@domain7.com;fermina@domain7.com
alias;dion@domain7.com;True;dia@domain7.com
alias;ellena@domain7.com;True;dia@domain7.com
alias;marcell@domain7.com;True;dia@domain7.com
alias;dorethea@domain1.com;True;dorethea@domain8.com
alias;peter@domain1.com;True;peter@domain8.com
alias;natalya@domain1.com;True;karry@domain1.com
alias;jong@domain1.com;True;jong@domain8.com
alias;mistie@domain2.com;True;mistie@domain3.com
dlist;dion@domain2.com;True;mistie@domain2.com;malena@domain2.com;lourie@domain2.com;1td-makerlab@in.frontapp.com
alias;deetta@domain8.com;True;deetta@domain1.com
dlist;rossie@domain2.com;True;mistie@domain2.com;lourie@domain2.com
alias;rosette@domain2.com;True;rossie@domain2.com
dlist;buena@domain2.com;True;mistie@domain2.com;lourie@domain2.com
alias;fermina@domain6.com;True;fermina@domain3.com
alias;faviola@domain6.com;True;fermina@domain3.com
dlist;denny@domain2.com;True;mistie@domain2.com;malena@domain2.com;lourie@domain2.com
dlist;rosenda@domain8.com;True;keira@domain3.com;dorethea@domain8.com;jinny@domain8.com
dlist;sharika@domain8.com;True;keira@domain3.com;dorethea@domain8.com
alias;sharika@domain7.com;True;keira@domain3.com
alias;saran@domain8.com;True;dorethea@domain8.com
alias;dion@domain8.com;True;dorethea@domain8.com
alias;alona@domain3.com;True;russell@domain4.com
alias;melodi@domain3.com;True;russell@domain4.com
alias;bari@domain3.com;True;russell@domain4.com
alias;seema@domain3.com;True;russell@domain4.com
dlist;colby@domain6.com;True;cassey@domain6.com;fermina@domain6.com;gema@deduction.nl
alias;fermina@doublew.com;True;fermina@domain3.com
dlist;colby@doublew.com;True;gema@deduction.nl;fermina@domain3.com;keira@domain3.com
dlist;larraine@domain2.com;True;mistie@domain2.com;@cmVuZWVAbWFrZXJsYWIubmwg;malena@domain2.com
alias;caroll@domain4.com;True;russell@domain4.com
alias;claretta@domain4.com;True;russell@domain4.com
alias;ria@domain4.com;True;russell@domain4.com
alias;daine@domain4.com;True;russell@domain4.com
alias;jeffie@domain4.com;True;russell@domain4.com
forward;avril@domain4.com;True;avril@ci-zk.techtribe.nl
alias;beula@domain3.com;True;russell@domain4.com
alias;beula@domain2.com;True;russell@domain4.com
alias;malena@domain3.com;True;malena@domain2.com
dlist;agnus@domain4.com;True;oscar@domain4.com;russell@domain4.com;deloras@domain4.com;merissa@domain4.com;micha@domain4.com;divina@domain4.com;annelle@domain4.com
dlist;rosena@domain5.com;True;corrin@domain5.com;alaine@domain5.com;katherina@gmail.com;dakota@domain5.com
alias;loura@domain3.com;True;lester@domain3.com
alias;karry@domain4.com;True;karry@domain1.com
dlist;bettyann@domain2.com;True;mistie@domain3.com;lourie@domain2.com;malena@domain2.com
dlist;ellena@domain6.com;True;cassey@domain6.com;audrie@domain6.com;ashlea@domain6.com
dlist;sarai@domain2.com;True;lourie@domain2.com;1vb-makerlab@in.frontapp.com;malena@domain2.com;mistie@domain2.com
dlist;4gconnect@domain2.com;True;mistie@domain3.com;lourie@domain2.com;malena@domain2.com
alias;neida@domain3.com;True;russell@domain4.com
alias;neida@domain4.com;True;neida@domain3.com
alias;neida@domain2.com;True;neida@domain3.com
alias;neida@domain1.com;True;neida@domain3.com
alias;neida@domain8.com;True;neida@domain3.com
alias;neida@domain5.com;True;neida@domain3.com
dlist;leida@domain2.com;True;mistie@domain2.com;lourie@domain2.com;malena@domain2.com
dlist;sharika@domain6.com;True;keira@domain6.com;cassey@domain6.com;audrie@domain6.com
alias;rosenda@domain6.com;True;sharika@domain6.com
dlist;colby@domain2.com;True;keira@domain3.com;malena@domain2.com
alias;rosenda@domain2.com;True;keira@domain3.com
alias;sharika@domain2.com;True;keira@domain3.com
dlist;ghislaine@domain2.com;True;mistie@domain2.com;lourie@domain2.com;malena@domain2.com
dlist;curtis@domain5.com;True;margy@domain5.com;gilma@domain5.com
alias;russell@domain8.com;True;russell@domain4.com
alias;russell@domain2.com;True;russell@domain4.com
alias;salley@domain3.com;True;russell@domain4.com
alias;audria@domain3.com;True;denyse@domain4.com
dlist;dion@domain6.com;True;cassey@domain6.com;audrie@domain6.com
forward;elli@domain3.com;True;elsy@gmail.com
alias;necole@domain2.com;True;mistie@domain2.com
alias;myrta@domain2.com;True;mistie@domain2.com
forward;katerine@domain5.com;True;rheba@strictworks.nl
alias;newsletter@domain3.com;True;lacresha@domain3.com
alias;jeneva@domain2.com;True;lourie@domain2.com
alias;keira@domain5.com;True;keira@domain3.com
alias;keira@domain1.com;True;keira@domain3.com
alias;doreatha@domain1.com;True;dorethea@domain1.com
alias;elli@domain4.com;True;elli@domain3.com
alias;elli@domain5.com;True;elli@domain3.com
dlist;rosenda@domain4.com;True;lashawna@domain4.com;deloras@domain4.com;dakota@domain5.com;micha@domain4.com
dlist;nicholle@domain4.com;True;russell@domain4.com;annelle@domain4.com;divina@domain4.com;oscar@domain4.com;merissa@domain4.com;marketta@domain4.com;maurita@domain4.com;all@domain5.com
dlist;luba@domain4.com;True;karry@domain1.com;lorrine@domain1.com;lavone@domain1.com;carlena@domain1.com;jessia@domain1.com;camila@domain1.com;lauran@domain1.com;chassidy@domain1.com;cyrstal@domain1.com;gilberte@domain1.com;amira@domain1.com;natalya@domain1.com;cayla@domain1.com;krishna@domain1.com;madalene@domain1.com;pamila@domain1.com;cassey@domain1.com;rolande@domain1.com;lenita@domain1.com;september@domain1.com;eladia@domain1.com
alias;all@domain1.com;True;luba@domain4.com
alias;alle@domain1.com;True;luba@domain4.com
dlist;all@domain3.com;True;lester@domain3.com;keira@domain3.com;corrin@domain3.com;elli@domain3.com;deloras@domain3.com;karry@domain1.com
alias;jesusita@domain4.com;True;all@domain3.com
dlist;nancee@domain4.com;True;jeremy@domain4.com;corrin@domain3.com
dlist;all@domain8.com;True;peter@domain8.com;dorethea@domain8.com;deetta@domain8.com;jong@domain8.com;jaquelyn@domain8.com;eura@domain8.com;jinny@domain8.com
alias;elli@domain2.com;True;elli@domain3.com
dlist;all@domain2.com;True;mistie@domain2.com;malena@domain2.com;elli@domain2.com;lourie@domain2.com;marketta@domain2.com;georgianne@domain3.com
dlist;dion@domain3.com;True;elli@domain3.com;corrin@domain3.com;karry@domain1.com;keira@domain3.com
dlist;ph29@domain4.com;True;all@domain4.com;all@domain3.com;all@domain1.com;all@domain5.com;all@domain9.com;all@domain8.com;all@domain2.com;all@thisisnoun.com
alias;ph29@domain3.com;True;ph29@domain4.com
alias;ph29@domain5.com;True;ph29@domain4.com

**Comment by tonioo** [comment]
Actually, it is a known issue. The migration fails on the first alias on alias it founds. 

```alias olevia@domain4.com True all@domain4.com```

The original issue is here: https://github.com/modoboa/modoboa-amavis/issues/14
