### ISSUE TITLE
Can´t add new accounts

### ISSUE THREAD

**Issue by controlcde** [tonioo/modoboa#757]
Hi,

just upgraded to 1.3.4 but now I can´t add new email accounts. If I filled all fields I click "Submit" nothing happens - the Apache log file shows:

    POST /admin/accounts/new/ HTTP/1.1" 500 1435 "https:/DOMAIN/admin/identities/"

And: If I choose "normal user" I could not add an email address on the second screen. "Submit" also not works.

**Comment by tonioo** [comment]
I can't reproduce your issue on the official demo (which is also running 1.3.4).

Coud you give more detail please ?

**Comment by controlcde** [comment]
Hmmm, I don´t know how I could get more details?! What could I do to get more details?! I´ve enabled both debug options in setting.py but I didn´t get more details like

    POST /admin/accounts/new/ HTTP/1.1" 500 1435 "https:/DOMAIN/admin/identities/"

For the second problem I found out that is a problem of different browsers. But for the first problem I´ve tried with different browsers and different OS - the problem are still there: I couldn´t click on "SUBMIT" or better: Nothing happens if I click on "SUBMIT".

**Comment by tonioo** [comment]
When DEBUG is set to True, open a javascript console (like firebug) to follow AJAX requests, you'll see the complete stacktrace.

About information, can you give me the list of the modoboa packages you use ? (Modoboa > Information)

**Comment by controlcde** [comment]
Right, problem found and problem solved: I´ve enabled pdf_credentials but the path for export the pdf didn´t exist. After creating the path and give them the rights from the webserver I could add a new account. Thanks for the help Antoine!
