### ISSUE TITLE
replacement for mailzu ?

### ISSUE THREAD

**Issue by peterbeck** [tonioo/modoboa#761]
Hi there,

will it be possible to use just the quarantine part of modoboa ?
The mailzu project seems to be dead so I am wondering if it is possible to replace mailzu with modoboa... I do not need any other than quarantine access...

Regards
Peter

**Comment by tonioo** [comment]
Hi,

you can use only the quarantine part of Modoba but but you will need the admin part (domains).

**Comment by peterbeck** [comment]
Great, thanks for your reply!
I'll try to implement it that way soon.
Regards Peter
