### ISSUE TITLE
modoboa-admin.py does not create necessary folders in ../media

### ISSUE THREAD

**Issue by alienmindbender** [tonioo/modoboa#763]
Hi there,

first post on github ever - so please be lenient with me :)

The script does not create the modoboa_webmail and webmail folders in /media which seem to be needed for sending mails with attachments and viewing embedded pictures in received emails.
I haven't stumbled across the manual setup of these folders in the documentation - and since the script handles the whole directory creation these should be handled as well.

I'am using 1.3.4 btw...

cheers

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-webmail#34
