### ISSUE TITLE
Forwarding mail from within webmail client not possible

### ISSUE THREAD

**Issue by alienmindbender** [tonioo/modoboa#764]
Hi,

when trying to forward mail from within the included webmail client the "send" button gets greyed out when pressed and nothing further is happening.
Running with debug = true sheds no light on the issue and there are no strinking entries in the log files either.
However - all other webmail client functions seem to work perfectly fine.
The frontend (1.3.4) is served via apache.

Any ideas how to fix this?

**Comment by tonioo** [comment]
Hi, since this issue is related to the webmail, could you please create it into the appropriate repository ? https://github.com/modoboa/modoboa-webmail

**Comment by tonioo** [comment]
Thanks.

**Comment by alienmindbender** [comment]
Sorry - my bad.
I haven't noticed that theres a seperate repository. I'am new to this!
