### ISSUE TITLE
404 in modoboa.org

### ISSUE THREAD

**Issue by fpiccinali** [tonioo/modoboa#767]
Page http://modoboa.org/en/downloads/
Link "online documentation" :
NOT OK: http://modoboa.readthedocs.org/en/latest/virtualmachine.html
OK: https://modoboa.readthedocs.org/en/latest/additional/virtualmachine.html

Idem for http://modoboa.org/fr/telechargements/

**Comment by tonioo** [comment]
Fixed. Thank you.
