### ISSUE TITLE
Webmail - Authentication failed

### ISSUE THREAD

**Issue by artofmailing** [tonioo/modoboa#769]
Hello there, the first time i post to Github, i hope it's going to the right place.
So experiencing various issues, with using Modoboa < > Dovecot IMAP.

It's an default install, with modoboa-installer on Debian 8.1, on an stronger DigitalOcean VM.
Here is my install layout file, slightly modified: 
http://pastebin.com/02rRRkyY

Error notification / page s mainly when logging in / refreshing the INBOX,  made few screenshots :
http://i.imgur.com/uAHTOI6.png
http://i.imgur.com/PKHQxeB.png

So again, hope it's went to the right place, and in the right format. We will try to work around this issue, and keep this thread posted, but if there is any ideas please share with us :-)

Thanks y'all guys !

**Comment by tonioo** [comment]
It might a dovecot configuration issue... Do you see something interesting inside /var/log/mail.log ?

**Comment by artofmailing** [comment]
Hey !

This one is repeating when the bug happens : 

Oct 25 17:10:44 packer-debian-8-amd64 dovecot: imap-login: Disconnected (auth failed, 1 attempts in 6 secs): user=<test@bounceserver.com>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, secured, session=<+DvORvQisAB/AAAB>

Now i found something else too, that's when switching between folders :
http://i.imgur.com/QfVwkI8.png

For me it seems like some Dovecot < > SQL connection limit is being exceeded and that's causing the problem.

Different thing, but using MySQL during the install it's the same issue, but never get in to the Webmail.

**Comment by artofmailing** [comment]
Don't sure if it's related with this, but another error message pops up randomly at Webmail : 
command SELECT illegal in state NONAUTH, only allowed in states AUTH, SELECTED

Screenshot : http://i.imgur.com/RbXCreh.png

**Comment by tonioo** [comment]
I really don't understand what happens right now... Have you tried to change the user password or to change the default scheme used to encrypt passwords ?

**Comment by artofmailing** [comment]
Hey,

Yes i think i changed the default password scheme to unencrypted, PLAIN. Maybe that's why ?

**Comment by tonioo** [comment]
Ok, I've found the bug. Passwords are stored into session and are crypted using AES and a secret key. But this secret key has no default value on a fresh install...

The latest commit should fix this but you can just save global parameters once to set a secret key. Authentication should then work as expected.

**Comment by artofmailing** [comment]
Hello tonioo !

Thanks for the fast reply, we're now testing this out, and will share our feedbacks :-)

**Comment by tonioo** [comment]
@artofmailing ping

**Comment by artofmailing** [comment]
Hey tonioo ! Sorry for the late reply, with the latest commit you did it seems to be all fine !
