### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by rebootit** [tonioo/modoboa#771]
Hi,

I've got an issue with the Webmail when trying to read an email in a folder with an accent (é).
I can list all the mail within this folder but can't open the mails.
Modoboa is installed on a Ubuntu 14.04 LXC container, with a french environement.
Moreover I can't find any Modoboa log (only nginx logging the 500 error). 

Is there a known bug or is it a problem with my setup ?

**Comment by tonioo** [comment]
Hi,

this issue has already been reported : https://github.com/modoboa/modoboa-webmail/issues/31.
