### ISSUE TITLE
Wrong Per-domain counters

### ISSUE THREAD

**Issue by karimelc** [tonioo/modoboa#774]
The per-domain counters in the Statistics section seems to be off. All my values are greater than the actuals. Adding a new simpleuser seems to increase the counter for that domain by 2.

modoboa==1.3.5
modoboa-admin==1.1.2

**Comment by tonioo** [comment]
Thanks for your feedback but you could please create your issue into the appropriate repository:
https://github.com/modoboa/modoboa-admin

**Comment by karimelc** [comment]
Sorry, my bad!
