### ISSUE TITLE
Can't create users who are not "Superadmins"

### ISSUE THREAD

**Issue by torbenwilkening** [tonioo/modoboa#778]
Hallo,
i'm using modoboa 1.3.5 and I don't know why, but i can't create users who are not a superadmin.
Reseller, User & Domain admins doesn't work.
I turned on Debug in settings.py, the response after click on submit is: 
"DoesNotExist at /admin/accounts/new/
Group matching query does not exist."
Do you know what can be wrong and how to solve? It was a clean installation, did I forget something at the configuration?

Thanks

**Comment by tonioo** [comment]
Hi,
have you installed extensions with Modoboa ?

**Comment by torbenwilkening** [comment]
so i install fresh with the installer (for lazy people :) ) and i installed with all extensions.. postfix/dovecot works fine, i can receive and send mails. The only problem is this..

**Comment by tonioo** [comment]
The installation must have failed at some point. Could you try to run it once again using the --debug option ? (remember to remove the /srv/modoboa/instance directory before)

**Comment by torbenwilkening** [comment]
uh I'm a bit afraid to do that, else the configuration is running perfect. I had also several problems with the installer, especially with write permissions etc. I changed the home_dir to a different one.
I believe it's something with amavis, but i'm not sure. Thats the traceback of my error 500:
http://pastebin.com/i1gX5uGP

**Comment by tonioo** [comment]
Can you try to run the following commands please:
```
$ source <home_dir>/env/bin/activate
$ cd <home_dir>/instance
$ python manage.py load_initial_data
```

**Comment by torbenwilkening** [comment]
Now it works! Don't know why exactly but i can create simple users and edit them too. 

By the way, the installer had a few errors at my installation. I had to create the directory <home_dir>/instance/media by hand and chown it, else it failed. I also tried to change the <home_dir> variable in installer.cfg but it still puts some files in /srv/modoboa which I merged to my <home_dir>, maybe it's a hardcoded path somewhere? 

But else everything was good, now I'm running the current modoboa release with every plugin, the installer helped a lot. I like the development here.

Thanks

**Comment by tonioo** [comment]
I'd be interested to know more about the errors you encountered. Do you have any trace ?

**Comment by torbenwilkening** [comment]
Today I tried again with the newest version and a fresh and clean VM and it worked very well.
The only thing i noticed is, that the homedir must exist, else you get this:

Traceback (most recent call last):
  File "run.py", line 64, in <module>
    main()
  File "run.py", line 54, in main
    scripts.install("modoboa", config)
  File "/root/modoboa/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/root/modoboa/modoboa-installer/modoboa_installer/scripts/base.py", line 138, in run
    self.post_run()
  File "/root/modoboa/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 113, in post_run
    self._deploy_instance()
  File "/root/modoboa/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 73, in _deploy_instance
    sudo_user=self.user, cwd=self.home_dir)
  File "/root/modoboa/modoboa-installer/modoboa_installer/utils.py", line 61, in exec_cmd
    process = subprocess.Popen(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/host/modoboa'

My homedir was /host/modoboa...

Else it works great, thanks. Good development here!

**Comment by tonioo** [comment]
The homedir is automatically created when the user "modoboa" is added by the script. But, if the user already exists, it won't be added anymore. So, if the folder was deleted for some reason, it won't be recreated by the installer.
