### ISSUE TITLE
Ignore lower/upper characters in email addresses

### ISSUE THREAD

**Issue by jonathan00** [tonioo/modoboa#779]
hi,

just saw on http://modoboa.readthedocs.org/en/latest/integration/imap_and_smtp.html your sql querys
user_query and password_query for dovecot.

probably you have the same issue i had with vboxadm 
see https://crazylinux.de/Vboxadm#Ignore_lower.2Fupper_characters_in_email_addresses
for a solution

**Comment by tonioo** [comment]
Hi,

Modoboa already lowers email addresses at creation/update time. (https://github.com/tonioo/modoboa/blob/master/modoboa/admin/forms/account.py#L228)

**Comment by jonathan00** [comment]
Hi,

this does not fix the problem.

Your query "SELECT '<mailboxes storage directory>/%d/%n' AS home" will use the mail address, e.g. "FOOBAR@some.com" or "foobar@some.com".

so home will be like /var/mail/some.com/FOOBAR or /var/mail/some.com/foobar.
This is a little difference ;-)

again, see my link for a solution ;-)

**Comment by tonioo** [comment]
@jonathan00 Actually, the best place to report this issue is the installer repository since it manages dovecot's configuration. I'll fix the documentation too.
