### ISSUE TITLE
Difference between aliases and forwards in admin panel?

### ISSUE THREAD

**Issue by virtuaris** [tonioo/modoboa#783]
Hei Tonio,

first of all many thanks for your great work! 

I have a question regarding creating `aliases` and `forwards` using the Modoboa admin panel (Identities).
While the functionality of an `alias` is pretty clear a `forward` pretends to be something different but in fact ends up just as another `alias` (it's even taged with `alias` in the identities list). Thus i do not understand what's the difference?!
I would expect a `forward` to offer the `keep local copy` option as it is available when managing settings as a simple user.
Currently (using Modoboa 1.3.4) this makes it impossible (at least for me) to create a `forward` pointing to another account within the same mail domain (e.g. `foo@example.net` pointing to `bar@example.net`). Trying to setup such a `forward` as a simple user the user interface says the administrator should create an `alias` instead. But an `alias` redirects **all** mails to the given target (`bar@example.net`). The mail never reaches the intended recipient (`foo@example.net`).
Maybe the order of `postfix sql-maps` matters? My current setup:
```
virtual_mailbox_domains = mysql:/etc/postfix/maps/sql-domains.cf
virtual_alias_domains = mysql:/etc/postfix/maps/sql-domain-aliases.cf
virtual_alias_maps = mysql:/etc/postfix/maps/sql-aliases.cf,
                     mysql:/etc/postfix/maps/sql-domain-aliases-mailboxes.cf,
                     mysql:/etc/postfix/maps/sql-autoreplies.cf,
                     mysql:/etc/postfix/maps/sql-mailboxes-self-aliases.cf,
                     mysql:/etc/postfix/maps/sql-catchall-aliases.cf
```
Any idea?

Cheers!

Harald

**Comment by tonioo** [comment]
Hi,

to be honest, this difference does not make sense anymore... The best would be to use aliases everywhere. If you want to keep local copies for an alias (as an administrator), just create an distribution list named like the address you want to route and containing two targets : the "forward" address and the local mailbox address.

**Comment by virtuaris** [comment]
Hei tonioo,
using a `distribution list` works for me. Thx a lot!
Bests
Harald
