### ISSUE TITLE
Error: LOGIN command error: BAD ['Missing \'"\'']

### ISSUE THREAD

**Issue by ezhishui** [tonioo/modoboa#797]
I logged in as a simpleuser,i see Error: LOGIN command error: BAD ['Missing \'"\''] when i click webmail.

The var/logs/mail.err :ubuntu dovecot: lmtp(2885): Fatal: Error reading configuration: Invalid settings: postmaster_address setting not given

what it means?

**Comment by tonioo** [comment]
Hi,
looks like your Dovecot configuration is not complete. Have you installed Modoboa using the installer ?

**Comment by ezhishui** [comment]
Hi,
thanks for helping me so quickly,i installed modoboa according to the user guide which is for lazy ones.
Maybe i need to reinstall modoboa?

**Comment by tonioo** [comment]
No, but please try to add the postmaster_address setting into the /etc/dovecot/conf.d/20-lmtp.conf file as follows:
```ini
protocol lmtp {
    postmaster_address = postmaster@<YOURDOMAINHERE>
    # Do not modify the remaining part
    # ...
}
```

**Comment by ezhishui** [comment]
Thank you very much,i still have a few questions what confused me.
1、It seems that most responses respond very slow.Such as when i click List Identities i need to wait for about 5s.
2、If i want to reinstall modoboa,the old one has installed nginx and the other modules.Need i delete these modules?
thanks

**Comment by tonioo** [comment]
About the response time, I can't tell you what's going on like that. Maybe your server requirements are too small, maybe DEBUG mode is activated inside settings.py and so on.

The reinstallation process will depend on the current installation age
* If it's a fresh install, just drop the Modoboa directory (/srv/modoboa/instance with the installer) and run the installer once again
* If it is an old one and you were not the guy who did it, start with a new server ?

**Comment by ezhishui** [comment]
you are great!
