### ISSUE TITLE
Simple Sender-Address Management for smtpd_sender_login_maps

### ISSUE THREAD

**Issue by tonioo** [tonioo/modoboa#802]
_From @kokel on August 4, 2015 11:9_

Hello,

thanks for implementing support for all the sender_login_maps.
One feature I am missing here. We have several shared mailboxes users have access to via IMAP acls.
These shared mailboxes from modoboa point of view are normal accounts. 

For example the user ```user01@example.com``` should be able to send mails with MAIL FROM address of the shared mailboxes e.g. ```shared01@example.com```. With the current implementation this is not possible.

Please add support for simple ```allowed from addresses``` which can be configured e.g. for normal account identities in the mail context.

It also would be great to have some kind of overview for the allowed sender addresses. e.g. a listing for all accounts/aliases etc. which account is allowed to send mails in account of.

Thanks in advance!

_Copied from original issue: modoboa/modoboa-admin#39_

**Comment by carragom** [comment]
@tonioo and @kokel

I'm not sure I understand completely the scenario here but shouldn't having this configuration like this in postfix achieve the objective?:

```
smtpd_sender_restrictions =
    permit_sasl_authenticated,
    reject_sender_login_mismatch,
```

First we permit any authenticated user to send from anywhere and then we reject if there is a mismatch, this would only apply to incoming mail.

I don't remember if my `sender-login` query is custom or not but here it's:

```
SELECT username
    FROM admin_mailbox m
        JOIN admin_domain d ON (m.domain_id = d.id)
        JOIN core_user u ON (m.user_id = u.id)
    WHERE
        d.enabled
        AND u.is_active
        AND u.username = '%s'
        AND d.name = '%d';
```

This is for version `1.2.2`.

**Comment by tonioo** [comment]
@carragom , this is already provided by Modoboa (https://github.com/tonioo/modoboa/blob/master/modoboa/admin/postfix_maps.py#L97).
The subject here is to add the possibility to add extra values on a per account basis.

**Comment by carragom** [comment]
I see so instead of all or nothing, you could actually pick which from addresses a user can use. That sounds useful.

**Comment by tonioo** [comment]
@carragom @kokel Should we allow this feature to administrators only? I guess it is dangerous to let simple users edit such a list...

**Comment by carragom** [comment]
Yeah I think it would be a good idea to restrict this to admins only.

**Comment by kokel** [comment]
Ohai, sorry for late answer. +1 for administratively editing.
