### ISSUE TITLE
User can't create *@example.com => @otherdomain.com alias

### ISSUE THREAD

**Issue by tonioo** [tonioo/modoboa#803]
_From @harobed on July 1, 2015 12:5_

User can't create ```*@example.com``` => ```@otherdomain.com``` alias.

Solution : 

* user define *@example.com => *@otherdomain.com in modoboa-admin user interface
* append ```TRIM(LEADING '*' FROM al.extmboxes)``` here : https://github.com/modoboa/modoboa-admin/blob/master/modoboa_admin/postfix_maps.py#L66

What do you think about this solution ?

_Copied from original issue: modoboa/modoboa-admin#32_

**Comment by tonioo** [comment]
_From @harobed on July 2, 2015 13:26_

What do you think about this proposition ?

**Comment by tonioo** [comment]
As modoboa already provides a way to create domain aliases (based on http://www.postfix.org/postconf.5.html#virtual_alias_domains), we need to know what's the best mechanism.

**Comment by SonRiab** [comment]
Trim leading * from alias addresses before saving them would reduce wrong user input for catch-all aliases. Doing it in the mapping file is to late in my opinion. And adding domain aliases this way is confusing. The already provided way is much clearer for me.

**Comment by tonioo** [comment]
Catchall aliases are no longer defined using a * character. Modoboa does now respect the internal postfix format.
