### ISSUE TITLE
Sieve rules do not seem to get processed

### ISSUE THREAD

**Issue by Fulviuus** [tonioo/modoboa#807]
I am unable to get any rules processed by the LDA.

I have installed modoboa using the online installer, and enabled the sieve rules according to the documentation here:

http://modoboa.readthedocs.org/en/latest/integration/imap_and_smtp.html#managesieve-sieve

At first, dovecot refused to restart because of this line:

    service managesieve {
      # Max. number of ManageSieve processes (connections)
      process_count = 1024
    }

Which gives this error when enabled:

    doveconf: Fatal: Error in configuration file /etc/dovecot/conf.d/20-managesieve.conf line 32: Unknown setting: process_count

Commenting it out seems to work, and I also get a response from Pigeonhole on port 4190:

    "IMPLEMENTATION" "Dovecot Pigeonhole"
    "SIEVE" "fileinto reject envelope encoded-character vacation subaddress comparator-i;ascii-numeric relational regex imap4flags copy include variables body enotify environment mailbox date ihave"
    "NOTIFY" "mailto"
    "SASL" "PLAIN"
    "STARTTLS"
    "VERSION" "1.0" 
    OK "Dovecot (Ubuntu) ready."

Creating rules from the Modoboa webinterface also seems to be ok (and also works from Roundcube), but even the simplest of rules (Send to spam is Subject contains 'hello') gets ignored.
Is there something I am missing?

**Comment by tonioo** [comment]
Try to edit the 20-lmtp.conf file and to modify the mail_plugins settings as follows:
```
mail_plugins = $mail_plugins quota sieve
```

**Comment by Fulviuus** [comment]
This seems to have been the issue indeed.
With that change the filters work fine, both from Modoboa and Roundcube.
Thanks!
