### ISSUE TITLE
How to create a domain and user by command or run a .py file?

### ISSUE THREAD

**Issue by ezhishui** [tonioo/modoboa#808]
Hi ,
i want to create a domain and a user by command as i do not have a desktop,is it possible?
I also want to run modoboa in a public server and others can visit it like https://120.75.23.6,but i comes 502 Bad Gateway.What i should do?

**Comment by tonioo** [comment]
You can try the CSV impprt feature:

$ python manage.py import_domains <file>

**Comment by tonioo** [comment]
Declare the public address you want to use inside ALLOWED_HOSTS
