### ISSUE TITLE
How to receive email from other servers?

### ISSUE THREAD

**Issue by ezhishui** [tonioo/modoboa#811]
I have installed modoboa,but it can not receive any email from other email server because i am not sure whether my configuration of the email  DNS is correct,for example:

the target receiver:u1@iwho.xyz
DNS:
A mail 111.200.55.28
MX @  mail.iwho.xyz.
CNAME smtp smtp.iwho.xyz
CNAME  pop3 pop3.iwho.xyz
TXT @ v=spf1 include:spf.iwho.com ~all

The send email server comes error:
Name service error for name=iwho.xyz type=MX: Host not found
I do not know what is wrong.
Can you help me ,i am new here,thank you very much!

**Comment by SonRiab** [comment]
the cname records seems wrong to me. see https://en.wikipedia.org/wiki/CNAME_record. should be CNAME smtp mail.iwho.xyz. and there is no a record for your main domain: A 111.200.55.28 should do the work.

**Comment by ezhishui** [comment]
@SonRiab 
Thank you ,you are so great.
I modify the cname and it works, the new error comes:
host mail.iwho.xyz[111.200.55.28] said: 550 5.7.1 Service unavailable; client [183.60.60.180] blocked using zen.spamhaus.org (in reply to RCPT TO command).

and the send server told me modoboa confirm the email is a spam mail then rejected it.
Do you have any solutions please?

**Comment by ezhishui** [comment]
@SonRiab  Thank you.I modified cname and it works.

But i need help,guys:
![screenshot from 2015-12-08 18_54_17](https://cloud.githubusercontent.com/assets/15809303/11654211/dc28f024-9dde-11e5-83bf-5458a1e9344c.png)

**Comment by ezhishui** [comment]
I have sent a mail from 126.com to u1@iwho.xyz.It rejected by my server,what does it means?Anything 
went wrong?

**Comment by ezhishui** [comment]
Help,Help!

**Comment by xpunkt** [comment]
ezhishui skrev den 2015-12-08 12:07:

> But i need help,guys:

you miss to define where root reads mails, when done dovecot-lmtp would 
not say unknown user :)

the error is in postfix/sendmail alias database for how and where unix 
users is mapped to non priviledged user logins

for postfix its in /etc/mail/aliasses find the line with root: and 
change it to a mailaddress local or external, local have no @, external 
have, the most important is that dovecot knows this user else it will 
reject as your example shows

root: me@junc.eu
newaliasses
postfix reload

testing

sendmail -bv root

did it work ? :=)

and no you should not put my email in your alias database it just how i 
did

**Comment by xpunkt** [comment]
https://dmarcian.com/spf-survey/iwho.xyz

**Comment by ezhishui** [comment]
@xpunkt Thank you.
It works,i create user root then the error "User does not exist"no longer appears. 
But what confused me is :
Connect from <ip> to <ip>
THen NOQUEUE reject
Then disconnect.
Then WARNING.

**Comment by ezhishui** [comment]
Spf succpended ,i just want to learn send receive mail😊😊
