### ISSUE TITLE
Reject received mails 

### ISSUE THREAD

**Issue by ezhishui** [tonioo/modoboa#812]
Hi,guys
look at the mail.log：

![20151209103653](https://cloud.githubusercontent.com/assets/15809303/11675061/8d27f352-9e61-11e5-8644-b79107897cec.png)

who can help me please,help.

**Comment by ezhishui** [comment]
I send a mail from another server to modoboa,and get the log above.Do anyone has solutions?

**Comment by ezhishui** [comment]
Here comes new problem:
The qq.com mail server sent twice ,the first time failed ,and the second time success.I tried many times,but nothing changed.Need i to add qq.com or anything else configuration to any files?
![20151209144045](https://cloud.githubusercontent.com/assets/15809303/11678540/e542281a-9e83-11e5-813d-5b030a58d387.png)

**Comment by tonioo** [comment]
Hi,
it looks like you are sending emails from a blacklisted IP address. Postscreen is enabled on your server and protects you against SPAM. Those log messages are normal. If you want to receive, just try with a valid sender (use a gmail address or equivalent).

**Comment by ezhishui** [comment]
China have the Grate Fire Wall as strong as the great wall.Gmail is not so convenient,i will have a try later.And qq.com should not be in any blacklist,it is a normal domain.

**Comment by tonioo** [comment]
Ok. Since your requests are not related to Modoboa but to Postfix, could you please ask your questions on its official mailing list ?
Thank you.

**Comment by ezhishui** [comment]
OK,thank you.
