### ISSUE TITLE
User not found using alias

### ISSUE THREAD

**Issue by rhaamo** [tonioo/modoboa#816]
Hi,

I've created an user ```dashie@mydomain.tld``` and want to alias everything so i've created an alias : ```@mydomain.tld``` redirecting to the dashie@ email.

But in logs i got from postfix:
```
Dec 15 09:39:25 derpy postfix/smtpd[16726]: NOQUEUE: reject: RCPT from ...[...]: 550 5.1.1 <rhaamo@mydomain.tld >: Recipient address rejected: undeliverable address: host ...[private/dovecot-lmtp] said: 550 5.1.1 <rhaamo@mydomain.tld > User doesn't exist: rhaamo@mydomain.tld (in reply to RCPT TO command); from=<...@...> to=<rhaamo@mydomain.tld > proto=ESMTP helo=<...>
```

What's wrong here ?

**Comment by tonioo** [comment]
Hi,
in your log, rhaama@mydomain.tld is an alias or a mailbox ?

**Comment by rhaamo** [comment]
@tonioo my mailbox is dashie@, rhaamo@ is just some other alias, which defined as alias in web-ui.
In my old setup i have some whatever@ aliased to dashie@

![identities list](http://i.imgur.com/3w7wn61.png)

**Comment by tonioo** [comment]
Looks like the alias is not resolved by postfix.
Could you try something like this please:
```bash
$ postmap -q rhaama@sigpipe.me <mysql|postgres>:/etc/postfix/sql_aliases.cf
```

**Comment by rhaamo** [comment]
```
root@derpy:/etc/postfix# postmap -q rhaamo@sigpipe.me pgsql:/etc/postfix/sql-aliases.cf
root@derpy:/etc/postfix#
```
nothing returned.
Tried with my email : returned dashie@
Tried adding an alias : ```test@``` to ```dashie@``` : returned dashie@

In the alias i tried even ```@sigpipe.me``` or ```*@sigpipe.me```, same result : nothing

**Comment by tonioo** [comment]
Strange... Could you paste you main.cf file somewhere ?

**Comment by rhaamo** [comment]
Yup, here: https://gist.github.com/rhaamo/8da666de1a79a1d10810

**Comment by tonioo** [comment]
Looks fine...

Running postmap for @sigpipe.me should return something. Have you tried to restart postfix ?

**Comment by rhaamo** [comment]
@tonioo yes restarted two times...
A postmap for just ```@sigpipe.me``` returns ```dashie@```, but ```whatever@sigpipe.me``` no :(

**Comment by tonioo** [comment]
I think postmap does not resolve wildcard aliases as we think, it is just a way to query the map as is.

Can you paste your logs ?

**Comment by rhaamo** [comment]
I removed a ```/var/lib/postfix/verify_cache.db``` which could be not updated, and it /seems/ to be ok.
I will do more tests about that tomorrow.

**Comment by y0va** [comment]
Also note the default delay of 3h ([address_verify_negative_refresh_time](http://www.postfix.org/postconf.5.html#address_verify_negative_refresh_time)) of enabling a alias when a negative request was made for that just before it's creation.
