### ISSUE TITLE
Mail show failed

### ISSUE THREAD

**Issue by ezhishui** [tonioo/modoboa#817]
Hi,
i have sent a mail which contains a picture in body,not as a attachment.
it showed the error when visit "/webmail/#?action=viewmail&mbox=INBOX&mailid=23":

IOError at /webmail/getmailcontent
[Errno 2] No such file or directory: u'./media/modoboa_webmail/23_DAE3C92E@E70C435A.430E7156.jpg'
Request Method:	GET
Request URL:	https://iwho.xyz/webmail/getmailcontent?mbox=INBOX&mailid=23&links=0
Django Version:	1.7.11
Exception Type:	IOError
Exception Value:	
[Errno 2] No such file or directory: u'./media/modoboa_webmail/23_DAE3C92E@E70C435A.430E7156.jpg'
Exception Location:	/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_webmail/lib/imapemail.py in _fetch_inlines, line 185
Python Executable:	/usr/bin/uwsgi-core
Python Version:	2.7.6
Python Path:	
['.',
 '',
 '/srv/modoboa/env/lib/python2.7',
 '/srv/modoboa/env/lib/python2.7/plat-x86_64-linux-gnu',
 '/srv/modoboa/env/lib/python2.7/lib-tk',
 '/srv/modoboa/env/lib/python2.7/lib-old',
 '/srv/modoboa/env/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/srv/modoboa/env/local/lib/python2.7/site-packages']
Server time:	Wed, 16 Dec 2015 11:34:58 +0100

The traceback:
Environment:

Request Method: GET
Request URL: https://iwho.xyz/webmail/getmailcontent?mbox=INBOX&mailid=23&links=0

Django Version: 1.7.11
Python Version: 2.7.6
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'reversion',
 'modoboa',
 'modoboa.core',
 'modoboa.lib',
 'modoboa_admin',
 'modoboa_admin_relaydomains',
 'modoboa_admin_limits',
 'modoboa_amavis',
 'modoboa_pdfcredentials',
 'modoboa_postfix_autoreply',
 'modoboa_sievefilters',
 'modoboa_stats',
 'modoboa_webmail')
Installed Middleware:
('x_forwarded_for.middleware.XForwardedForMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'modoboa.lib.middleware.AjaxLoginRedirect',
 'modoboa.lib.middleware.CommonExceptionCatcher',
 'modoboa.lib.middleware.RequestCatcherMiddleware')

Traceback:
File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/transaction.py" in inner
  394.                 return func(*args, **kwargs)
File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/transaction.py" in inner
  394.                 return func(*args, **kwargs)
File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)
File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_admin/lib.py" in wrapped_f
  29.                 return f(request, *args, **kwargs)
File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_webmail/views.py" in getmailcontent
  496.         "mailbody": email.body if email.body else ""
File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_webmail/lib/imapemail.py" in body
  129.             self._fetch_inlines()
File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_webmail/lib/imapemail.py" in _fetch_inlines
  185.             with open(path, "wb") as fpo:

Exception Type: IOError at /webmail/getmailcontent
Exception Value: [Errno 2] No such file or directory: u'./media/modoboa_webmail/23_DAE3C92E@E70C435A.430E7156.jpg'

**Comment by tonioo** [comment]
Looks like the /srv/modoboa/instance/media/modoboa_webmail folder does not exist. Create it and your issue should be fixed.

**Comment by ezhishui** [comment]
Thank you, i will have a try tomorrow i am not sure the folder whether exist.If it will be created automatically when the picture is received will be better.

**Comment by ezhishui** [comment]
I have create the folder  /srv/modoboa/instance/media/modoboa_webmail, and the error disappear but i can not see the picture in the email body from Inbox of modoboa.The picture is in the folder already,and i have read the email in vmail/myuser/cur,the base64 code of the pictrue is exist.

**Comment by ezhishui** [comment]
The email page source code:

<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="stylesheet" type="text/css" href="/sitestatic/css/viewmail.css" />
  </head>
  <body>
    <div id="table-container">
      

<div id="emailheaders" class="well">
  <div class="row">
    <div class="header">From</div><div class="value">Camus</div>
  </div><div class="row">
    <div class="header">To</div><div class="value">u2 u2</div>
  </div><div class="row">
    <div class="header">Date</div><div class="value">Thu 09:41</div>
  </div><div class="row">
    <div class="header">Subject</div><div class="value">22222</div>
  </div>
  
</div>


    </div>
    <pre></pre>
  </body>
</html>

The tag <pre> is empty.

**Comment by tonioo** [comment]
Hi, have you tried this: https://github.com/tonioo/modoboa/issues/819 ?
