### ISSUE TITLE
Wrong default value for X_FRAME_OPTIONS

### ISSUE THREAD

**Issue by tonioo** [tonioo/modoboa#819]
The default value is too restrictive, change it to "SAMEORIGIN"

**Comment by ebrahim** [comment]
Worked around it by adding two lines to `server` section of nginx config:

    more_clear_headers 'X-Frame-Options';
    add_header X-Frame-Options SAMEORIGIN;

**Comment by Sn4kY** [comment]
Be careful !
With Debian 8, to use the "more_clear_headers 'X-Frame-Options';" parameter, nginx-extras should be installed instead of nginx-full package.
