### ISSUE TITLE
Fix exported identities order

### ISSUE THREAD

**Issue by controlcde** [tonioo/modoboa#822]
I´ve exported domains and identities from a previous installation of modoboa (1.3.5) and want to import these files into a new installation with a new database. If I import the domains all entry will be imported but the import dialog will not close and a spinning import will be shown and not ended. If I import identities all mailboxes will be imported and only one alias - nothing more. The interface always show the spinning import.

**Comment by tonioo** [comment]
Hi, can you provide your CSV file please ?

**Comment by controlcde** [comment]
You´ve got mail!

**Comment by controlcde** [comment]
Sadly it doesn´t work with 1.4.4 - I upgraded 1.3.5 to 1.4.4, then I exported domains and identities and then I tried to import the domains and identities via web frontend on a new installation with a fresh database. Domains could imported but identities import stopped after the first alias.
