### ISSUE TITLE
Mailpile as webmail

### ISSUE THREAD

**Issue by titilambert** [tonioo/modoboa#824]
Hello !
I didn't found any history about this, but what do you think to use mailpile as default webmail in Modoboa?
Thanks for your answer.

**Comment by SomeGeek** [comment]
Roundcube Next is more likely as it has groupware features by default. The project started and looks promising.

https://github.com/roundcube-next

**Comment by tonioo** [comment]
@titilambert I think your question is more related to the installer.

It would be pretty easy to add the possibility to deploy a custom webmail during the installation process.

**Comment by hadifarnoud** [comment]
just saw Mailpile. looks great! I would also like to know how to add it post installation

**Comment by hadifarnoud** [comment]
@tonioo any plan to allow us add custom webmail during installation process?

**Comment by tonioo** [comment]
@hadifarnoud Feel free to modify the installer, add this feature and propose a pull request ;)

**Comment by hadifarnoud** [comment]
@tonioo if you can help me get started, I would give this a try. I would've done it if I knew how :)

**Comment by pirogoeth** [comment]
@hadifarnoud If you need to support multiple users through webmail, I'm not sure that Mailpile is quite capable enough yet to do this. They won't have full/stable multi-account support until their 1.0 milestone. If single user works in your situation, then it's perfect, especially considering the baked in PGP/GPG features. From what I can tell, it's not too bad to get running -- just clone the repo, do the pip setup, and run the setup from the Mailpile CLI. Then set the web address and reverse proxy!

**Comment by hadifarnoud** [comment]
my setups is multi-user. I guess I need to add RTL to existing webmail that comes with Modoboa. Will submit a PR soon.

I think others might like a tutorial though if you know how to do this.

**Comment by pirogoeth** [comment]
@hadifarnoud I'll look in to doing that after Mailpile has proper multi-user support :)

**Comment by tonioo** [comment]
I close this issue since it is more an installer request. Feel free to reopen it in the appropriate repository.

**Comment by hadifarnoud** [comment]
multi user support is added @pirogoeth https://github.com/mailpile/Mailpile/issues/820
