### ISSUE TITLE
Webmail 1.0.3 - Email content not displayed

### ISSUE THREAD

**Issue by Sn4kY** [tonioo/modoboa#828]
Hi.
On a fresh install of Modoboa 1.4.2, with modoboa-installer, in a newly installed debian 8.2, the webmail doen't display the content of the emails (received or sent).

Could you please help me ?
I can provide you more information if you ask for it.

![modoboa_nomail_webmail](https://cloud.githubusercontent.com/assets/2815087/12230295/b48e0e9c-b84f-11e5-9733-e14799b102e2.png)

Regards.

**Comment by tonioo** [comment]
Hi, have you tried this: https://github.com/tonioo/modoboa/issues/819 ?

**Comment by Sn4kY** [comment]
Hi.

Nope, but the solution solves the problem.

Warning, the nginx debian 8 package installed automatically by the modoba-installer (nginx-full 1.6.2) doesn't include the needed module "openresty" to add the parameter "more_clear_headers" to the nginx configuration.
I have to install nginx-extras (1.6.2) to do the job.

The solution solves the problem.

Thank you very much.
