### ISSUE TITLE
cannot add domain

### ISSUE THREAD

**Issue by hadifarnoud** [tonioo/modoboa#829]
when trying to add any domain, I get `OperationalError at /domains/new/ (1054, "Unknown column 'unchecked_lover' in 'field list'")` error

here is the full log: https://gist.github.com/hadifarnoud/3d29a8f630f02ec7e23f

**Comment by tonioo** [comment]
looks like your amavis version is too old... Which one did you install ?

**Comment by hadifarnoud** [comment]
I installed it via modoboa-admin.py deploy

**Comment by tonioo** [comment]
I am talking about amavis, not modoboa.

**Comment by hadifarnoud** [comment]
did not know modoboa wouldn't install it. Just used this to install Amavis. https://help.ubuntu.com/community/PostfixAmavisNew

I skipped the postfix part

**Comment by tonioo** [comment]
The modoboa-deploy command is only made for modoboa. If you want a complete setup, you must use the installer.

**Comment by hadifarnoud** [comment]
when I use the installer, I run into problems. the sent emails are not received on the other side. I have checked with multiple IPs. I have no idea what the issue is, but on the same server I managed to get Mail-in-a-box to work.

**Comment by hadifarnoud** [comment]
at last I couldn't fix modoboa and decided to migrate back to Mail-in-a-box :(

**Comment by schneidermayer** [comment]
Got the same issue, fixed it by setting proper permissions for the webserver user www-data on a) the modoboa instance and b) the wsgi lock file:

Use this if you have Nginx with uWSGI:
chmod -R 774 /run/uwsgi/app/
chown -R modoboa:www-data /run/uwsgi/

Use this if you have Apache with mod_wsgi:
chmod -R 774 /var/run/apache2/
chown -R modoboa:www-data /var/run/apache2/

Finally, set permission on those folder, just in case:
chown -R modoboa:www-data /srv/modoboa

Check syslog and apache2 access+error logs and always restart the webserver. If you use nginx don't forget to restart uwsgi seperately!

Caution, the chown is way too lose. If it works you may wanna specify it in detail.
