### ISSUE TITLE
Temporary lookup failure in postfix because of failure in sql-sender-login-aliases.cf

### ISSUE THREAD

**Issue by lexusburn** [tonioo/modoboa#830]
i found a bug in bug in postfix_maps.py:
for postgres database you had a reference on relation "admin_aliasrecipient" instead of "modoboa_admin_aliasrecipient". On creating sql-sender-login-aliases.cf you get a file that get a fatak error from pgsql.

bugfix is simple: search for  "admin_aliasrecipient" and replace with "modoboa_admin_aliasrecipient".

**Comment by tonioo** [comment]
Thanks for reporting but this issue has already been fixed, see  #814.

**Comment by whyscream** [comment]
Named commit only solves this for the `sql-aliases.cf` file, not for `sql-sender-login-aliases.cf`. Please also fix the other file

**Comment by tonioo** [comment]
Sorry, I read to quickly.
