### ISSUE TITLE
Account API

### ISSUE THREAD

**Issue by tonioo** [tonioo/modoboa#832]
Add new services to the API to:
* Retrieve a list of accounts (global or per domain)
* Get a single account
* Create a new account
* Modify an account
* Delete an account

**Comment by gawel** [comment]
Another good service that you can add is "email exists". Since in the real world the only way to be sure that an email exist is to send an email, it would be cool if modoboa can provide this.

Something like:
```
GET /api/accounts/<email>/exists
{exists: (true|false}}
```

Thought ?

**Comment by tonioo** [comment]
Yes it could be useful.

**Comment by tonioo** [comment]
@gawel What do you think about:
```
GET /api/accounts/exists/?email=<email>
{exists: (true|false}}
```
I'm not a DRF expert but looking at the documentation, it looks simpler to implement. (see http://www.django-rest-framework.org/api-guide/viewsets/#marking-extra-actions-for-routing)

**Comment by gawel** [comment]
Yep, that work. I'm not a DRF expert too :)

**Comment by hadifarnoud** [comment]
cool. where can I find API docs? could not find it on your site.

**Comment by tonioo** [comment]
The API is not released yet. I'll add the documentation soon.

**Comment by hadifarnoud** [comment]
eagerly waiting for API docs. btw, I could help out polishing the docs once I figure out how it works myself.

**Comment by mangliobertoluci** [comment]
Hello everyone. Is it possible to edit this API to generate "email packages" with storage limits and "email sending limits" and permissions?
