### ISSUE TITLE
Parameters panel does not represent correct settings in 1.4.3

### ISSUE THREAD

**Issue by schefi** [tonioo/modoboa#835]
I discovered a bug in the parameters panel, the bug was introduced in 1.4.3. Saving settings works correctly, I checked the entries in lib_parameter table. But navigating elsewhere and returning to or reloading the parameters page always shows defaults (initial values), not the last saved settings. 
This is unconvinient, since I have to re-enter all values if I would like to make a single change, including reentering former secret key.

**Comment by whyscream** [comment]
Seeing same behaviour here

**Comment by tonioo** [comment]
I'll look into it ASAP.

**Comment by tonioo** [comment]
@schefi @whyscream Could try this fix please ?

**Comment by schefi** [comment]
I applied the commit. It works OK now. Thanks!

**Comment by whyscream** [comment]
works again! TY :)
