### ISSUE TITLE
Internal Error in stats view

### ISSUE THREAD

**Issue by fionnb** [tonioo/modoboa#836]
Hi, on a fresh 1.4.3 install I get errors in the stats module. 

 ```
File "modoboa_stats/graphics.py", line 94, in export
    timestamp = int(row.find('t').text)
```

`AttributeError: 'NoneType' object has no attribute 'text'`

i went digging a bit and had it dump the command, which is:

`rrdtool xport --start -1week --end 1455825274 DEF:size_recv=/mail/modoboa/stats/global.rrd:size_recv:AVERAGE CDEF:size_recvpm=size_recv,60,* XPORT:size_recvpm:"Empfangsgr\xc3\xb6sse" DEF:size_sent=/mail/modoboa/stats/global.rrd:size_sent:AVERAGE CDEF:size_sentpm=size_sent,60,* XPORT:size_sentpm:"Versendegr\xc3\xb6sse"`

Apparently, when using this command, the result will not contain any 't' fields:

  ```
<data>
    <row><v>3.9836091071e+05</v><v>6.2045392857e+04</v></row>
  ...
```

... and the subsequent code fails. I wonder what goes wrong while constructing the command?

Can I do anything to make it work properly?

Using rrdtool 1.5.5 btw.

**Comment by tonioo** [comment]
Indeed, it looks pretty strange... Could you try with an older version of rrdtool (like 1.4.7) ?

**Comment by fionnb** [comment]
confirmed: <t> appears in 1.4.7 and is missing in 1.5.5.

**Comment by tonioo** [comment]
Looks like the output is a bit different with 1.5.5. Anyway, 1.5.5 should have a working JSON output (unlike 1.4.7), I'll make a change to use it if present.

**Comment by fionnb** [comment]
I get it that 1.4.4 does not have the fix yet?

**Comment by tonioo** [comment]
You're right. The stats plugin has its own repository (https://github.com/modoboa/modoboa-stats) so this issue is misplaced.

**Comment by fionnb** [comment]
I am sorry then. Should I open an issue there or just wait for an update to appear?
Fell free to close this issue if inappropriate.

**Comment by tonioo** [comment]
Don't worry, I'm going to move this issue.

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-stats#11
