### ISSUE TITLE
Mail for the mail server's FQDN loops back to itself

### ISSUE THREAD

**Issue by armouredking** [tonioo/modoboa#837]
So after running my Modoboa server for a few days ( and able to send and receive mail - tested between my other email accounts as well as with some app services and things work as expected ) I check the logs just to see what's going on and find them _filled_ with:

```
Feb 28 11:50:04 modoboa postfix/pickup[7874]: CC44916C7A: uid=0 from=<root>
Feb 28 11:50:04 modoboa postfix/cleanup[8397]: CC44916C7A: message-id=<20160228115004.CC44916C7A@computername.domain.tld>
Feb 28 11:50:04 modoboa postfix/qmgr[1998]: CC44916C7A: from=<root@computername.domain.tld>, size=1920, nrcpt=1 (queue active)
Feb 28 11:50:04 modoboa postfix/smtp[8399]: warning: CC44916C7A: defer service failure
Feb 28 11:50:04 modoboa postfix/smtp[8399]: CC44916C7A: to=<root@computername.domain.tld>, orig_to=<root>, relay=none, delay=0.06, delays=0.04/0.02/0/0, dsn=4.3.0, status=deferred (bounce or trace service failure)
Feb 28 11:50:04 modoboa postfix/cleanup[8397]: E383A16C7F: message-id=<20160228115004.E383A16C7F@computername.domain.tld>
Feb 28 11:50:04 modoboa postfix/bounce[8400]: CC44916C7A: sender non-delivery notification: E383A16C7F
Feb 28 11:50:04 modoboa postfix/qmgr[1998]: E383A16C7F: from=<>, size=3915, nrcpt=1 (queue active)
Feb 28 11:50:04 modoboa postfix/qmgr[1998]: CC44916C7A: status=deferred (bounce failed)
Feb 28 11:50:04 modoboa postfix/smtp[8399]: E383A16C7F: to=<root@computername.domain.tld>, relay=none, delay=0.01, delays=0/0.01/0/0, dsn=5.4.6, status=bounced (mail for computername.domain.tld loops back to myself)
Feb 28 11:50:04 modoboa postfix/qmgr[1998]: E383A16C7F: status=deferred (bounce failed)
```

And I do mean filled. Like nonstop. The domain name it's servicing is domain.tld, I don't have anything setup for computername.domain.tld ( where computername is the host of the Modoboa computer so basically this string is the mail server's FQDN ). Do I need to set this up in modoboa? I'm assuming this is some service account issue thing because root@whatever isn't going to be any regular mail account...

**Comment by patrickbenkoetter** [comment]
This is a beginners question for Postfix users. It is definitely NOT a
question for modoboa.

p@rick



* armouredking <reply@reply.github.com>:
> So after running my Modoboa server for a few days ( and able to send and receive mail - tested between my other email accounts as well as with some app services and things work as expected ) I check the logs just to see what's going on and find them _filled_ with:
> 
> ```
> Feb 28 11:50:04 modoboa postfix/pickup[7874]: CC44916C7A: uid=0 from=<root>
> Feb 28 11:50:04 modoboa postfix/cleanup[8397]: CC44916C7A: message-id=<20160228115004.CC44916C7A@computername.domain.tld>
> Feb 28 11:50:04 modoboa postfix/qmgr[1998]: CC44916C7A: from=<root@computername.domain.tld>, size=1920, nrcpt=1 (queue active)
> Feb 28 11:50:04 modoboa postfix/smtp[8399]: warning: CC44916C7A: defer service failure
> Feb 28 11:50:04 modoboa postfix/smtp[8399]: CC44916C7A: to=<root@computername.domain.tld>, orig_to=<root>, relay=none, delay=0.06, delays=0.04/0.02/0/0, dsn=4.3.0, status=deferred (bounce or trace service failure)
> Feb 28 11:50:04 modoboa postfix/cleanup[8397]: E383A16C7F: message-id=<20160228115004.E383A16C7F@computername.domain.tld>
> Feb 28 11:50:04 modoboa postfix/bounce[8400]: CC44916C7A: sender non-delivery notification: E383A16C7F
> Feb 28 11:50:04 modoboa postfix/qmgr[1998]: E383A16C7F: from=<>, size=3915, nrcpt=1 (queue active)
> Feb 28 11:50:04 modoboa postfix/qmgr[1998]: CC44916C7A: status=deferred (bounce failed)
> Feb 28 11:50:04 modoboa postfix/smtp[8399]: E383A16C7F: to=<root@computername.domain.tld>, relay=none, delay=0.01, delays=0/0.01/0/0, dsn=5.4.6, status=bounced (mail for computername.domain.tld loops back to myself)
> Feb 28 11:50:04 modoboa postfix/qmgr[1998]: E383A16C7F: status=deferred (bounce failed)
> ```
> 
> And I do mean filled. Like nonstop. The domain name it's servicing is domain.tld, I don't have anything setup for computername.domain.tld ( where computername is the host of the Modoboa computer so basically this string is the mail server's FQDN ). Do I need to set this up in modoboa? I'm assuming this is some service account issue thing because root@whatever isn't going to be any regular mail account...
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/tonioo/modoboa/issues/837

-- 
[*] sys4 AG
 
https://sys4.de, +49 (89) 30 90 46 64
Franziskanerstraße 15, 81669 München
 
Sitz der Gesellschaft: München, Amtsgericht München: HRB 199263
Vorstand: Patrick Ben Koetter, Marc Schiffbauer
Aufsichtsratsvorsitzender: Florian Kirstein

**Comment by armouredking** [comment]
Perhaps you should read my question again. Recall the one I _actually_ asked?

> Do I need to set this up in modoboa?

Judging by your answer I will assume that a command line edit in Postfix _will_ suffice and not be overwritten by Modoboa.
