### ISSUE TITLE
cant update identities

### ISSUE THREAD

**Issue by blendi-93** [tonioo/modoboa#838]
icant update older identities.

updatet to version 1.4.4

i try to edit an identitie and if i hit update i get 
````SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data````

    AttributeError at /admin/accounts/edit/696/
    'NoneType' object has no attribute 'group'

    Request Method: POST
    Request URL: https://mail.netzwerkplan.de/admin/accounts/edit/696/
    Django Version: 1.8.9
    Python Executable: /usr/bin/python
    Python Version: 2.7.6
    Python Path: ['/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/pymodules/python2.7', '/var/www/mailadmin']
    Server time: Mo, 29 Feb 2016 16:31:40 +0100
    Installed Applications:
    ('django.contrib.auth',
     'django.contrib.contenttypes',
     'django.contrib.sessions',
     'django.contrib.messages',
     'django.contrib.sites',
     'django.contrib.staticfiles',
     'reversion',
     'rest_framework.authtoken',
     'modoboa',
     'modoboa.core',
     'modoboa.lib',
     'modoboa.admin',
     'modoboa.relaydomains',
     'modoboa.limits',
     'modoboa_pdfcredentials',
     'modoboa_postfix_autoreply',
     'modoboa_imap_migration',
     'modoboa_webmail',
     'modoboa_sievefilters',
     'modoboa_amavis',
     'modoboa_stats')
    Installed Middleware:
    ('x_forwarded_for.middleware.XForwardedForMiddleware',
     'django.contrib.sessions.middleware.SessionMiddleware',
     'django.middleware.common.CommonMiddleware',
     'django.middleware.csrf.CsrfViewMiddleware',
     'django.contrib.auth.middleware.AuthenticationMiddleware',
     'django.contrib.messages.middleware.MessageMiddleware',
     'django.middleware.locale.LocaleMiddleware',
     'django.middleware.clickjacking.XFrameOptionsMiddleware',
     'modoboa.lib.middleware.AjaxLoginRedirect',
     'modoboa.lib.middleware.CommonExceptionCatcher',
     'modoboa.lib.middleware.RequestCatcherMiddleware')

    Traceback:
    File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
      132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
    File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py" in inner
      145.                     return func(*args, **kwargs)
    File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py" in inner
      145.                     return func(*args, **kwargs)
    File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
      22.                 return view_func(request, *args, **kwargs)
    File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
      22.                 return view_func(request, *args, **kwargs)
    File "/usr/local/lib/python2.7/dist-packages/reversion/revisions.py" in do_revision_context
      323.                 return func(*args, **kwargs)
    File "/usr/local/lib/python2.7/dist-packages/modoboa/admin/views/identity.py" in editaccount
      181.     return AccountForm(request, instances=instances).process()
    File "/usr/local/lib/python2.7/dist-packages/modoboa/lib/form_utils.py" in process
      349.                 self.save()
    File "/usr/local/lib/python2.7/dist-packages/modoboa/admin/forms/account.py" in save
      475.             "AccountModified", self.instances["general"], self.account
    File "/usr/local/lib/python2.7/dist-packages/modoboa/lib/events.py" in raiseEvent
      90.         callback(*args, **kwargs)
    File "/usr/local/lib/python2.7/dist-packages/modoboa/limits/controls.py" in on_account_modified
      161.     if owner.group not in ["SuperAdmins", "Resellers"]:

    Exception Type: AttributeError at /admin/accounts/edit/696/
    Exception Value: 'NoneType' object has no attribute 'group'
    Request information:
    GET: No GET data

    POST:
    username = u'nwp@sadoni.net'
    password1 = u''
    first_name = u'aaaa'
    last_name = u''
    is_active = u'on'
    password2 = u''
    aliases_1 = u'nwp@sadoni.net'
    role = u'SimpleUsers'
    quota_act = u'on'
    csrfmiddlewaretoken = u'MYse3Evon4oOCYva9RO310OTXNOu0yAB'
    email = u'nwp@sadoni.net'
    aliases = u''

    FILES: No FILES data

    COOKIES:
    csrftoken = 'MYse3Evon4oOCYva9RO310OTXNOu0yAB'
    sessionid = 'vn2mpmju77cad4zi490ttkk1yrqfopyw'

    META:
    mod_wsgi.listener_port = '443'
    HTTP_COOKIE = 'csrftoken=MYse3Evon4oOCYva9RO310OTXNOu0yAB; sessionid=vn2mpmju77cad4zi490ttkk1yrqfopyw'
    mod_wsgi.listener_host = ''
    mod_wsgi.handler_script = ''
    CONTEXT_DOCUMENT_ROOT = '/var/www/mailadmin/'
    SERVER_SOFTWARE = 'Apache/2.4.7 (Ubuntu)'
    SCRIPT_NAME = u''
    mod_wsgi.enable_sendfile = '0'
    HTTP_X_CSRFTOKEN = 'MYse3Evon4oOCYva9RO310OTXNOu0yAB'
    SERVER_SIGNATURE = '<address>Apache/2.4.7 (Ubuntu) Server at mail.netzwerkplan.de Port 443</address>\n'
    REQUEST_METHOD = 'POST'
    PATH_INFO = u'/admin/accounts/edit/696/'
    SERVER_PROTOCOL = 'HTTP/1.1'
    QUERY_STRING = ''
    SSL_TLS_SNI = 'mail.netzwerkplan.de'
    CONTENT_LENGTH = '229'
    HTTP_USER_AGENT = 'Mozilla/5.0 (Windows NT 6.3; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0'
    HTTP_CONNECTION = 'keep-alive'
    HTTP_REFERER = 'https://mail.netzwerkplan.de/admin/identities/'
    SERVER_NAME = 'mail.netzwerkplan.de'
    REMOTE_ADDR = '91.90.144.102'
    mod_wsgi.queue_start = '1456759900764419'
    mod_wsgi.request_handler = 'wsgi-script'
    wsgi.url_scheme = 'https'
    PATH_TRANSLATED = '/var/www/mailadmin/wsgi.py/admin/accounts/edit/696/'
    SERVER_PORT = '443'
    wsgi.multiprocess = True
    mod_wsgi.input_chunked = '0'
    SERVER_ADDR = '46.245.177.46'
    DOCUMENT_ROOT = '/var/www/mailadmin/'
    mod_wsgi.process_group = ''
    HTTP_X_REQUESTED_WITH = 'XMLHttpRequest'
    SCRIPT_FILENAME = '/var/www/mailadmin/wsgi.py'
    SERVER_ADMIN = '[no address given]'
    wsgi.input = <mod_wsgi.Input object at 0x7f9207a4abf0>
    HTTP_HOST = 'mail.netzwerkplan.de'
    CONTEXT_PREFIX = ''
    wsgi.multithread = False
    mod_wsgi.callable_object = 'application'
    REQUEST_URI = '/admin/accounts/edit/696/'
    HTTP_ACCEPT = '*/*'
    wsgi.version = 
    GATEWAY_INTERFACE = 'CGI/1.1'
    wsgi.run_once = False
    wsgi.errors = <mod_wsgi.Log object at 0x7f9207a4aaf0>
    REMOTE_PORT = '14968'
    HTTP_ACCEPT_LANGUAGE = 'de,en-US;q=0.7,en;q=0.3'
    REQUEST_SCHEME = 'https'
    mod_wsgi.version = 
    CONTENT_TYPE = 'application/x-www-form-urlencoded; charset=UTF-8'
    mod_wsgi.application_group = 'mail.netzwerkplan.de|'
    mod_wsgi.script_reloading = '1'
    wsgi.file_wrapper = ''
    CSRF_COOKIE = u'MYse3Evon4oOCYva9RO310OTXNOu0yAB'
    HTTP_ACCEPT_ENCODING = 'gzip, deflate, br'

    Settings:
    Using settings module settings
    SECURE_BROWSER_XSS_FILTER = False
    USE_THOUSAND_SEPARATOR = False
    CSRF_COOKIE_SECURE = False
    LANGUAGE_CODE = 'de-de'
    ROOT_URLCONF = 'urls'
    MANAGERS = 
    BASE_DIR = '/var/www/mailadmin'
    SILENCED_SYSTEM_CHECKS = []
    DEFAULT_CHARSET = 'utf-8'
    SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'
    STATIC_ROOT = '/var/www/mailadmin/sitestatic'
    ALLOWED_HOSTS = ['localhost', 'netzwerkplan01', 'netzwerkplan01.mivitec.net', '.netzwerkplan01.mivitec.net', 'mail.netzwerkplan.mivitec.net', 'mail.netzwerkplan.de', '46.245.177.46', '91.90.144.102', '79.240.219.74', '127.0.0.1']
    MESSAGE_STORAGE = 'django.contrib.messages.storage.fallback.FallbackStorage'
    EMAIL_SUBJECT_PREFIX = '[Django] '
    SERVER_EMAIL = 'root@localhost'
    PASSWORD_MIN_LENGTH = u'********************'
    SECURE_HSTS_SECONDS = 0
    STATICFILES_FINDERS = 
    SESSION_CACHE_ALIAS = 'default'
    SESSION_COOKIE_DOMAIN = None
    SESSION_COOKIE_NAME = 'sessionid'
    TIME_INPUT_FORMATS = 
    SECURE_REDIRECT_EXEMPT = []
    DATABASES = {'default': {'ENGINE': 'django.db.backends.mysql', 'AUTOCOMMIT': True, 'ATOMIC_REQUESTS': True, 'NAME': 'modoboa', 'CONN_MAX_AGE': 0, 'TIME_ZONE': 'UTC', 'PORT': '3306', 'HOST': 'netzwerkplan01.mivitec.net', 'USER': 'modoboa', 'TEST': {'COLLATION': None, 'CHARSET': None, 'NAME': None, 'MIRROR': None}, 'PASSWORD': u'********************', 'OPTIONS': {'init_command': 'SET foreign_key_checks = 0;'}}, 'amavis': {'ENGINE': 'django.db.backends.mysql', 'AUTOCOMMIT': True, 'ATOMIC_REQUESTS': True, 'NAME': 'amavis', 'CONN_MAX_AGE': 0, 'TIME_ZONE': 'UTC', 'PORT': '3306', 'HOST': 'netzwerkplan01.mivitec.net', 'USER': 'amavis', 'TEST': {'COLLATION': None, 'CHARSET': None, 'NAME': None, 'MIRROR': None}, 'PASSWORD': u'********************', 'OPTIONS': {'init_command': 'SET foreign_key_checks = 0;'}}}
    EMAIL_SSL_KEYFILE = u'********************'
    FILE_UPLOAD_DIRECTORY_PERMISSIONS = None
    PASSWORD_COMPLEXITY = u'********************'
    FILE_UPLOAD_PERMISSIONS = None
    FILE_UPLOAD_HANDLERS = 
    DEFAULT_CONTENT_TYPE = 'text/html'
    APPEND_SLASH = True
    LOCALE_PATHS = 
    DATABASE_ROUTERS = ['modoboa_amavis.dbrouter.AmavisRouter']
    DEFAULT_TABLESPACE = ''
    YEAR_MONTH_FORMAT = 'F Y'
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
    CACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
    SESSION_COOKIE_PATH = '/'
    MODOBOA_APPS = 
    SECURE_CONTENT_TYPE_NOSNIFF = False
    MIDDLEWARE_CLASSES = 
    USE_I18N = True
    THOUSAND_SEPARATOR = ','
    SECRET_KEY = u'********************'
    MODOBOA_API_URL = u'********************'
    LANGUAGE_COOKIE_NAME = 'django_language'
    DEFAULT_INDEX_TABLESPACE = ''
    LOGGING_CONFIG = 'logging.config.dictConfig'
    TEMPLATE_LOADERS = 
    FIRST_DAY_OF_WEEK = 0
    WSGI_APPLICATION = 'wsgi.application'
    TEMPLATE_DEBUG = False
    X_FRAME_OPTIONS = 'SAMEORIGIN'
    CSRF_COOKIE_NAME = 'csrftoken'
    FORCE_SCRIPT_NAME = None
    USE_X_FORWARDED_HOST = False
    EMAIL_TIMEOUT = None
    SECURE_SSL_HOST = None
    SIGNING_BACKEND = 'django.core.signing.TimestampSigner'
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_DOMAIN = None
    FILE_CHARSET = 'utf-8'
    DEBUG = True
    LANGUAGE_COOKIE_DOMAIN = None
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    INSTALLED_APPS = 
    LANGUAGES = 
    USE_L10N = False
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    STATICFILES_DIRS = '/usr/local/lib/python2.7/dist-packages/modoboa/bower_components'
    PREPEND_WWW = False
    SECURE_PROXY_SSL_HEADER = None
    LANGUAGE_COOKIE_AGE = None
    SESSION_COOKIE_HTTPONLY = True
    DEBUG_PROPAGATE_EXCEPTIONS = False
    CSRF_COOKIE_AGE = 31449600
    MONTH_DAY_FORMAT = 'F j'
    LOGIN_URL = '/accounts/login/'
    SESSION_EXPIRE_AT_BROWSER_CLOSE = False
    TIME_FORMAT = 'P'
    AUTH_USER_MODEL = 'core.User'
    DATE_INPUT_FORMATS = 
    AUTHENTICATION_BACKENDS = 'modoboa.lib.authbackends.SimpleBackend'
    EMAIL_HOST_PASSWORD = u'********************'
    PASSWORD_RESET_TIMEOUT_DAYS = u'********************'
    SESSION_FILE_PATH = None
    CACHE_MIDDLEWARE_ALIAS = 'default'
    SESSION_SAVE_EVERY_REQUEST = False
    NUMBER_GROUPING = 0
    SESSION_ENGINE = 'django.contrib.sessions.backends.db'
    CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'
    CSRF_COOKIE_PATH = '/'
    LOGIN_REDIRECT_URL = '/accounts/profile/'
    DECIMAL_SEPARATOR = '.'
    IGNORABLE_404_URLS = 
    MIGRATION_MODULES = {}
    TEMPLATE_STRING_IF_INVALID = ''
    LOGOUT_URL = '/accounts/logout/'
    EMAIL_USE_TLS = False
    FIXTURE_DIRS = 
    EMAIL_HOST = 'localhost'
    DATE_FORMAT = 'N j, Y'
    MEDIA_ROOT = '/var/www/mailadmin/media'
    DEFAULT_EXCEPTION_REPORTER_FILTER = 'django.views.debug.SafeExceptionReporterFilter'
    ADMINS = 
    FORMAT_MODULE_PATH = None
    DEFAULT_FROM_EMAIL = 'webmaster@localhost'
    REST_FRAMEWORK = {'DEFAULT_AUTHENTICATION_CLASSES': ('rest_framework.authentication.TokenAuthentication',), 'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',)}
    MEDIA_URL = '/media/'
    DATETIME_FORMAT = 'N j, Y, P'
    TEMPLATE_DIRS = 
    SITE_ID = 1
    DISALLOWED_USER_AGENTS = 
    ALLOWED_INCLUDE_ROOTS = 
    LOGGING = {'loggers': {'modoboa.auth': {'handlers': ['syslog-auth', 'modoboa'], 'propagate': False, 'level': 'INFO'}, 'modoboa.admin': {'handlers': ['modoboa'], 'propagate': False, 'level': 'INFO'}}, 'version': 1, 'formatters': {'syslog': {'format': '%(name)s: %(levelname)s %(message)s'}}, 'handlers': {'syslog-auth': {'formatter': 'syslog', 'class': 'logging.handlers.SysLogHandler', 'facility': 4}, 'modoboa': {'class': 'modoboa.core.loggers.SQLHandler'}}}
    SHORT_DATE_FORMAT = 'm/d/Y'
    TEMPLATES = [{'DIRS': [], 'APP_DIRS': True, 'OPTIONS': {'debug': False, 'context_processors': ['django.template.context_processors.debug', 'django.template.context_processors.request', 'django.contrib.auth.context_processors.auth', 'django.template.context_processors.i18n', 'django.template.context_processors.media', 'django.template.context_processors.static', 'django.template.context_processors.tz', 'django.contrib.messages.context_processors.messages', 'modoboa.core.context_processors.top_notifications']}, 'BACKEND': 'django.template.backends.django.DjangoTemplates'}]
    TEST_RUNNER = 'django.test.runner.DiscoverRunner'
    CACHE_MIDDLEWARE_KEY_PREFIX = u'********************'
    SECURE_SSL_REDIRECT = False
    TIME_ZONE = 'Europe/Berlin'
    FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_USE_SSL = False
    TEMPLATE_CONTEXT_PROCESSORS = 
    SESSION_COOKIE_AGE = 1209600
    SETTINGS_MODULE = 'settings'
    USE_ETAGS = False
    LANGUAGES_BIDI = 
    FILE_UPLOAD_TEMP_DIR = None
    INTERNAL_IPS = 
    STATIC_URL = '/sitestatic/'
    EMAIL_PORT = 25
    USE_TZ = True
    SHORT_DATETIME_FORMAT = 'm/d/Y P'
    TEST_NON_SERIALIZED_APPS = []
    PASSWORD_HASHERS = u'********************'
    ABSOLUTE_URL_OVERRIDES = {}
    LANGUAGE_COOKIE_PATH = '/'
    CACHE_MIDDLEWARE_SECONDS = 600
    EMAIL_SSL_CERTFILE = None
    CSRF_COOKIE_HTTPONLY = False
    DATETIME_INPUT_FORMATS = 
    EMAIL_HOST_USER = ''

    You're seeing this error because you have DEBUG = True in your
    Django settings file. Change that to False, and Django will
    display a standard page generated by the handler for this status code.

**Comment by tonioo** [comment]
What was your previous version ?

**Comment by blendi-93** [comment]
i dont know, sry.

**Comment by tonioo** [comment]
Don't think so. Anyway, it seems you have orphan records in your database... (ie. accounts with no owner)
Have you dropped administrators recently ?

**Comment by blendi-93** [comment]
yes, i'am missing some in table: "admin_domain"

**Comment by blendi-93** [comment]
ok was an upgrade from 1.4.3 to 1.4.4.
can u tell me how i can find the orphan records (mysql db)?

**Comment by blendi-93** [comment]
thx for ur time i found it, some objects have 0 owner... ;)

**Comment by tonioo** [comment]
Great. I was planing to add a management command for that.

**Comment by blendi-93** [comment]
just in case, i had many object_ids with no owner:

    mysql modoboa -e 'SELECT user_id, is_owner FROM core_objectaccess WHERE (object_id = 696 AND content_type_id = 8);'
    +---------+----------+
    | user_id | is_owner |
    +---------+----------+
    |       7 |        0 |
    |       1 |        0 |
    |      21 |        0 |
    +---------+----------+

after setting one user_id as owner it worked.

**Comment by khalidzouagui** [comment]
Hi,

I have installed modoboa 1.9.1, but when i try to add a new account i could not and in the console i receive this error :

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data : jquery.min.js:3:4315

Than you for your time and your help.

**Comment by tonioo** [comment]
@khalidzouagui Please don't comment old and closed issues. Open a new one instead.
