### ISSUE TITLE
Invalid postfix_maps for postgresql

### ISSUE THREAD

**Issue by neutrinus** [tonioo/modoboa#840]
The auto-created postfix maps have a typo. There is `admin_aliasrecipient` instead of `modoboa_admin_aliasrecipient`.

Log:
`Mar 03 12:37:54 Debian-jessie-amd64-netboot postfix/smtpd[11121]: warning: pgsql query failed: fatal error from host localhost: ERROR:  relation "admin_aliasrecipient" does not exist?LINE 1: ... '@' || dom.name FROM admin_mailbox mb INNER JOIN admin_alia...?                                                             ^?
`

/etc/postfix/sql-sender-login-aliases.cf:
`query = SELECT mb.address || '@' || dom.name FROM admin_mailbox mb INNER JOIN admin_aliasrecipient alr ON alr.r_mailbox_id=mb.id INNER JOIN admin_domain dom ON dom.id=mb.domain_id INNER JOIN admin_alias al ON alr.alias_id=al.id WHERE al.enabled AND al.address='%s'`

Relations in DB:
> 
                      List of relations
 Schema |               Name                | Type  |  Owner  
--------+-----------------------------------+-------+---------
 public | admin_alias                       | table | modoboa
 public | admin_domain                      | table | modoboa
 public | admin_domainalias                 | table | modoboa
 public | admin_mailbox                     | table | modoboa
 public | admin_mailboxoperation            | table | modoboa
 public | admin_objectdates                 | table | modoboa
 public | admin_quota                       | table | modoboa
 public | auth_group                        | table | modoboa
 public | auth_group_permissions            | table | modoboa
 public | auth_permission                   | table | modoboa
 public | authtoken_token                   | table | modoboa
 public | core_log                          | table | modoboa
 public | core_objectaccess                 | table | modoboa
 public | core_user                         | table | modoboa
 public | core_user_groups                  | table | modoboa
 public | core_user_user_permissions        | table | modoboa
 public | django_content_type               | table | modoboa
 public | django_migrations                 | table | modoboa
 public | django_session                    | table | modoboa
 public | django_site                       | table | modoboa
 public | lib_parameter                     | table | modoboa
 public | lib_userparameter                 | table | modoboa
 public | limits_limit                      | table | modoboa
 public | limits_limitspool                 | table | modoboa
 public | modoboa_admin_aliasrecipient      | table | modoboa
 public | postfix_relay_domains_relaydomain | table | modoboa
 public | postfix_relay_domains_service     | table | modoboa
 public | reversion_revision                | table | modoboa
 public | reversion_version                 | table | modoboa
(29 rows)

Modoboa installed from pip==1.4.4

This way it has been deployed:
`/home/modoboa/virtualenv/bin/modoboa-admin.py deploy mailadmin --dburl default:postgres://modoboa:modoboa@localhost:5432/maildb --domain localhost`
`/home/modoboa/virtualenv/bin/modoboa-admin.py postfix_maps --dburl postgres://modoboa:modoboa@localhost:5432/maildb /etc/postfix`

**Comment by tonioo** [comment]
Hi, thanks for reporting but this issue is already fixed and will be released soon. (see https://github.com/tonioo/modoboa/commit/0a62b0f9a4cc202da33cd1a6141741585e5f9baf)

**Comment by neutrinus** [comment]
Great, thank you!
