### ISSUE TITLE
the postfix_map command should be run has a standard management command

### ISSUE THREAD

**Issue by gawel** [tonioo/modoboa#851]
No need to generate postfix_maps from the modoboa-admin script.
If you use a standard command, you can get the app context and avoid passing the --db-url parameters and plugins list (you can use settings.DATABASES and settings.MODOBOA_APPS).

You'll also be able to use the orm to generate maps (and avoid typo and other stupid bugs)
For instance, this will generate the correct query for the autoreply plugin:
```
>>> str(Transport.objects.filter(domain='%s').values('method').query)
'SELECT `postfix_autoreply_transport`.`method` FROM `postfix_autoreply_transport` WHERE `postfix_autoreply_transport`.`domain` = %s'
```

**Comment by tonioo** [comment]
Using the ORM is a great idea but I don't agree with the --dburl parameter. It is required since you can use different users/credentials to access the database. For example, one user for modoboa, one user for postfix, etc.

**Comment by gawel** [comment]
Then settings can be used as default

**Comment by tonioo** [comment]
Finally, I think using the ORM to output queries is not possible:
http://stackoverflow.com/questions/8112554/printing-django-queryset-sql-with
