### ISSUE TITLE
Using passwords with $ in them with the modoboa-installer breaks the app

### ISSUE THREAD

**Issue by Znuff** [tonioo/modoboa#853]
Steps to reproduce:

1. Use 'modoboa-installer'
2. Edit installer.cfg and set a password for the database that contains a `$` sign (ie: `sign$sign$SIGN`)
3. Webmail will not function for users (incorrect mysql password)

Further more, if you check the settings.py file, you will see that the password only ended up being `sign` instead of `sign$sign$SIGN`.

**Comment by tonioo** [comment]
This issue is related to the installer, not to modoboa. Could you please move your ticket to the right repository ?
