### ISSUE TITLE
Support for let's encrypt

### ISSUE THREAD

**Issue by tisba37** [tonioo/modoboa#856]
Hello,

It's prossible to add a support for let's encrypt ?

**Comment by hadifarnoud** [comment]
native support would be awesome. Mailinabox did something in that effect. can we re-use some of that code?

**Comment by tonioo** [comment]
Maybe. Once again, don't hesitate to contribute.

**Comment by spinza** [comment]
I'm running with letsencrypt certificates.  Not that difficult to setup.

**Comment by tonioo** [comment]
That's something the installer could do pretty easily.

**Comment by almereyda** [comment]
Before installing, I have been using the following procedure to generate certificates.

---

Create a letsencrypt certificate with https://github.com/lukas2511/letsencrypt.sh and Python SimpleHTTPServer, assuming you work as `root`.

1. Clone into `/root/letsencrypt.sh`: `git clone https://github.com/lukas2511/letsencrypt.sh`
Create the following files within that folder:
    * `domains.txt`
    ```
    FQDN of your box
    ```
    * `config.sh`
    ```
    WELLKNOWN="/root/webroot/.well-known/acme-challenge"
    CONTACT_EMAIL="hostmaster@FQDN"
    ```

2. Create your HTTP webroot `mkdir -p /root/webroot/.well-known/acme-challenge`
    * Run an HTTP server from there `cd /root/webroot && python -m SimpleHTTPServer 80`

---

Then the `installer.cfg` from Modoboa's installer would receive the following lines:

```
[general]
tls_key_file = /root/letsencrypt.sh/certs/FQDN/privkey.pem
tls_cert_file = /root/letsencrypt.sh/certs/FQDN/fullchain.pem
```

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-installer#50
