### ISSUE TITLE
Proposal for update install requirements

### ISSUE THREAD

**Issue by joelfranco** [tonioo/modoboa#858]
I tried to install with Django 1.7 (Debian Jessie) but i had a problem with URLValidator that was fixed with Django 1.8 installed from backports.

Regards

**Comment by tonioo** [comment]
Each version of modoboa requires a specific Django branch. The current one (1.4.x) only works with Django 1.8.x so testing it with Django 1.7 is useless.
BTW, django version provided by major distributions is generally outdated so you should consider to use pip instead.
