### ISSUE TITLE
customizing LDAP auto mailbox creation 

### ISSUE THREAD

**Issue by maziyarpanahi** [tonioo/modoboa#866]
Hello,

Where can I change the setting for auto mailbox creation when the user logs in for the first time instead of /srv/vmail/ldap/uid(ldap usernam) creates the mailbox in /srv/vmail/domainname/firstPartOfEmail(%n)?

I have tried dovecot-ldap.conf.ext and also 10-mail.conf to match them with the default format (../ldap/uid) but I still get the error that says it can't find the user in /srv/vmail/domain/%n

The only place that had an effect in this error was a MySQL config (dovecot-sql.conf.ext). But I still have to change the default LDAP mailbox creation path and parameters. My LDAP userName is not the same as the user's email address.

Details of error:

```
Apr 29 10:45:14 mail dovecot: lmtp(24413, romain.reuillon@iscpif.fr):
Error: user romain.reuillon@iscpif.fr: Initialization failed: Namespace
'': Mail storage autodetection failed with
home=/srv/vmail/iscpif.fr/romain.reuillon
```

When user logs in for the first time it creates the mailbox in /srv/vmail/ldap/uid which is different that its email username without domain.

Many thanks.

**Comment by tonioo** [comment]
Modoboa does not create mailboxes on the filesystem, dovecot does.

If you haven't modified the default configuration, the mailbox path is returned by the SQL query used with user_query in dovecot's configuration (http://modoboa.readthedocs.io/en/latest/integration/imap_and_smtp.html#mysql-users)

In your example, I don't understand where does the 'ldap' part come from...

**Comment by maziyarpanahi** [comment]
Hi tonioo,

Thanks for your reply. Actually the /ldap part was coming from "dovecot-ldap.conf.ext" that I have set manually. I am trying to make this config as same as user_query (I don't want to change sql query). So I need to assign user's email address instead of LDAP username which is different in my LDAP:

```
user_attrs =
uidNumber=uid,gidNumber=gid,homeDirectory=home=/srv/vmail/iscpif.fr/%n,uid=mail=maildir:/srv/vmail/iscpif.fr/%$/Maildir,=namespace/default/separator=%{ldap:mailSeparator}
```

Any chance you know how to get user's LDAP email address? If I can find the parameter for LDAP user's email address instead of %n it will match the user_query.

Many thanks again tonioo

**Comment by maziyarpanahi** [comment]
Ok I have managed to get the email address on both mailBox creation and user_query.

Many thanks again tonioo

**Comment by tonioo** [comment]
Nice! I was replying to you but you were faster than me :)

Could you paste a working example? So others can retrieve it if they need too?

Thanks!
