### ISSUE TITLE
Modoboa trying to install mysql even if i choose the postgresql

### ISSUE THREAD

**Issue by luanfonceca** [tonioo/modoboa#874]
Hi folks, i am trying to use the `modoboa-installer`, comment the `engine` option on the .cfg file:
```
engine = postgres
#engine = mysql
```

But when i try to install it keeps asking for the mysql password, I need to compile something else in order to use the postgresql?

Thanks in advance

**Comment by tonioo** [comment]
No, it shoud be enough. I've just tried a fresh install with postgres enabled and it works as expected... Are you installing a new system or an existing one ?

**Comment by tonioo** [comment]
@luanfonceca By the way, this issue is related to the installer, not to modoboa. Could you please move it to the right repository ? (https://github.com/modoboa/modoboa-installer)
