### ISSUE TITLE
Modoboa webmail can't delete mail with attachments

### ISSUE THREAD

**Issue by pavinjosdev** [tonioo/modoboa#880]
Deleting email with attachments in Modoboa webmail does not work. The email still remains in the inbox folder and the response is [object Object].

**Comment by tonioo** [comment]
Could you please move this issue in the appropriate repository (https://github.com/modoboa/modoboa-webmail/). Then, set DEBUG to True inside settings.py and open a javascript console, you should see the real error message.
Thank you
