### ISSUE TITLE
Autoreply showing swagger problem in log

### ISSUE THREAD

**Issue by benfante** [tonioo/modoboa#881]
Hi,
when an e-mail is relayed through autoreply I see following message in the log (and the autoreply doesn't work, of course). Any Idea? I'm running Modoboa 1.5.3, with Postfix autoreply plugin 1.1.6.

`May 19 10:03:45 mail postfix/pipe[3323]: 282432069B9: to=<email@mydomain@autoreply.mydomain>, orig_to=<email@mydomain>, relay=autoreply, delay=5.3, delays=0.13/0.03/0/5.1, dsn=5.3.0, status=bounced (Command died with status 1: "/opt/environments/modoboa/bin/python". Command output: Traceback (most recent call last):   File "/var/www/modoboa_benfante/manage.py", line 10, in <module>     execute_from_command_line(sys.argv)   File "/opt/environments/modoboa/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line     utility.execute()   File "/opt/environments/modoboa/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute     django.setup()   File "/opt/environments/modoboa/lib/python2.7/site-packages/django/__init__.py", line 18, in setup     apps.populate(settings.INSTALLED_APPS)   File "/opt/environments/modoboa/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate     app_config = AppConfig.create(entry)   File "/opt/environments/modoboa/lib/python2.7/site-packages/django/apps/config.py", line 86, in create     module = import_module(entry)   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module     __import__(name) ImportError: No module named rest_framework_swagger )`

**Comment by tonioo** [comment]
It looks like your virtual environment is not fully functional because it tries to locate the missing requirement inside the default python installation (/usr/lib/python2.7).
I suggest you recreate your virtualenv.

**Comment by tonioo** [comment]
@benfante ping

**Comment by benfante** [comment]
Hi,
sorry for the late.

I spent some hours trying to solve this problem, but...no results. The error is still there.

I recreated the virtual environment environment and also reinstalled modoboa, but nothing changed.

I also installed the package django-rest-swagger in the root environment, and still nothing changed.

Can I try anything else?

**Comment by benfante** [comment]
Sorry, I was updating the wrong virtual environment. Now it's ok.

Thank you for your support.
