### ISSUE TITLE
Webmail: Internal error with spanish locale

### ISSUE THREAD

**Issue by rmontagud** [tonioo/modoboa#882]
Hi,

During my tests I see "Internal error" messages when I click on empty folders (such as drafts) but only with the Spanish locale (tried English and Italian)

I'm not afraid of sending a patch but I'd like to now which files should I edit to update Spanish locale

**Comment by tonioo** [comment]
Hi, thanks for reporting this but this is not the appropriate repository.
Could you please move your issue to https://github.com/modoboa/modoboa-webmail ?

**Comment by rmontagud** [comment]
Moved
