### ISSUE TITLE
webmail: internal error when user's language is not English

### ISSUE THREAD

**Issue by cptMikky** [tonioo/modoboa#885]
When a user changes his lang to non-english (Czech - cs in my case), webmail gives a small "Internal error" (in Czech) bubble on top of the page without any further explanation even with Debug enabled. Server logs (uwsgi logs) only give the request URL and a mention about a 500 error, nothing specific. I was unable to produce any logs or messages beyond this and I only came up with the relation to Language settings via trial-and-error.

So two issues here really: 1) a hard 500 server error on language change and 2) inconclusive error message

Debian Jessie, ngnix 1.10.1 (http2), uwsgi (2.0.7), mysql (Percona 5.7.11), Python 2.7.9, modoboa installed in virtualenv via pip install method.

Modoboa v. 1.5.3, webmail v. 1.0.4

As usual, I'm happy to cooperate in any way I can, being it debugging (if I'm told what to do) or giving any additional information.

**Comment by tonioo** [comment]
@cptMikky Since the webmail mostly use async requests to update the page, errors are not showed unless you open a javascript console.

**Comment by cptMikky** [comment]
Now I see this in js console:

    jquery.min.js:5 GET https://<mydomain>/webmail/?action=listmailbox&mbox=Sent&reset_page=true&_=1234567890123 500 (Internal Server Error)
    send	@	jquery.min.js:5
    ajax	@	jquery.min.js:5 
    check	@	history.js:272
    i	@	jquery.min.js:3

Same for all folders. I was able to create a new folder, it even appears in the folder list but I still can't switch to it - same error.

**Comment by tonioo** [comment]
Are you sure you're looking at the right tab ? What tool do you use ? With DEBUG = True, you should see a complete python stacktrace.

**Comment by cptMikky** [comment]
What tab are you referring to? I do have DEBUG = True. I use Chromium's integrated JS console. The screen looks like this: https://oc.ghoul.cz/index.php/s/Lzf8FcaBzyra3jO

**Comment by tonioo** [comment]
Is it the console launched when you hit the F12 key ?
Could you try to display server response instead of the javascript error please ?

**Comment by cptMikky** [comment]
Of course, my mistake, I thought you wanted the javascript errors.

Server response is http://pastebin.com/AtwXYfJ1

**Comment by tonioo** [comment]
Ok, so it corresponds to the issue I fixed yesterday.
https://github.com/modoboa/modoboa-webmail/issues/37
