### ISSUE TITLE
Display RSS feed from modoboa's official blog

### ISSUE THREAD

**Issue by tonioo** [tonioo/modoboa#891]
Display the RSS feed containing latest news from Modoboa's official blog somewhere, maybe a new dashboard ?
Feature must be activated/deactivated from global settings.

**Comment by almereyda** [comment]
That's actually a good idea and resembles what ISPConfig does.

**Comment by figassis** [comment]
Is it possible to support custom RSS feeds for non SuperUsers? This way SuperUsers could show their own feeds to other DomainAdmins and resellers.

Something like the code below could be added to modoboa/core/views/dashboard.py

`if not self.request.user.is_superuser:
            url = "https://medium.com/feed/bantumail"
        posts = feedparser.parse(
            url.format(lang))`

**Comment by tonioo** [comment]
Indeed, it is an interesting feature. Could you please create a new
issue about this?

**Comment by figassis** [comment]
Done, see issue #1047
