### ISSUE TITLE
100% cpu on logout

### ISSUE THREAD

**Issue by romainreuillon** [tonioo/modoboa#899]
Dear Devs,

I got a 100% CPU usage of uwgi on modoboa logout (as soon as I click on the logout link uwsgi gets to 100%): ``` 4729 modoboa   20   0  301960  89708  14144 R  99,7  2,2   0:08.70 uwsgi```

Any idea where it could come from ?

I am using the modoboa version: 1.5.3 and ldap authentication backend.

Romain

**Comment by romainreuillon** [comment]
I forgot to tell that the 100% uwsgi process never ends...

**Comment by tonioo** [comment]
Looks like there is an infinite loop somewhere... Have you tried using a local account ? (ie non LDAP)

**Comment by romainreuillon** [comment]
I just tested it and it works fine with non-ldap users (admin and a test user).

**Comment by ogg1980** [comment]
I have the same problem. Not using LDAP.

SimpleUsers results in 100% cpu usage by a uwsgi process and they never get logged out.
Also DomainAdmins.

SuperAdmins can log in / out just fine without any cpu spikes.

Modoboa version 1.5.3.

**Comment by tonioo** [comment]
The issue reported by @ogg1980 was due to a wrong filesystem configuration. (emails were not stored into the location used by dovecot)
@romainreuillon Could you try to logout with such a user and check mail logs to see if there is anything interesting inside?

**Comment by romainreuillon** [comment]
Great ! Next time I plan to work on this is at the end of September. I'll give it a try then.

**Comment by hardikvala** [comment]
Hi is this bounty still open.
I think I can help you on this

**Comment by tonioo** [comment]
@hardikvala Thank you but the bounty is closed.

@romainreuillon I close the issue for now (required by bountysource). Do not hesitate to reopen it when you'll do your tests.
