### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by adeel** [tonioo/modoboa#906]
I just installed Modoboa on Debian 8.  Everything appeared to go smoothly, I signed in and created a new domain and a user on that domain.  After logging into the webmail for that user, I got a blank page with the following error message in a red box:

    Error: ['[AUTHENTICATIONFAILED] Authentication failed.']

Here is a paste of `/var/log/mail.log`: https://gist.github.com/adeel/1127c8d9bd8e129312b2ed9e5f44ab36

Let me know if there is anything else I can provide.  For what it's worth, the issue appears similar to [this](https://github.com/tonioo/modoboa/issues/769).

**Comment by tonioo** [comment]
Have you installed modoboa manually or using the installer ?

**Comment by adeel** [comment]
I used the installer.

**Comment by tonioo** [comment]
What is the user you're connected with? What's is role? Does it have a regular mailbox?

**Comment by adeel** [comment]
Ok, I believe I found the problem.  I was creating the user with the username "adeel".  When I create it with "adeel@mydomain.com", it works fine.

**Comment by mlzummo** [comment]
@tonioo I am getting this error as well now with a freshinstall as of this morning

**Comment by tonioo** [comment]
@mlzummo can you provide more information?

**Comment by mlzummo** [comment]
@tonioo do you have an IM client we can chat on for a sec (gchat)?

**Comment by mlzummo** [comment]
also cant send mail (so im guessing this is a hard auth issue)

**Comment by tonioo** [comment]
XMPP (tonio@ngyn.org)

**Comment by mlzummo** [comment]
@tonioo roundcubemail login is fine (not sure how to debug the modoboa-webmail for this)
