### ISSUE TITLE
DNSBL report incorrect

### ISSUE THREAD

**Issue by dugite-code** [tonioo/modoboa#921]
Just upgraded to 1.6.0 from 1.5.1

added new crontab entries then manually ran `/srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py modo check_mx` as vmail with no errors. All DNSBL show as listed, my manual checks (where possible) show no listings. using dnsbl.info only dnsbl-3.uceprotect.net shows listed due to my server being a digital ocean droplet (minor issue).

I am unsure how to debug this issue. I have set debugging to True in settings.py is there a log file I can check?

**Comment by tonioo** [comment]
Could you paste some screenshots please ?

**Comment by dugite-code** [comment]
Is this what you're after? It's every DNSBL provider from the `constants.py` file.
![domains](https://cloud.githubusercontent.com/assets/12742064/18734841/ce7df99c-80aa-11e6-852a-c2458da8ba67.png)

**Comment by tonioo** [comment]
Have you checked that the MX record found by Modoboa is the right one ?

**Comment by dugite-code** [comment]
MX record is correct with correct IP address. I also have reverse DNS lookup working.

* Only thing I've added to my blank Ubuntu install is UFW but the default behavior for outgoing traffic is allow

**Comment by henne-** [comment]
I can confirm this behaviour on a fresh installation of Ubuntu 16.04 without ufw.

**Comment by tonioo** [comment]
Guys, would be easier to debug if one of you could give me a domain name that fails. Do not hesitate to send me a private message.

**Comment by henne-** [comment]
Try smells.sexy :)

**Comment by tonioo** [comment]
Thank you. I'm sorry but I fail to reproduce your issue... I see your domain as not blacklisted. Where is your server ? Is there any DNS limitation or something similar which could cause this ?

**Comment by henne-** [comment]
Not that i'm aware of it..

When I manually try to query the ip, it shows the following

```
root@mail:/ dig 66.30.172.31.bl.spamcop.net

; <<>> DiG 9.10.3-P4-Ubuntu <<>> 66.30.172.31.bl.spamcop.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 58068
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;66.30.172.31.bl.spamcop.net.	IN	A

;; AUTHORITY SECTION:
bl.spamcop.net.		0	IN	SOA	bl.spamcop.net. hostmaster.admin.spamcop.net. 1475602051 3600 1800 3600 0

;; Query time: 32 msec
;; SERVER: 195.182.2.2#53(195.182.2.2)
;; WHEN: Tue Oct 04 19:28:54 CEST 2016
;; MSG SIZE  rcvd: 109
```

Which is fine, if i'm not mistaking... I will have a look at the code tonight..

**Comment by tonioo** [comment]
Yes, it is fine. Which user runs the management command ?

**Comment by tonioo** [comment]
@dugite-code Have you tried to run the command as root ?

**Comment by henne-** [comment]
Found the error! 
I had set a DNS Search Domain in my /etc/resolv.conf.
socket.gethostbyname always returned the IP address of my Webserver. The Searchdomain also is the hostname of my Webserver, so it seems, when socket.gethostbyname cannot resolve the Hostname, it takes the IP of the searchdomain.

Removing the Searchdomain fixed this.

**Comment by dugite-code** [comment]
@tonioo just gave it a shot running as root with no change

@henne- Unfortunately I don't have a dns search domain defined.

**Comment by awein** [comment]
This issue is caused by a missing domain entry in the `resolv.conf` file. An empty value might still cause issues in case your hostname is a subdomain (like mail.example.com).

@tonioo I suggest to append a `.` at the end of the hostname (which will force the name to be the full DNS name instead of a relative one)
(e.g. `bl.spamcop.net.` instead of `bl.spamcop.net`)

The workaround until then is to add the following line to the `/etc/resolv.conf`:
```
domain .
```

**Comment by dugite-code** [comment]
I can confirm adding `domain .` to my `/etc/resolv.conf` fixed this issue for me. Thanks @awein

**Comment by dugite-code** [comment]
Incidentally dnsbl.njabl.org show's listed but according to [dnsbl.info](http://www.dnsbl.info/dnsbl-njabl-org.php) and [vamsoft.com](http://vamsoft.com/support/docs/knowledge-base/njabl-shutdown) njabl.org has been shutdown and should probably be removed.

**Comment by csmk** [comment]
Just my 2 cents.

Are you guys using some public DNS resolver? Because many DNSBL services are known to block or limit the queries from such resolvers.

I use my own DNS resolver (Unbound), so I only have `nameserver 127.0.0.1` in resolv.conf file. And everything is fine here with many domains.

**Comment by dugite-code** [comment]
@csmk that's interesting to know. I'm using the google name servers because I honestly didn't think of changing the default settings.

My Digital Ocean droplet built using their default `Ubuntu 16.04.1 x64` image `/etc/resolv.conf`
```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 8.8.8.8
nameserver 8.8.4.4
```

**Comment by tonioo** [comment]
@awein Thank you! I'll update the code.

**Comment by gabsoftware** [comment]
> Are you guys using some public DNS resolver? Because many DNSBL services are known to block or limit the queries from such resolvers.
> 
> I use my own DNS resolver (Unbound), so I only have `nameserver 127.0.0.1` in resolv.conf file. And everything is fine here with many domains.
> 
> Just my 2 cents.

That was it! zen.spamhaus.org refused DNS queries with public DNS resolvers, even the ECS enabled 9.9.9.11... Which should have worked according to their usage terms https://www.spamhaus.org/organization/dnsblusage/ .
