### ISSUE TITLE
aliases broken

### ISSUE THREAD

**Issue by gawel** [tonioo/modoboa#922]
After migrating to 1.6, the admin_alias.expire_at values is NULL but the query contained in sql-aliases.cf require a date:

```
query = SELECT alr.address FROM modoboa_admin_aliasrecipient AS alr INNER JOIN admin_alias AS al ON alr.alias_id=al.id WHERE al.enabled=1 AND al.address='%s' AND al.expire_at>now()
```

Did I missed a step ? If not you should also take care of NULL values in the query.

**Comment by dugite-code** [comment]
I can also confirm this behavior. Aliases without an expiry date don't work and results in:

```
<test@example.com>: host mail.example.com[private/dovecot-lmtp] said: 550
    5.1.1 <test@example.com> User doesn't exist: test@example.com (in reply
    to RCPT TO command)
```

Current work around is just adding a really far away date like `2020-12-25 16:52:41`

**Comment by tonioo** [comment]
Yes, this is a SQL query issue. You can fix it like this (sql-aliases.cf):
```sql
AND (al.expire_at IS NULL OR al.expire_at>now())
```

**Comment by tonioo** [comment]
I'll post a fix soon.
