### ISSUE TITLE
Missing reference to sql-sender-login-mailboxes-extra.cf restricts using extra user sender addresses

### ISSUE THREAD

**Issue by tkosars** [tonioo/modoboa#926]
I have a special account for relaying messages using various email addresses. Added the required Sender addresses but I kept getting the following error in mail.log:

`553 5.7.1 <example.adress@domain.com>: Sender address rejected: not owned by user specialaccount@modoboa-host;`

Started lurking in /etc/postfix folder and found out that modoba already has a mapping for this case, but there is no reference in main.cf:

`mysql:/etc/postfix/sql-sender-login-mailboxes-extra.cf`

Added this mapping to smtpd_sender_login_maps and the Sender address is being accepted for relaying now:

`smtpd_sender_login_maps =
        mysql:/etc/postfix/sql-sender-login-mailboxes.cf
        mysql:/etc/postfix/sql-sender-login-aliases.cf
        mysql:/etc/postfix/sql-sender-login-mailboxes-extra.cf`

Please let me know if I'm thinking it right.

**Comment by tonioo** [comment]
You're right, I forgot to mention in the documentation and in the upgrade procedure. I'll fix it asap. Thanks for the feedback!
