### ISSUE TITLE
Error while creating an account: "dictionary changed size during iteration"

### ISSUE THREAD

**Issue by gawel** [tonioo/modoboa#933]
Got this error (don't have more context, I'm not the end user)

```
File "/var/www/modoboa/vtenv/local/lib/python2.7/site-packages/modoboa/admin/forms/account.py" in clean
           |  282.         for name, value in cleaned_data.iteritems():
           |
           |Exception Type: RuntimeError at /manager/admin/accounts/new/
           |Exception Value: dictionary changed size during iteration
```

I guess this can be improve by using:
 ```for name, value in list(cleaned_data.items()): ``` here:
https://github.com/tonioo/modoboa/blob/master/modoboa/admin/forms/account.py#L295

Also ```.iteritems()``` do not exist in python3

**Comment by tonioo** [comment]
I don't understand the difference between your stacktrace talking about line 282 and you talking about line 295...
What version are you using ?

**Comment by gawel** [comment]
I'm using the latest stable release https://github.com/tonioo/modoboa/blob/1.6.0/modoboa/admin/forms/account.py#L282

**Comment by tonioo** [comment]
Ok. How can I reproduce this issue ? What kind of user are you created ? What is your python version ? 
(atm, I fail to reproduce it)

**Comment by gawel** [comment]
"don't have more context, I'm not the end user"

I only had the traceback in error mails. Don't have any other clue. But it means it's happening. I got ~6 mails before the customer finally succeeded to create the account.

We are using python 2.7.9. Django 1.9.9

Here are (almost) the data sent:

```
username = u'nathalie@domain.fr'
password1 = u'xxxx'
first_name = u'Nath'
last_name = u'Xxxx'
target = u'next'
is_active = u'on'
password2 = u'xxxx'
senderaddress = u'xx@other.fr'
stepid = u'step2'
role = u''
quota_act = u'on'
csrfmiddlewaretoken = u'ZzI3nzwI'
email = u'nathalie@domain.fr'
aliases = u'xx@other.fr'
```

Nothing weird here...
