### ISSUE TITLE
Help with upgrading Modoboa on Debian

### ISSUE THREAD

**Issue by abmiller99** [tonioo/modoboa#939]
I'm not experienced with Python, Postgre.

I have Modoboa 1.6.0 running on my mailserver . My install method was the 'easy', Python script method:

`$ git clone https://github.com/modoboa/modoboa-installer`
`$ cd modoboa-installer`
`$ sudo ./run.py <mail server hostname>`

I have read the [docs](http://modoboa.readthedocs.io/en/latest/getting_started/upgrade.html) describing how to update modoboa with new version, but I'm stuck on the `deploy` instructions.

Example from the docs:
`$ modoboa-admin.py deploy modoboa_example --collectstatic [--dburl default:database-url] [--extensions extensions]`

What do I replace `modoboa_example` with?

How do I determine my `--dburl` values?

Any help is very  appreciated!

**Comment by tonioo** [comment]
Hi,
in your case, the easiest way to upgrade is the following one:
```bash
> su - modoboa
> source env/bin/activate
> cd instance
> python manage.py migrate
> python manage.py collectstatic
```
Then, just follow the 1.6.1 instructions as described in the weblog post.

**Comment by abmiller99** [comment]
Here is the result of the commands you provided:

`$ su - modoboa`

`$ source env/bin/activate`
`-su: 1: source: not found`

`$ cd instance`

`$ python manage.py migrate`
`Traceback (most recent call last):`
`File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)`
`File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.p                                         y", line 353, in execute_from_command_line`
`utility.execute()`
`File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.p                                         y", line 302, in execute`
`settings.INSTALLED_APPS`
`File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 55                                         , in __getattr__`
`self._setup(name)`
`File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 43                                         , in _setup`
`self._wrapped = Settings(settings_module)`
`File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 99                                         , in __init__`
`mod = importlib.import_module(self.SETTINGS_MODULE)`
`File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)`
`File "/srv/modoboa/instance/instance/settings.py", line 250, in <module>
    from modoboa_amavis.settings import *`
`ImportError: No module named modoboa_amavis.settings`

`$ python manage.py collectstatic`
`Traceback (most recent call last):`
` File "manage.py", line 10, in <module>`
    `execute_from_command_line(sys.argv)`
`File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.p                                         y", line 353, in execute_from_command_line`
    `utility.execute()`
  `File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.p                                         y", line 302, in execute`
    `settings.INSTALLED_APPS`
  `File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 55                                         , in __getattr__`
    `self._setup(name)`
  `File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 43                                         , in _setup`
    `self._wrapped = Settings(settings_module)`
  `File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 99                                         , in __init__`
    `mod = importlib.import_module(self.SETTINGS_MODULE)`
  `File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)`
  `File "/srv/modoboa/instance/instance/settings.py", line 250, in <module>
    from modoboa_amavis.settings import *`
`ImportError: No module named modoboa_amavis.settings`

Any insights?

My environment: Debian 8 (Jessie)

![screen shot 2016-10-13 at 14 48 06](https://cloud.githubusercontent.com/assets/2399854/19351530/186281fe-9154-11e6-96d0-b9234703f54b.png)

**Comment by tonioo** [comment]
Looks like the shell of the modoboa user is not bash. Please retry like this:
```bash
> su - modoboa
> bash
> source env/bin/activate
> cd instance
> python manage.py migrate
> python manage.py collectstatic
```

**Comment by tonioo** [comment]
@abmiller99 Is it better ?

**Comment by abmiller99** [comment]
I semi-bricked my install and had to restore from backup.

Now I'll try again using your commands with my working v1.6.0:

`root@mail ~ $ su - modoboa`

`$ bash`

`modoboa@mail:~$ source env/bin/activate`

`(env)modoboa@mail:~$ cd instance`

`(env)modoboa@mail:~/instance$ python manage.py migrate`

`Operations to perform:`
` Apply all migrations: authtoken, core, limits, lib, sessions, admin, modoboa_postfix_autoreply, auth, sites, reversion, contenttypes, modoboa_amavis, relaydomains`
`Running migrations:`
` No migrations to apply.`
` Your models have changes that are not yet reflected in a migration, and so won't be applied.`
` Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.`

I'll pause here for your input..

**Comment by tonioo** [comment]
This is fine. You can continue.
Le 13 oct. 2016 5:59 PM, Andrew Miller <notifications@github.com> a écrit :I semi-bricked my install and had to restore from backup.

Now I'll try again using your commands with my working v1.6.0:

root@mail ~ $ su - modoboa

$ bash

modoboa@mail:~$ source env/bin/activate

(env)modoboa@mail:~$ cd instance

(env)modoboa@mail:~/instance$ python manage.py migrate

Operations to perform:
Apply all migrations: authtoken, core, limits, lib, sessions, admin, modoboa_postfix_autoreply, auth, sites, reversion, contenttypes, modoboa_amavis, relaydomains
Running migrations:
No migrations to apply.
Your models have changes that are not yet reflected in a migration, and so won't be applied.
Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

I'll pause here for your input..

**Comment by abmiller99** [comment]
`(env)modoboa@mail:~/instance$ python manage.py makemigrations`
`Migrations for 'admin':`
`  0005_auto_20161013_1808.py:`
`    - Alter field description on alias`
`    - Alter field expire_at on alias`
`Migrations for 'core':`
`  0009_auto_20161013_1808.py:`
`    - Alter field first_name on user`
`    - Alter field language on user`
`    - Alter field last_name on user`

`(env)modoboa@mail:~/instance$ python manage.py migrate`
`Operations to perform:`
`  Apply all migrations: authtoken, core, limits, lib, sessions, admin, modoboa_postfix_autoreply, auth, sites, reversion, contenttypes, modoboa_amavis, relaydomains`
`Running migrations:`
`  Rendering model states... DONE`
`  Applying admin.0005_auto_20161013_1808... OK`
`  Applying core.0009_auto_20161013_1808... OK`

Now what? Restart uWSGI?

**Comment by tonioo** [comment]
Sorry, I meant you can continue with the procedure I gave you.

Run the following commands please:
```bash
> python manage.py migrate core 0008
> python manage.py migrate admin 0004
```
You should also remove the two migration files you created by running the "makemigrations" command. (you should find them in /srv/modoboa/env/lib/python2.7/site-packages/modoboa/core/migrations/0009_auto_20161013_1808.py and srv/modoboa/env/lib/python2.7/site-packages/modoboa/admin/migrations/0005_auto_20161013_1808.py)

Then, continue with the collectstatic command of this original procedure and finally, reload uwsgi.

**Comment by abmiller99** [comment]
OK -

`(env)modoboa@mail:~/instance$ python manage.py migrate core 0008`
`Operations to perform:`
`  Target specific migration: 0008_localconfig, from core`
`Running migrations:`
`  Rendering model states... DONE`
`  Unapplying core.0009_auto_20161013_1808... OK`

`(env)modoboa@mail:~/instance$ python manage.py migrate admin 0004`
`Operations to perform:`
`  Target specific migration: 0004_auto_20160914_0907, from admin`
`Running migrations:`
`  Rendering model states... DONE`
`  Unapplying admin.0005_auto_20161013_1808... OK`

> You should also remove the two migration files you created by running the "makemigrations" command. (you should find them in /srv/modoboa/env/lib/python2.7/site-packages/modoboa/core/migrations/0009_auto_20161013_1808.py and srv/modoboa/env/lib/python2.7/site-packages/modoboa/admin/migrations/0005_auto_20161013_1808.py)
done.

`(env)modoboa@mail:~/instance$ python manage.py collectstatic`

`You have requested to collect static files at the destination location as specified in your settings:`

`    /srv/modoboa/instance/sitestatic`

`This will overwrite existing files!`
`Are you sure you want to do this?`

`Type 'yes' to continue, or 'no' to cancel: yes`

`0 static files copied to '/srv/modoboa/instance/sitestatic', 1455 unmodified.`

`root@mail ~ $ service uwsgi reload`

I'm guessing that the report of `0 static files copied` means that I didn't do something?

Checked install is still Modoboa 1.6.0.

**Comment by tonioo** [comment]
```0 static files copied``` only means there was nothing to update and it is normal with this version.

Have you tried to restart uwsgi ?

**Comment by abmiller99** [comment]
> Have you tried to restart uwsgi ?

Yes

Going back to the beginning of the update procedure - would it be correct to run the python install script first before proceeding with the commands you provided? For example:

Step 1) 
```
$ git clone https://github.com/modoboa/modoboa-installer
$ cd modoboa-installer
$ sudo ./run.py <mail server hostname>
```

Step 2)
```
> su - modoboa
> bash
> source env/bin/activate
> cd instance
> python manage.py migrate
> python manage.py collectstatic
```

Step3)
`$ service uwsgi reload`

**Comment by tonioo** [comment]
Yes, it would be correct.

**Comment by abmiller99** [comment]
Still at 1.6.0

I also tried using pip install method:

pip install modoboa==1.6.1

Got lots of these:
` Could not find .egg-info directory in install record for gevent==1.1.1 (from modoboa==1.6.1)`
`Could not find .egg-info directory in install record for dnspython==1.12.0 (from modoboa==1.6.1)`
`Could not find .egg-info directory in install record for jsonfield==1.0.3 (from modoboa==1.6.1)`
`Could not find .egg-info directory in install record for py-dateutil==2.2 (from modoboa==1.6.1)`
`Could not find .egg-info directory in install record for feedparser==5.2.1 (from modoboa==1.6.1)`
`Could not find .egg-info directory in install record for cffi>=1.1 (from bcrypt==2.0.0->modoboa==1.6.1)`
`Could not find .egg-info directory in install record for LEPL (from rfc6266->modoboa==1.6.1)`
`Could not find .egg-info directory in install record for greenlet>=0.4.9 (from gevent==1.1.1->modoboa==1.6.1)`
`Could not find .egg-info directory in install record for pycparser (from cffi>=1.1->bcrypt==2.0.0->modoboa==1.6.1)`

and quite a few warnings like:
```
 no previously-included directories found matching '*/__pycache__'
    warning: no previously-included files matching '*.o' found anywhere in distribution
    no previously-included directories found matching 'doc/_build'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '.coverage' found under directory 'greentest'
    no previously-included directories found matching 'greentest/htmlcov'
    warning: no previously-included files matching 'ares_build.h.orig' found under directory 'c-ares'
    warning: no previously-included files matching '_corecffi.c' found under directory 'gevent'
    warning: no previously-included files found matching 'Makefile'
```

**Comment by tonioo** [comment]
Please make sure to run commands as ```modoboa``` user and that the virtualenv is properly loaded (```source ~/env/bin/activate```).
Then, can you run the following command please:
```pip list | grep modoboa```

**Comment by abmiller99** [comment]
`(env)modoboa@mail:~$ pip list | grep modoboa`
```
modoboa (1.6.0)
modoboa-admin (1.1.2)
modoboa-amavis (1.0.9)
modoboa-pdfcredentials (1.0.3)
modoboa-postfix-autoreply (1.1.6)
modoboa-sievefilters (1.0.6)
modoboa-stats (1.0.8)
modoboa-webmail (1.0.4)
```

**Comment by tonioo** [comment]
Ok. Please try the following now:
```bash
> pip install -U pip
> pip uninstall modoboa-admin
> pip install modoboa==1.6.1
```

**Comment by abmiller99** [comment]
`(env)modoboa@mail:~$ pip uninstall modoboa-admin`
...
`Successfully uninstalled modoboa-admin-1.1.2`

`(env)modoboa@mail:~$ pip install modoboa==1.6.1`
..
`Successfully installed modoboa-1.6.1`

**Comment by tonioo** [comment]
Looks better !
Now, upgrade map files and postfix configuration (as described in the blog post) and reload uwsgi and you'll be done.

**Comment by abmiller99** [comment]
`python manage.py generate_postfix_maps --destdir <path> --force-overwrite`

How I do know my `<path>`? Is it /etc/postfix?

**Comment by abmiller99** [comment]
OK:
`<path>` = `/etc/postfix/`
`<driver>` = `pgsql`

Ran this:
`(env)modoboa@mail:~$ cd instance`
`(env)modoboa@mail:~/instance$ python manage.py generate_postfix_maps --destdir /etc/postfix`
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/management/commands/generate_postfix_maps.py", line 157, in handle
    force_overwrite=options["force_overwrite"])
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/management/commands/generate_postfix_maps.py", line 125, in __render_map_file
    mapcontent = utils.parse_map_file(fullpath)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/utils.py", line 21, in parse_map_file
    name, value = line.split("=", 1)
ValueError: need more than 1 value to unpack
```

Then checked postfix main.cf for:
```
smtpd_sender_login_maps =
    <driver>:<path>/sql-sender-login-mailboxes.cf
    <driver>:<path>/sql-sender-login-aliases.cf
    <driver>:<path>/sql-sender-login-mailboxes-extra.cf
```
(it was already there)

Then 
`$ service postfix reload`

Then 
`$ service uwsgi reload `

![screen shot 2016-10-14 at 13 28 13](https://cloud.githubusercontent.com/assets/2399854/19388321/e4fd9330-9216-11e6-84c7-20e32037de30.png)

**Comment by tonioo** [comment]
The ```generate_postfix_maps``` command must be ran as root (because it is writing to /etc/postfix) and you forgot the ```--force-overwrite``` option.

About the internal error, you need to upgrade extensions too.

**Comment by abmiller99** [comment]
OK,

`root@mail /srv/modoboa/instance $ python manage.py generate_postfix_maps --destdir /etc/postfix --force-overwrite`

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 302, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/modoboa/instance/instance/settings.py", line 250, in <module>
    from modoboa_amavis.settings import *
ImportError: No module named modoboa_amavis.settings
```

`root@mail /srv/modoboa/instance :( $ service uwsgi reload`
`root@mail /srv/modoboa/instance $ service postfix reload`

![screen shot 2016-10-14 at 13 28 13](https://cloud.githubusercontent.com/assets/2399854/19389038/438da93c-921a-11e6-83b5-1cb703746c20.png)

**Comment by tonioo** [comment]
Run the ```generate_postfix_maps``` command as follows:
```bash
> /srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py generate_postfix_maps --destdir /etc/postfix --force-overwrite
```
To upgrade extensions, run (**as modoboa and with virtualenv loaded**):
```bash
> pip install modoboa-amavis==1.0.10
> pip install modoboa-stats==1.0.9
> pip install modoboa-postfix-autoreply==1.1.7
```
And reload uwsgi.

**Comment by abmiller99** [comment]
OK that all worked 100% - tremendous job guiding me. 

![screen shot 2016-10-14 at 14 44 45](https://cloud.githubusercontent.com/assets/2399854/19389717/e5b4bbb8-921c-11e6-9a69-fd8c161932a6.png)

**Comment by md678685** [comment]
I've been following this as it happened - I encountered very similar problems to this and this just helped me too. Thanks @tonioo

**Comment by tonioo** [comment]
The documentation has been refactored and now includes clear upgrade instructions (I hope so).
http://modoboa.readthedocs.io/en/latest/upgrade.html
