### ISSUE TITLE
Let's Encrypt Support

### ISSUE THREAD

**Issue by mwaigichuhi** [tonioo/modoboa#949]
Hi,

Any plans to build in let's encrypt support. I got a nice article after struggling a bit with this a few weeks ago.

Please see http://justrocketscience.com/post/setup-email-server. However it would really be nice to have this built-in as it's becoming main stream i.e.available on install by default and then optionally turn it off if not desired.

When I had a LE certificate my app mails failed to go out when I tried using SSL/TLS with ports 465 and 587 using STARTTLS. I could not find any help online or in the official docs.

Please advice on this if you can and your work is much appreciated.

Happy User,

Ken.

**Comment by tonioo** [comment]
Hi,
I was just about to make an announcement about this: https://github.com/modoboa/modoboa-installer/pull/60 ;-)

About your issue, some logs would be appreciated.

**Comment by tonioo** [comment]
@mwaigichuhi ping

**Comment by JayBeRayBearGun** [comment]
Don't you have trouble with Android mailclient accepting this certificate? (I do sadly)

**Comment by tonioo** [comment]
No, I use such a certificate on my personal platform and it works fine. What's your issue?

**Comment by JayBeRayBearGun** [comment]
@tonioo I discovered the problem. The LE certificate is made out to mail.mydomain.org while I use imap.mydomain.org and smtp.mydomain.org (which are valid and resolve) in the mailclient settings. On the desktop client one just accepts the "problem" by accepting certificate mismatch as a permanent exception. Android does not offer this but when you replace imap and smtp with mail in the fqdn it all naturally works like a charm :)
