### ISSUE TITLE
Using modoboa just as a mailfilter quarantine management no webmail

### ISSUE THREAD

**Issue by stevie** [tonioo/modoboa#962]
Hi,  

I have installed this and it looks great for what im trying to do, great work!  However, I would not like the webmail component installed as im just trying to use it as a spam/virus filter/quarantine management tool.  So using the modoboa installer I have removed this from the installer.cfg 

For example:

extensions = modoboa-amavis modoboa-pdfcredentials modoboa-postfix-autoreply modoboa-sievefilters modoboa-stats

My question is on the notification side of things.  Can modoboa generate it's notifications whether it's an admin/user for a particular domain if the modoboa-webmail component is not installed?  I have tried installation a few times but it only seems to support notifications to a built in account (admin@webmail.address)

Is there something I could put into a config file to allow modoboa to send notifications to an external email address?

Any assistance or pointers would be greatly appreciated.

Thanks

Steve

**Comment by tonioo** [comment]
@stevie  what kind of notification are you talking about ?

**Comment by tonioo** [comment]
@stevie ping

**Comment by stevie** [comment]
Hi I'm basically wanting admin notifications for blocked email messages sent to either the specific admin for the domain or for domains with users that know the difference between a spam and real mail self release notifications. This seems to work when using a web account on the system but does not seem to work when the modoboa-webmail component is not installed from the documentation it looks like it is supported.  Sorry I have been very busy and not had much time to look about the documentation.

I think it's using something like lmtp:postdove to send the notifications but if you have not got modoboa-webmail installed then this obviously should be sent from something else was wondering if this is configureable from somewhere in the modoboa_installer\installer.cfg or would I need to manually change config files somewhere else to get email release notifications sent when postdov is not installed?

Thanks

Steve

**Comment by tonioo** [comment]
Actually, Modoboa itself does not send notifications to users (the only one concerns pending release requests). The notifications you're talking about are sent by amavis depending on your configuration.

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-amavis#39
