### ISSUE TITLE
Modoboa Installer doesn't fail, but Modoboa doesn't startup

### ISSUE THREAD

**Issue by Starz0r** [tonioo/modoboa#963]
I wrote this issue on the Modoboa Installer repo, but it got no attention, decided to post it here and see if it can get resolved.

Note: I tried the same setup on a Ubuntu 16.04 setup.

It seems when using the installer script that Nginx cannot bind it's self to the ports set at 80 and 443, and as such, Dovecot cannot startup. I've tried editing the nginx config to see if it can be fixed, as well as the installer options, but nothing seems to fix this.

I preformed the Install Script with Dependencies installed on a DigitalOcean droplet with 512MB of RAM, 20GB SSD, and Ubuntu 16.10 x64.

Is there any solutions?

**Comment by tonioo** [comment]
Have you tried with more RAM ? The minimum requirement is around 1G if you don't use clamav and 2G if you intend to use it.

Otherwise, have you run the installer using the --debug option ?

**Comment by tonioo** [comment]
Please don't open multiple issues for the same question. (https://github.com/modoboa/modoboa-installer/issues/70)
