### ISSUE TITLE
pam_unix(sudo:auth): authentication failure; logname=root

### ISSUE THREAD

**Issue by uberdave** [tonioo/modoboa#970]
My site refuses to connect with a pam error.(nginx won't restart)

pam_unix(sudo:auth): authentication failure; logname=root

from tail -f auth.log, when connecting:

: session opened for user vmail by (uid=0)
: pam_unix(cron:session): session opened for user root by (uid=0)
: pam_unix(cron:session): session closed for user root
: pam_unix(cron:session): session closed for user vmail

journalctl -xn for nginx
pam_unix(sudo:auth): authentication failure; logname=root uid=1000 euid=0 tty=/dev/pts/0

**Comment by tonioo** [comment]
Can you give more information about your context? How did you install Modoboa? What is your actual problem?

**Comment by uberdave** [comment]
I used the easy install on debian 8. at first the admin panel came up. Then I reinstalled with letsencrypt.
when I revisited the site, I was not able to load anything as, nginx failed to reboot, as I documented earlier. Since then, as I am on a vps, I rebuilt my droplet on Centos 6, and everything seems to be ok now, but I am going to wait a while before I try letsencrypt, again.  I want to thank you guys for your hard work and what appears to be great  software! I will be following. You can go ahead and close this, and, i'll post again, if the same thing happens again later with letsencrypt.

**Comment by tonioo** [comment]
Ok, thank you for the feedback.
