### ISSUE TITLE
Per Domain Bayes Learning

### ISSUE THREAD

**Issue by stalks** [tonioo/modoboa#976]
When I try and learn a mail using domain, the web panel doesn't respond.

![issue](http://image.prntscr.com/image/2a227ca180d04c788a84984629008d0b.png)

When clicking Validate nothing happens. If I select global database, it will work.

**Comment by stalks** [comment]
Some further investigation finds a 500 error on the request

`POST /quarantine/learning_recipient/ => generated 16141 bytes in 51 msecs (HTTP/1.1 500) 4 headers in 146 bytes (1 switches on core 0)`

**Comment by tonioo** [comment]
Can you activate the debug mode please? (set DEBUG to True inside settings.py and reload uwsgi)
You should get a complete error.
By the way, this error is not related to modoboa but to modoboa-amavis. I'll move it to the right repository.

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-amavis#38
