### ISSUE TITLE
SQLite: SQL prepare failed: no such function: now?

### ISSUE THREAD

**Issue by csmk** [tonioo/modoboa#977]
Hi,

I tried to experiment SQLite as db, but I got this error from Postfix:

```
Nov 25 19:32:20 domain postfix/cleanup[27161]: fatal: dict_sqlite_lookup: /etc/postfix/modoboa/sql-aliases.cf: SQL prepare failed: no such function: now?
```

The WebUI and dovecot is functioning properly. I'm using the latest (1.6.1) version.

**Comment by tonioo** [comment]
Looks like SQLite does not provide the `now()` function. Can you try to replace `now()` by `datetime('now')` in /etc/postfix/modoboa/sql-aliases.cf please?

**Comment by csmk** [comment]
Replaced, and it's working now! Thank you for the fast response.

Cheers! ;)
