### ISSUE TITLE
Aliases without "Expire at" date don't work

### ISSUE THREAD

**Issue by neutrinus** [tonioo/modoboa#978]
I'm using postgres, autogenerated configs:
` maildb=> SELECT alr.address FROM modoboa_admin_aliasrecipient AS alr INNER JOIN admin_alias AS al ON alr.alias_id=al.id WHERE al.enabled AND al.expire_at>now();`

If I leave empty 'expire at' date - the select doesn't return my alias. 

Please either make this field obligatory or change the query. Thank you

**Comment by tonioo** [comment]
I guess you're not using the latest version. Have you seen this: https://github.com/tonioo/modoboa/issues/922 ?

**Comment by neutrinus** [comment]
Yeah! I had maps from older version. Thank you!
