### ISSUE TITLE
Redundant alias for domain administrators

### ISSUE THREAD

**Issue by almereyda** [tonioo/modoboa#981]
If one intends to create a domain administrator with the username `postmaster@`, a redundant `postmaster@` alias pointing to the the very same address is created, too.

**Comment by tonioo** [comment]
Can you provide more info please? (screenshot, etc.)

**Comment by almereyda** [comment]
If I create a new user account with the role Domain Administrator that is already called `postmaster`, Modoboa will also create an alias from `postmaster` to `postmaster`, if the checkbox is marked.

Should we also consider creating more aliases, if needed?

See https://github.com/ecobytes/docker-postfix/blob/master/etc/postfix/global_alias for further examples.

**Comment by tonioo** [comment]
You mean that you already have an alias called 'postmaster@mydomain.tld'
and that you want to add a domain adminstrator with the same name after?

**Comment by almereyda** [comment]
No, other way round: I want to create a Domain Administrator user + mailbox
with the postmaster@ name, and keep "Create Aliases" checked. Then I will
end up with the desired mailbox, and an alias, carrying the same name,
redirecting to the mailbox.

**Comment by tonioo** [comment]
Ok, you're talking about domain creation with predefined admin and
aliases, right?

**Comment by almereyda** [comment]
Yes, I wanted to greate a general postmaster Account which would receive both hostmaster and postmaster aliases from various domains.

Can an account maintain multiple domains, too?

**Comment by tonioo** [comment]
You mean a domain administrator who manage more than one domain?

**Comment by almereyda** [comment]
Yes, that would be interesting. Maybe something like a Site or Farm
Administrator, so to speak.

**Comment by tonioo** [comment]
So you can already do it. Edit an administrator account and go to the
permissions tab, you can add more than one domain.
