### ISSUE TITLE
install error: dir /srv/modoboa/instance/media/webmail not exist

### ISSUE THREAD

**Issue by cmdtstof** [tonioo/modoboa#985]
hi
few days ago i installed modoboa on a live ub1604 system with no problem.
now trying to install it in a local (virtualbox ub1604) network i get

> 
> Installing modoboa
> Traceback (most recent call last):
>   File "./run.py", line 73, in <module>
>     main()
>   File "./run.py", line 63, in main
>     scripts.install("modoboa", config)
>   File "/home/user1/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
>     getattr(script, appname.capitalize())(config).run()
>   File "/home/user1/modoboa-installer/modoboa_installer/scripts/base.py", line 151, in run
>     self.post_run()
>   File "/home/user1/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 157, in post_run
>     self.apply_settings()
>   File "/home/user1/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 132, in apply_settings
>     utils.mkdir(d, stat.S_IRWXU | stat.S_IRWXG, pw[2], pw[3])
>   File "/home/user1/modoboa-installer/modoboa_installer/utils.py", line 79, in mkdir
>     os.mkdir(path, mode)
> OSError: [Errno 2] No such file or directory: '/srv/modoboa/instance/media/webmail'

???
thanks a lot (also for the great work)

**Comment by tonioo** [comment]
Could you please move your issue to the appropriate repository? (https://github.com/modoboa/modoboa-installer)

**Comment by tonioo** [comment]
Thank you.

**Comment by cmdtstof** [comment]
sorry! wrong place for this issue.
