### ISSUE TITLE
Postfix maps generated incompletely

### ISSUE THREAD

**Issue by almereyda** [tonioo/modoboa#987]
Since the breaking change from v1.5 to v1.6 to `generate_postfix_maps`, one issue has arosen, which revealed another.

When our Discourse wanted to send its notifications via SMTPS, it lately failed with some thousands of email jobs unfinished, resulting in the following logs at the involved MTA:

```
Dec  1 00:44:00 email postfix/submission/smtpd[13211]: connect from static.179.161.9.5.clients.your-server.de[5.9.161.179]
Dec  1 00:44:00 email postfix/submission/smtpd[13211]: Anonymous TLS connection established from static.179.161.9.5.clients.your-server.de[5.9.161.179]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
Dec  1 00:44:00 email postfix/submission/smtpd[13275]: warning: pgsql:/etc/postfix/sql-sender-login-mailboxes-extra.cf lookup error for "notifications+verp-hash@discourse.transformap.co"
Dec  1 00:44:00 email postfix/submission/smtpd[13275]: NOQUEUE: reject: RCPT from static.179.161.9.5.clients.your-server.de[5.9.161.179]: 451 4.3.0 <notifications+verp-hash@discourse.transformap.co>: Temporary lookup failure; from=<notifications+verp-hash@discourse.transformap.co> to=<redacted@gmail.com> proto=ESMTP helo=<localhost.localdomain>
Dec  1 00:44:00 email postfix/submission/smtpd[13275]: disconnect from static.179.161.9.5.clients.your-server.de[5.9.161.179]
```

It seems the original `/etc/postfix/sql-sender-login-mailboxes.cf` query `SELECT email FROM core_user WHERE email='%s' AND is_active` does not sanitize enough für `recipient_delimiter = +` enabled setups (standard with `modoboa-installer`), while there should be another rule which picks up [the last failing one in `smtpd_sender_login_maps`](https://modoboa.readthedocs.io/en/latest/upgrade.html#id1).

```
# cat /etc/postfix/sql-sender-login-mailboxes-extra.cf
...
query = SELECT mb.address || '@' || dom.name) FROM admin_mailbox mb INNER JOIN admin_senderaddress sad ON sad.mailbox_id=mb.id INNER JOIN admin_domain dom ON dom.id=mb.domain_id WHERE sad.address='%s'
```

Running the query manually in `psql` quickly also reveals a syntax error, which can be avoided easily. Unfortunately I was not able to find the pieces of code which are invoked upon calling `generate_postfix_maps`, as [GitHub search only reveals tests and documentation](https://github.com/tonioo/modoboa/search?utf8=%E2%9C%93&q=generate_postfix_maps).

**Comment by tonioo** [comment]
I guess you encountered this issue: https://github.com/tonioo/modoboa/issues/940 and I don't think it is related to `recipient_delimiter`.
@almereyda can you confirm this please, I'd like to release 1.6.2 today.

**Comment by almereyda** [comment]
@tonioo Yes, this seems to fix it. I had manually removed the `)` from the `.cf` file and soon the message log started to empty, while `tail -f /var/log/mail.log` revealed successful transfers.

**Comment by tonioo** [comment]
Great :)
